# Cleaning and merging ACS 2012-16 data files

These data will be merged with the full charter school data and web-scraping output and used in analysis.

Authors: Ji Shi (URAP research apprentice, undergraduate, UC Berkeley), Jaren Haber (PhD Candidate, Sociology, UC Berkeley)

Date: May 2018

In [2]:
import pandas as pd

In [4]:
sddata = pd.read_csv("../data/ACS_2016_sd-merged_FULL.csv", header = [0, 1], encoding = 'latin1', low_memory=False)

In [5]:
sddata

,FIPS,Name of Area,Qualifying Name,State/U.S.-Abbreviation (USPS),Summary Level,File Identification,Logical Record Number,State (FIPS),School District (Elementary),School District (Secondary),...,% Foreign-Born Population: Europe,% Foreign-Born Population: Asia,% Foreign-Born Population: Africa,% Foreign-Born Population: Oceania,% Foreign-Born Population: Americas,Total:,% Total: No Health Insurance Coverage,% Total: with Health Insurance Coverage,% Total: with Health Insurance Coverage: Public Health Coverage,% Total: with Health Insurance Coverage: Private Health Insurance
,Geo_FIPS,Geo_NAME,Geo_QName,Geo_STUSAB,Geo_SUMLEV,Geo_FILEID,Geo_LOGRECNO,Geo_STATE,Geo_SDELM,Geo_SDSEC,...,PCT_SE_T139_002,PCT_SE_T139_034,PCT_SE_T139_067,PCT_SE_T139_085,PCT_SE_T139_090,SE_T145_001,PCT_SE_T145_002,PCT_SE_T145_003,PCT_SE_T145_004,PCT_SE_T145_005
0,100001.0,"Fort Rucker School District, Alabama","Fort Rucker School District, Alabama",al,970,ACSSF,8710,1,NaN,NaN,...,6.30,48.03,0.00,0.00,45.67,2907,0.34,99.66,3.54,99.21
1,100003.0,"Maxwell AFB School District, Alabama","Maxwell AFB School District, Alabama",al,970,ACSSF,8711,1,NaN,NaN,...,3.06,19.39,7.14,0.00,70.41,811,0.86,99.14,2.59,97.78
2,100005.0,"Albertville City School District, Alabama","Albertville City School District, Alabama",al,970,ACSSF,8712,1,NaN,NaN,...,0.64,0.64,0.03,0.00,98.70,21160,20.83,79.17,38.21,51.86
3,100006.0,"Marshall County School District, Alabama","Marshall County School District, Alabama",al,970,ACSSF,8713,1,NaN,NaN,...,6.73,8.24,0.00,0.00,85.04,47895,14.19,85.81,36.90,63.19
4,100007.0,"Hoover City School District, Alabama","Hoover City School District, Alabama",al,970,ACSSF,8714,1,NaN,NaN,...,8.54,49.13,7.62,0.42,34.29,82783,6.33,93.67,21.62,84.40
5,100008.0,"Madison City School District, Alabama","Madison City School District, Alabama",al,970,ACSSF,8715,1,NaN,NaN,...,20.37,58.14,5.04,1.04,15.41,46087,6.15,93.85,17.51,87.81
6,100011.0,"Leeds City School District, Alabama","Leeds City School District, Alabama",al,970,ACSSF,8716,1,NaN,NaN,...,8.30,0.00,4.15,0.00,87.55,11701,7.39,92.61,33.41,74.10
7,100012.0,"Boaz City School District, Alabama","Boaz City School District, Alabama",al,970,ACSSF,8717,1,NaN,NaN,...,0.95,3.99,0.00,0.00,95.06,9518,13.27,86.73,40.30,58.87
8,100013.0,"Trussville City School District, Alabama","Trussville City School District, Alabama",al,970,ACSSF,8718,1,NaN,NaN,...,16.78,65.32,0.00,0.00,17.90,20752,2.58,97.42,20.35,90.04
9,100030.0,"Alexander City City School District, Alabama","Alexander City City School District, Alabama",al,970,ACSSF,8719,1,NaN,NaN,...,0.00,20.98,0.00,0.00,79.02,16874,12.88,87.12,48.03,53.18
10,100060.0,"Andalusia City School District, Alabama","Andalusia City School District, Alabama",al,970,ACSSF,8720,1,NaN,NaN,...,10.74,62.42,0.00,0.00,26.85,8717,13.22,86.78,40.61,61.58
11,100090.0,"Anniston City School District, Alabama","Anniston City School District, Alabama",al,970,ACSSF,8721,1,NaN,NaN,...,20.87,39.69,0.00,0.00,39.44,21522,13.02,86.98,51.18,55.16
12,100100.0,"Arab City School District, Alabama","Arab City School District, Alabama",al,970,ACSSF,8722,1,NaN,NaN,...,12.56,57.49,0.48,0.97,28.50,8118,10.36,89.64,36.36,68.81
13,100120.0,"Athens City School District, Alabama","Athens City School District, Alabama",al,970,ACSSF,8723,1,NaN,NaN,...,10.45,8.25,4.16,2.19,74.95,23883,13.78,86.22,33.90,64.99
14,100180.0,"Attalla City School District, Alabama","Attalla City School District, Alabama",al,970,ACSSF,8724,1,NaN,NaN,...,4.30,1.95,0.00,0.00,93.75,5781,15.57,84.43,38.45,58.23
15,100185.0,"Saraland City School District, Alabama","Saraland City School District, Alabama",al,970,ACSSF,8725,1,NaN,NaN,...,4.80,50.66,0.00,0.00,44.54,13751,12.36,87.64,32.00,71.03
16,100188.0,"Chickasaw City School District, Alabama","Chickasaw City School District, Alabama",al,970,ACSSF,8726,1,NaN,NaN,...,21.62,0.00,17.57,0.00,60.81,5943,17.16,82.84,47.05,46.27
17,100189.0,"Satsuma City School District, Alabama","Satsuma City School District, Alabama",al,970,ACSSF,8727,1,NaN,NaN,...,29.73,70.27,0.00,0.00,0.00,6102,7.29,92.71,24.45,76.97
18,100190.0,"Alabaster City School District, Alabama","Alabaster City School District, Alabama",al,970,ACSSF,8728,1,NaN,NaN,...,5.84,13.54,8.71,0.00,71.91,31970,11.32,88.68,23.07,75.46
19,100194.0,"Pelham City School District, Alabama","Pelham City School District, Alabama",al,970,ACSSF,8729,1,NaN,NaN,...,9.54,8.35,5.80,0.00,76.31,22519,10.48,89.52,21.63,80.04
20,100210.0,"Auburn City School District, Alabama","Auburn City School District, Alabama",al,970,ACSSF,8730,1,NaN,NaN,...,9.09,72.04,8.36,0.15,10.35,60113,6.48,93.52,16.73,85.23
21,100240.0,"Autauga County School District, Alabama","Autauga County School District, Alabama",al,970,ACSSF,8731,1,NaN,NaN,...,15.22,32.31,0.00,7.21,45.26,54387,8.92,91.08,31.71,72.73
22,100270.0,"Baldwin County School District, Alabama","Baldwin County School District, Alabama",al,970,ACSSF,8732,1,NaN,NaN,...,18.64,18.55,2.35,0.72,59.74,197046,11.80,88.20,34.49,68.50
23,100300.0,"Barbour County School District, Alabama","Barbour County School District, Alabama",al,970,ACSSF,8733,1,NaN,NaN,...,8.64,4.01,0.00,0.00,87.35,11141,13.47,86.53,50.67,52.37
24,100330.0,"Bessemer City School District, Alabama","Bessemer City School District, Alabama",al,970,ACSSF,8734,1,NaN,NaN,...,4.57,1.76,16.53,0.70,76.44,26350,16.74,83.26,49.31,47.58
25,100360.0,"Bibb County School District, Alabama","Bibb County School District, Alabama",al,970,ACSSF,8735,1,NaN,NaN,...,14.10,4.59,0.00,0.00,81.31,20598,9.03,90.97,38.15,66.30
26,100390.0,"Birmingham City School District, Alabama","Birmingham City School District, Alabama",al,970,ACSSF,8736,1,NaN,NaN,...,7.27,25.08,11.45,0.33,55.88,209221,14.90,85.10,41.87,54.08
27,100420.0,"Blount County School District, Alabama","Blount County School District, Alabama",al,970,ACSSF,8737,1,NaN,NaN,...,6.69,5.71,3.87,0.00,83.74,50993,10.76,89.24,35.78,67.68
28,100450.0,"Brewton City School District, Alabama","Brewton City School District, Alabama",al,970,ACSSF,8738,1,NaN,NaN,...,100.00,0.00,0.00,0.00,0.00,5208,13.42,86.58,43.66,56.57
29,100480.0,"Bullock County School District, Alabama","Bullock County School District, Alabama",al,970,ACSSF,8739,1,NaN,NaN,...,14.37,23.75,36.25,0.00,25.62,10170,16.74,83.26,45.80,48.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13376,4747034.0,"Crockett County School District in Bells, Tenn...","Crockett County School District in Bells, Tenn...",tn,960,ACSSF,10365,47,NaN,47034.0,...,0.00,6.08,0.00,0.00,93.92,3766,12.72,87.28,36.96,62.80
13377,4747073.0,"Hawkins County School District in Rogersville,...","Hawkins County School District in Rogersville,...",tn,960,ACSSF,10366,47,NaN,47073.0,...,0.00,50.00,26.92,0.00,23.08,4012,10.17,89.83,53.71,53.79
13378,4747077.0,"Henderson County School District in Lexington,...","Henderson County School District in Lexington,...",tn,960,ACSSF,10367,47,NaN,47077.0,...,0.00,9.17,0.00,0.00,90.83,7501,10.52,89.48,42.02,56.27
13379,4747079.0,"Henry County School District in Paris, Tennessee","Henry County School District in Paris, Tennessee",tn,960,ACSSF,10368,47,NaN,47079.0,...,30.08,46.34,23.58,0.00,0.00,11396,11.65,88.35,51.62,54.34
13380,4747107.0,"McMinn County School District in Athens, Tenne...","McMinn County School District in Athens, Tenne...",tn,960,ACSSF,10369,47,NaN,47107.0,...,7.20,19.54,0.00,3.08,70.18,13437,11.22,88.78,43.52,59.05
13381,4747108.0,"McMinn County School District in Etowah, Tenne...","McMinn County School District in Etowah, Tenne...",tn,960,ACSSF,10370,47,NaN,47108.0,...,0.00,0.00,0.00,0.00,100.00,3288,12.07,87.93,47.02,58.67
13382,4747123.0,"Monroe County School District in Sweetwater, T...","Monroe County School District in Sweetwater, T...",tn,960,ACSSF,10371,47,NaN,47123.0,...,30.12,16.54,0.00,0.00,53.33,11518,14.25,85.75,41.43,56.31
13383,4747143.0,"Rhea County School District in Dayton, Tennessee","Rhea County School District in Dayton, Tennessee",tn,960,ACSSF,10372,47,NaN,47143.0,...,9.03,10.32,0.00,0.00,80.65,7099,12.72,87.28,47.53,56.40
13384,4747149.0,Rutherford County School District in Murfreesb...,Rutherford County School District in Murfreesb...,tn,960,ACSSF,10373,47,NaN,47149.0,...,6.55,43.70,9.50,0.97,39.28,120493,11.14,88.86,22.49,74.52
13385,4747187.0,"Williamson County School District in Franklin,...","Williamson County School District in Franklin,...",tn,960,ACSSF,10374,47,NaN,47187.0,...,9.91,36.01,2.27,1.92,49.89,37943,10.10,89.90,23.16,77.57
13386,4747189.0,"Wilson County School District in Lebanon, Tenn...","Wilson County School District in Lebanon, Tenn...",tn,960,ACSSF,10375,47,NaN,47189.0,...,12.43,37.01,1.20,2.46,46.91,31424,11.65,88.35,36.25,63.21
13387,4799999.0,"Remainder of Tennessee, Tennessee","Remainder of Tennessee, Tennessee",tn,960,ACSSF,10376,47,NaN,99999.0,...,10.58,29.62,10.02,0.51,49.26,6152695,11.78,88.22,35.34,65.13
13388,4848021.0,Elgin/Giddings Independent School Districts (9...,Elgin/Giddings Independent School Districts (9...,tx,960,ACSSF,31825,48,NaN,48021.0,...,0.00,0.00,0.00,0.00,100.00,1752,21.75,78.25,27.00,60.27
13389,4848143.0,Stephenville Independent School District (9-12...,Stephenville Independent School District (9-12...,tx,960,ACSSF,31826,48,NaN,48143.0,...,0.00,0.00,0.00,0.00,100.00,880,15.34,84.66,35.45,62.61
13390,4848285.0,Hallettsville Independent School District (9-1...,Hallettsville Independent School District (9-1...,tx,960,ACSSF,31827,48,NaN,48285.0,...,33.33,0.00,0.00,0.00,66.67,894,10.18,89.82,29.53,75.95
13391,4848449.0,Mount Pleasant Independent School District (9-...,Mount Pleasant Independent School District (9-...,tx,960,ACSSF,31828,48,NaN,48449.0,...,0.00,0.00,0.00,0.00,100.00,894,29.75,70.25,42.28,34.79
13392,4899999.0,"Remainder of Texas, Texas","Remainder of Texas, Texas",tx,960,ACSSF,31829,48,NaN,99999.0,...,4.23,20.40,4.29,0.27,70.81,26474448,19.32,80.68,28.55,60.50
13393,5000006.0,"Essex Community Education Center, Vermont","Essex Community Education Center, Vermont",vt,960,ACSSF,2195,50,NaN,6.0,...,32.69,30.45,20.32,1.06,15.49,20626,3.12,96.88,28.67,80.28
13394,5099999.0,"Remainder of Vermont, Vermont","Remainder of Vermont, Vermont",vt,960,ACSSF,2196,50,NaN,99999.0,...,30.28,30.19,8.33,0.82,30.37,599590,5.36,94.64,40.94,67.83
13395,5505490.0,"Nicolet Union High School District, Wisconsin","Nicolet Union High School District, Wisconsin",wi,960,ACSSF,13066,55,NaN,5490.0,...,35.71,44.21,3.28,0.53,16.28,25234,4.06,95.94,29.24,82.92
13396,5506120.0,"Hartford Union High School District, Wisconsin","Hartford Union High School District, Wisconsin",wi,960,ACSSF,13067,55,NaN,6120.0,...,41.40,20.05,6.08,0.00,32.47,32501,5.70,94.30,23.89,82.61
13397,5506180.0,"Arrowhead Union High School District, Wisconsin","Arrowhead Union High School District, Wisconsin",wi,960,ACSSF,13068,55,NaN,6180.0,...,38.79,33.80,0.44,0.00,26.97,34056,4.06,95.94,20.24,87.47
13398,5507650.0,Lake Geneva-Genoa City Union High School Distr...,Lake Geneva-Genoa City Union High School Distr...,wi,960,ACSSF,13069,55,NaN,7650.0,...,18.71,10.58,0.00,0.00,70.71,24409,9.02,90.98,32.87,71.47
13399,5509630.0,"Lakeland Union High School District, Wisconsin","Lakeland Union High School District, Wisconsin",wi,960,ACSSF,13070,55,NaN,9630.0,...,44.65,24.28,0.00,0.00,31.07,17630,8.10,91.90,48.50,68.47
13400,5513290.0,"Westosha Central High School District, Wisconsin","Westosha Central High School District, Wisconsin",wi,960,ACSSF,13071,55,NaN,13290.0,...,41.60,30.72,3.84,0.00,23.84,20124,5.98,94.02,27.08,79.62
13401,5515150.0,"Union Grove Union High School District, Wisconsin","Union Grove Union High School District, Wisconsin",wi,960,ACSSF,13072,55,NaN,15150.0,...,26.21,33.33,0.00,0.00,40.46,12502,6.33,93.67,28.02,78.48
13402,5515480.0,"Big Foot Union High School District, Wisconsin","Big Foot Union High School District, Wisconsin",wi,960,ACSSF,13073,55,NaN,15480.0,...,29.25,1.77,0.27,0.54,68.16,9685,7.91,92.09,31.89,74.46
13403,5515600.0,"Waterford Union High School District, Wisconsin","Waterford Union High School District, Wisconsin",wi,960,ACSSF,13074,55,NaN,15600.0,...,35.90,37.77,1.86,0.00,24.47,18449,4.33,95.67,22.30,85.16
13404,5516770.0,"Wilmot Union High School District, Wisconsin","Wilmot Union High School District, Wisconsin",wi,960,ACSSF,13075,55,NaN,16770.0,...,28.39,14.98,0.00,0.00,56.62,19153,7.66,92.34,28.16,74.44
13405,5599999.0,"Remainder of Wisconsin, Wisconsin","Remainder of Wisconsin, Wisconsin",wi,960,ACSSF,13076,55,NaN,99999.0,...,16.68,35.40,4.09,0.40,43.43,5468148,7.24,92.76,32.20,73.49

In [9]:
sum(sddata[('% Total Population: White Alone', 'PCT_SE_T013_002')].notnull())

13395

In [6]:
list(sddata)

[('FIPS', 'Geo_FIPS'),
 ('Name of Area', 'Geo_NAME'),
 ('Qualifying Name', 'Geo_QName'),
 ('State/U.S.-Abbreviation (USPS)', 'Geo_STUSAB'),
 ('Summary Level', 'Geo_SUMLEV'),
 ('File Identification', 'Geo_FILEID'),
 ('Logical Record Number', 'Geo_LOGRECNO'),
 ('State (FIPS)', 'Geo_STATE'),
 ('School District (Elementary)', 'Geo_SDELM'),
 ('School District (Secondary)', 'Geo_SDSEC'),
 ('School District (Unified)', 'Geo_SDUNI'),
 ('Geographic Identifier', 'Geo_GEOID'),
 ('Area (Land)', 'Geo_AREALAND'),
 ('Area (Water)', 'Geo_AREAWATR'),
 ('Total Population', 'SE_T002_001'),
 ('Population Density (Per Sq. Mile)', 'SE_T002_002'),
 ('Area (Land)', 'SE_T002_003'),
 ('% Total Population: Under 18 Years', 'PCT_SE_T009_002'),
 ('% Total Population: 18 to 34 Years', 'PCT_SE_T009_003'),
 ('% Total Population: 35 to 64 Years', 'PCT_SE_T009_004'),
 ('% Total Population: 65 and Over', 'PCT_SE_T009_005'),
 ('% Total Population: White Alone', 'PCT_SE_T013_002'),
 ('% Total Population: Black or African American Alone', 'PCT_SE_T013_003'),
 ('% Total Population: American Indian and Alaska Native Alone',
  'PCT_SE_T013_004'),
 ('% Total Population: Asian Alone', 'PCT_SE_T013_005'),
 ('% Total Population: Native Hawaiian and Other Pacific Islander Alone',
  'PCT_SE_T013_006'),
 ('% Total Population: Some Other Race Alone', 'PCT_SE_T013_007'),
 ('% Total Population: Two or More Races', 'PCT_SE_T013_008'),
 ('Occupied Housing Units', 'SE_T165_001'),
 ('% Occupied Housing Units: Family Households', 'PCT_SE_T165_002'),
 ('% Occupied Housing Units: Family Households: Married-Couple Family',
  'PCT_SE_T165_003'),
 ('% Occupied Housing Units: Nonfamily Households', 'PCT_SE_T165_016'),
 ('% Occupied Housing Units: Nonfamily Households: Householder Living Alone',
  'PCT_SE_T165_017'),
 ('% Occupied Housing Units: With Related Children of the Householder Under 18',
  'PCT_SE_T167_002'),
 ('% Occupied Housing Units: No Related Children of the Householder Under 18',
  'PCT_SE_T167_008'),
 ('Population 15 Years and Over:', 'SE_T022_001'),
 ('% Population 15 Years and Over: Never Married', 'PCT_SE_T022_002'),
 ('% Population 15 Years and Over: Now Married (Not Including Separated)',
  'PCT_SE_T022_003'),
 ('% Population 15 Years and Over: Separated', 'PCT_SE_T022_004'),
 ('% Population 15 Years and Over: Widowed', 'PCT_SE_T022_005'),
 ('% Population 15 Years and Over: Divorced', 'PCT_SE_T022_006'),
 ('Population 25 Years and Over:', 'SE_T025_001'),
 ('% Population 25 Years and Over: Less than High School', 'PCT_SE_T025_002'),
 ('% Population 25 Years and Over: High School Graduate (Includes Equivalency)',
  'PCT_SE_T025_003'),
 ('% Population 25 Years and Over: Some College', 'PCT_SE_T025_004'),
 ("% Population 25 Years and Over: Bachelor's Degree", 'PCT_SE_T025_005'),
 ("% Population 25 Years and Over: Master's Degree", 'PCT_SE_T025_006'),
 ('% Population 25 Years and Over: Professional School Degree',
  'PCT_SE_T025_007'),
 ('% Population 25 Years and Over: Doctorate Degree', 'PCT_SE_T025_008'),
 ('Population 3 Years and Over:', 'SE_T028_001'),
 ('% Population 3 Years and Over: Enrolled in School', 'PCT_SE_T028_002'),
 ('% Population 3 Years and Over: Not Enrolled in School', 'PCT_SE_T028_003'),
 ('% Population 3 Years and Over Enrolled in School: Public School',
  'PCT_SE_T029_002'),
 ('% Population 3 Years and Over Enrolled in School: Public School: Pre-School',
  'PCT_SE_T029_003'),
 ('% Population 3 Years and Over Enrolled in School: Public School: K-8',
  'PCT_SE_T029_004'),
 ('% Population 3 Years and Over Enrolled in School: Public School: 9-12',
  'PCT_SE_T029_005'),
 ('% Population 3 Years and Over Enrolled in School: Public School: College',
  'PCT_SE_T029_006'),
 ('% Population 3 Years and Over Enrolled in School: Private School',
  'PCT_SE_T029_007'),
 ('% Population 3 Years and Over Enrolled in School: Private School: Pre-School',
  'PCT_SE_T029_008'),
 ('% Population 3 Years and Over Enrolled in School: Private School: K-8',
  'PCT_SE_T029_009'),
 ('% Population 3 Years and Over Enrolled in School: Private School: 9-12',
  'PCT_SE_T029_010'),
 ('% Population 3 Years and Over Enrolled in School: Private School: College',
  'PCT_SE_T029_011'),
 ('Civilian Population 16 to 19 Years:', 'SE_T030_001'),
 ('% Civilian Population 16 to 19 Years: Not High School Graduate, Not Enrolled (Dropped Out)',
  'PCT_SE_T030_002'),
 ('% Civilian Population 16 to 19 Years: High School Graduate, or Enrolled (in School)',
  'PCT_SE_T030_003'),
 ('% Civilian Population in Labor Force 16 Years and Over: Employed',
  'PCT_SE_T037_002'),
 ('% Civilian Population in Labor Force 16 Years and Over: Unemployed',
  'PCT_SE_T037_003'),
 ('% White Alone, Not Hispanic or Latino 16 Years Old  in&nbsp; Civilian Labor Force: Employed',
  'PCT_SE_T048_002'),
 ('% White Alone, Not Hispanic or Latino 16 Years Old  in&nbsp; Civilian Labor Force: Unemployed',
  'PCT_SE_T048_003'),
 ('% Employed Civilian Population 16 Years and Over: Agriculture, Forestry, Fishing and Hunting, and Mining',
  'PCT_SE_T049_002'),
 ('% Employed Civilian Population 16 Years and Over: Construction',
  'PCT_SE_T049_003'),
 ('% Employed Civilian Population 16 Years and Over: Manufacturing',
  'PCT_SE_T049_004'),
 ('% Employed Civilian Population 16 Years and Over: Wholesale Trade',
  'PCT_SE_T049_005'),
 ('% Employed Civilian Population 16 Years and Over: Retail Trade',
  'PCT_SE_T049_006'),
 ('% Employed Civilian Population 16 Years and Over: Transportation and Warehousing, and Utilities',
  'PCT_SE_T049_007'),
 ('% Employed Civilian Population 16 Years and Over: Information',
  'PCT_SE_T049_008'),
 ('% Employed Civilian Population 16 Years and Over: Finance and Insurance, and Real Estate and Rental  and Leasing',
  'PCT_SE_T049_009'),
 ('% Employed Civilian Population 16 Years and Over: Professional, Scientific, and Management, and  Administrative and Waste Management Services',
  'PCT_SE_T049_010'),
 ('% Employed Civilian Population 16 Years and Over: Educational Services, and Health Care and Social  Assistance',
  'PCT_SE_T049_011'),
 ('% Employed Civilian Population 16 Years and Over: Arts, Entertainment, and Recreation, and  Accommodation and Food Services',
  'PCT_SE_T049_012'),
 ('% Employed Civilian Population 16 Years and Over: Other Services, Except Public Administration',
  'PCT_SE_T049_013'),
 ('% Employed Civilian Population 16 Years and Over: Public Administration',
  'PCT_SE_T049_014'),
 ('% Employed Civilian Population 16 Years and Over: Unpaid Family Workers',
  'PCT_SE_T053_006'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars)',
  'SE_T057_001'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): White Alone Householder',
  'SE_T058_002'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): Black or African American Alone Householder',
  'SE_T058_003'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): American Indian and Alaska Native Alone  Householder',
  'SE_T058_004'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): Asian Alone',
  'SE_T058_005'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): Native Hawaiian and Other Pacific Islander Alone  Householder',
  'SE_T058_006'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): Some Other Race Alone Householder',
  'SE_T058_007'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): Two or More Races Householder',
  'SE_T058_008'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): Hispanic or Latino Householder',
  'SE_T058_009'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): White Alone Householder, Not Hispanic or Latino',
  'SE_T058_010'),
 ('Per Capita Income (In 2016 Inflation Adjusted Dollars)', 'SE_T083_001'),
 ('Gini Index', 'SE_T157_001'),
 ('Median Year Structure Built', 'SE_T098_001'),
 ('Median Value', 'SE_T101_001'),
 ('% Renter-Occupied Housing Units: Less than 10 Percent', 'PCT_SE_T103_002'),
 ('% Renter-Occupied Housing Units: 10 to 29 Percent', 'PCT_SE_T103_003'),
 ('% Renter-Occupied Housing Units: 30 to 49 Percent', 'PCT_SE_T103_004'),
 ('% Renter-Occupied Housing Units: 50 Percent or More', 'PCT_SE_T103_005'),
 ('% Renter-Occupied Housing Units: Not Computed', 'PCT_SE_T103_006'),
 ('% Families: Income in Below Poverty Level', 'PCT_SE_T113_002'),
 ('% Families: Income in at or Above Poverty Level', 'PCT_SE_T113_011'),
 ('Population Under 18 Years of Age for Whom Poverty Status Is Determined:',
  'SE_T114_001'),
 ('% Population Under 18 Years of Age for Whom Poverty Status Is Determined: Living in Poverty',
  'PCT_SE_T114_002'),
 ('% Population Under 18 Years of Age for Whom Poverty Status Is Determined: at or Above Poverty Level',
  'PCT_SE_T114_003'),
 ('% Total: Same House 1 Year Ago', 'PCT_SE_T130_002'),
 ('% Total: Moved Within Same County', 'PCT_SE_T130_003'),
 ('% Total: Moved From Different County Within Same State', 'PCT_SE_T130_004'),
 ('% Total: Moved From Different State', 'PCT_SE_T130_005'),
 ('% Total: Moved From Abroad', 'PCT_SE_T130_006'),
 ('% Total Population: Native Born', 'PCT_SE_T133_002'),
 ('% Total Population: Foreign Born', 'PCT_SE_T133_003'),
 ('% Total Population: Foreign Born: Naturalized Citizen', 'PCT_SE_T133_004'),
 ('% Total Population: Foreign Born: Not a Citizen', 'PCT_SE_T133_005'),
 ('% Foreign-Born Population: Europe', 'PCT_SE_T139_002'),
 ('% Foreign-Born Population: Asia', 'PCT_SE_T139_034'),
 ('% Foreign-Born Population: Africa', 'PCT_SE_T139_067'),
 ('% Foreign-Born Population: Oceania', 'PCT_SE_T139_085'),
 ('% Foreign-Born Population: Americas', 'PCT_SE_T139_090'),
 ('Total:', 'SE_T145_001'),
 ('% Total: No Health Insurance Coverage', 'PCT_SE_T145_002'),
 ('% Total: with Health Insurance Coverage', 'PCT_SE_T145_003'),
 ('% Total: with Health Insurance Coverage: Public Health Coverage',
  'PCT_SE_T145_004'),
 ('% Total: with Health Insurance Coverage: Private Health Insurance',
  'PCT_SE_T145_005')]

In [2]:
#read the CSVs that we want to concatenate
asc_uni = pd.read_csv("data/ACS_2016_school-district-unified_FULL.csv", header = [0,1], encoding = "latin1", low_memory = False)
asc_ele = pd.read_csv("data/ACS_2016_school-district-elementary_FULL.csv", header = [0,1], encoding = "latin1", low_memory = False)
asc_sec = pd.read_csv("data/ACS_2016_school-district-secondary_FULL.csv", header = [0,1], encoding = "latin1", low_memory = False)

asc_uni_sm = pd.read_csv("data/ACS_2016_school-district-unified_SMALL.csv", header = [0,1], encoding = "latin1", low_memory = False)
asc_ele_sm = pd.read_csv("data/ACS_2016_school-district-elementary_SMALL.csv", header = [0,1], encoding = "latin1", low_memory = False)
asc_sec_sm = pd.read_csv("data/ACS_2016_school-district-secondary_SMALL.csv", header = [0,1], encoding = "latin1", low_memory = False)

In [3]:
#turn their unique identifier to a common type
asc_uni['FIPS'] = asc_uni.FIPS.astype('float64')
asc_ele['FIPS'] = asc_ele.FIPS.astype('float64')
asc_sec['FIPS'] = asc_sec.FIPS.astype('float64')

asc_uni_sm['FIPS'] = asc_uni_sm.FIPS.astype('float64')
asc_ele_sm['FIPS'] = asc_ele_sm.FIPS.astype('float64')
asc_sec_sm['FIPS'] = asc_sec_sm.FIPS.astype('float64')

In [4]:
#concatenate them using pandas.concat, simple because columns are identical
#input is a list of dataframe that you want to concatenate
fullacs = pd.concat([asc_uni, asc_ele, asc_sec])
smallacs = pd.concat([asc_uni_sm, asc_ele_sm, asc_sec_sm])

In [5]:
# Define variables to drop from datasets (because empty or not useful)
smalldrops = [('Geographic Component', 'Geo_GEOCOMP'), ('US', 'Geo_US'), ('Region', 'Geo_REGION'), ('Division', 'Geo_DIVISION'), ('State (Census Code)', 'Geo_STATECE'), ('County', 'Geo_COUNTY'), ('County Subdivision (FIPS)', 'Geo_COUSUB'), ('Place (FIPS Code)', 'Geo_PLACE'), ('Place (State FIPS + Place FIPS)', 'Geo_PLACESE'), ('Census Tract', 'Geo_TRACT'), ('Block Group', 'Geo_BLKGRP'), ('Consolidated City', 'Geo_CONCIT'), ('American Indian Area/Alaska Native Area/Hawaiian Home Land (Census)', 'Geo_AIANHH'), ('American Indian Area/Alaska Native Area/Hawaiian Home Land (FIPS)', 'Geo_AIANHHFP'), ('American Indian Trust Land/Hawaiian Home Land Indicator', 'Geo_AIHHTLI'), ('American Indian Tribal Subdivision (Census)', 'Geo_AITSCE'), ('American Indian Tribal Subdivision (FIPS)', 'Geo_AITS'), ('Alaska Native Regional Corporation (FIPS)', 'Geo_ANRC'), ('Metropolitan and Micropolitan Statistical Area', 'Geo_CBSA'), ('Combined Statistical Area', 'Geo_CSA'), ('Metropolitan Division', 'Geo_METDIV'), ('Metropolitan Area Central City', 'Geo_MACC'), ('Metropolitan/Micropolitan Indicator Flag', 'Geo_MEMI'), ('New England City and Town Combined Statistical Area', 'Geo_NECTA'), ('New England City and Town Area', 'Geo_CNECTA'), ('New England City and Town Area Division', 'Geo_NECTADIV'), ('Urban Area', 'Geo_UA'), ('Urban Area Central Place', 'Geo_UACP'), ('Current Congressional District ***', 'Geo_CDCURR'), ('State Legislative District Upper', 'Geo_SLDU'), ('State Legislative District Lower', 'Geo_SLDL'), ('Voting District', 'Geo_VTD'), ('ZIP Code Tabulation Area (3-digit)', 'Geo_ZCTA3'), ('ZIP Code Tabulation Area (5-digit)', 'Geo_ZCTA5'), ('Subbarrio (FIPS)', 'Geo_SUBMCD'), ('Urban/Rural', 'Geo_UR'), ('Principal City Indicator', 'Geo_PCI'), ('Traffic Analysis Zone', 'Geo_TAZ'), ('Urban Growth Area', 'Geo_UGA'), ('Public Use Microdata Area - 5% File', 'Geo_PUMA5'), ('Public Use Microdata Area - 1% File', 'Geo_PUMA1'), ('Tribal Tract', 'Geo_BTTR'), ('Tribal Block Group', 'Geo_BTBG'), ('Total Population:', 'SE_T013_001'), ('Total Population: White Alone', 'SE_T013_002'), ('Total Population: Black or African American Alone', 'SE_T013_003'), ('Total Population: American Indian and Alaska Native Alone', 'SE_T013_004'), ('Total Population: Asian Alone', 'SE_T013_005'), ('Total Population: Native Hawaiian and Other Pacific Islander Alone', 'SE_T013_006'), ('Total Population: Some Other Race Alone', 'SE_T013_007'), ('Total Population: Two or More Races', 'SE_T013_008'), ('Population 25 Years and Over: Less than High School', 'SE_T025_002'), ('Population 25 Years and Over: High School Graduate (Includes Equivalency)', 'SE_T025_003'), ('Population 25 Years and Over: Some College', 'SE_T025_004'), ("Population 25 Years and Over: Bachelor's Degree", 'SE_T025_005'), ("Population 25 Years and Over: Master's Degree", 'SE_T025_006'), ('Population 25 Years and Over: Professional School Degree', 'SE_T025_007'), ('Population 25 Years and Over: Doctorate Degree', 'SE_T025_008'), ('Population 3 Years and Over: Enrolled in School', 'SE_T028_002'), ('Population 3 Years and Over: Not Enrolled in School', 'SE_T028_003'), ('Civilian Population 16 to 19 Years: Not High School Graduate, Not Enrolled (Dropped Out)', 'SE_T030_002'), ('Civilian Population 16 to 19 Years: High School Graduate, or Enrolled (in School)', 'SE_T030_003'), ('Civilian Population in Labor Force 16 Years and Over:', 'SE_T037_001'), ('Civilian Population in Labor Force 16 Years and Over: Employed', 'SE_T037_002'), ('Civilian Population in Labor Force 16 Years and Over: Unemployed', 'SE_T037_003'), ('Families:', 'SE_T113_001'), ('Families: Income in Below Poverty Level', 'SE_T113_002'), ('Families: Income in Below Poverty Level: Married Couple Family: with Related Child Living  Bellow Poverty Level', 'SE_T113_003'), ('Families: Income in Below Poverty Level: Married Couple Family: No Related Children Under 18 Years', 'SE_T113_004'), ('Families: Income in Below Poverty Level: Male Householder, No Wife Present', 'SE_T113_005'), ('Families: Income in Below Poverty Level: Male Householder, No Wife Present: with Related Children Under 18 Years', 'SE_T113_006'), ('Families: Income in Below Poverty Level: Male Householder, No Wife Present: No Related Children Under 18 Years', 'SE_T113_007'), ('Families: Income in Below Poverty Level: Female Householder, No Husband Present', 'SE_T113_008'), ('Families: Income in Below Poverty Level: Female Householder, No Husband Present: with Related Children Under 18 Years', 'SE_T113_009'), ('Families: Income in Below Poverty Level: Female Householder, No Husband Present: No Related Children Under 18 Years', 'SE_T113_010'), ('Families: Income in at or Above Poverty Level', 'SE_T113_011'), ('% Families: Income in Below Poverty Level: Married Couple Family: with Related Child Living  Bellow Poverty Level', 'PCT_SE_T113_003'), ('% Families: Income in Below Poverty Level: Married Couple Family: No Related Children Under 18 Years', 'PCT_SE_T113_004'), ('% Families: Income in Below Poverty Level: Male Householder, No Wife Present', 'PCT_SE_T113_005'), ('% Families: Income in Below Poverty Level: Male Householder, No Wife Present: with Related Children Under 18 Years', 'PCT_SE_T113_006'), ('% Families: Income in Below Poverty Level: Male Householder, No Wife Present: No Related Children Under 18 Years', 'PCT_SE_T113_007'), ('% Families: Income in Below Poverty Level: Female Householder, No Husband Present', 'PCT_SE_T113_008'), ('% Families: Income in Below Poverty Level: Female Householder, No Husband Present: with Related Children Under 18 Years', 'PCT_SE_T113_009'), ('% Families: Income in Below Poverty Level: Female Householder, No Husband Present: No Related Children Under 18 Years', 'PCT_SE_T113_010'), ('Population Under 18 Years of Age for Whom Poverty Status Is Determined: Living in Poverty', 'SE_T114_002'), ('Population Under 18 Years of Age for Whom Poverty Status Is Determined: at or Above Poverty Level', 'SE_T114_003'), ('Total:', 'SE_T130_001'), ('Total: Same House 1 Year Ago', 'SE_T130_002'), ('Total: Moved Within Same County', 'SE_T130_003'), ('Total: Moved From Different County Within Same State', 'SE_T130_004'), ('Total: Moved From Different State', 'SE_T130_005'), ('Total: Moved From Abroad', 'SE_T130_006'), ('Total Population:', 'SE_T133_001'), ('Total Population: Native Born', 'SE_T133_002'), ('Total Population: Foreign Born', 'SE_T133_003'), ('Total Population: Foreign Born: Naturalized Citizen', 'SE_T133_004'), ('Total Population: Foreign Born: Not a Citizen', 'SE_T133_005')]
fulldrops = [('Foreign-Born Population: Europe: Eastern Europe: Bosnia and Herzegovina', 'SE_T139_030'), ('Employed Civilian Population 16 Years and Over: Public Sector', 'SE_T053_003'), ('Foreign-Born Population: Americas: Latin America: Central America', 'SE_T139_100'), ('% Households: $20,000 to $24,999', 'PCT_SE_T056_005'), ('Foreign-Born Population: Asia: South Eastern Asia: Indonesia', 'SE_T139_052'), ('Foreign-Born Population: Africa: Southern Africa: South Africa', 'SE_T139_077'), ('Foreign-Born Population: Americas: Latin America: Caribbean: Barbados', 'SE_T139_093'), ('% Foreign-Born Population: Oceania: Australia and New Zealand Subregion', 'PCT_SE_T139_086'), ('Foreign-Born Population: Asia: South Eastern Asia: Other South Eastern Asia', 'SE_T139_057'), ('% Foreign-Born Population: Americas: Latin America: South America: Ecuador', 'PCT_SE_T139_115'), ('% Households: $35,000 to $39,999', 'PCT_SE_T056_008'), ('% Population 16 Years and Over: in Labor Force: in Armed Forces', 'PCT_SE_T033_003'), ('% Foreign-Born Population: Africa: Western Africa', 'PCT_SE_T139_079'), ('Population 3 Years and Over Enrolled in School: Private School: Pre-School', 'SE_T029_008'), ('Foreign-Born Population: Asia: Eastern Asia: China: China, Excluding Hong Kong and Taiwan', 'SE_T139_037'), ('Foreign-Born Population: Americas: Latin America: Caribbean: Other Caribbean', 'SE_T139_099'), ('% Occupied Housing Units: Family Households: Other Family: Male Householder, No Wife Present: Householder 35 to 64 Years', 'PCT_SE_T165_010'), ('% Foreign-Born Population: Americas: Latin America: Central America: El Salvador', 'PCT_SE_T139_103'), ('Foreign-Born Population: Americas: Latin America: Caribbean: Dominican Republic', 'SE_T139_095'), ('% Total Population: Under 5 Years', 'PCT_SE_T007_002'), ('Foreign-Born Population: Americas: Latin America: Caribbean: Haiti', 'SE_T139_096'), ('Total Population: 65 and Over', 'SE_T009_005'), ('% Foreign-Born Population: Africa: Eastern Africa: Other Eastern Africa', 'PCT_SE_T139_071'), ('% Foreign-Born Population: Europe: Northern Europe: United Kingdom: England', 'PCT_SE_T139_006'), ('Workers 16 Years and Over: Did Not Work at Home: 30 to 39 Minutes', 'SE_T129_006'), ('Foreign-Born Population: Africa: Western Africa: Other Western Africa', 'SE_T139_083'), ('Renter-Occupied Housing Units: $20,000 To $34,999', 'SE_T225_006'), ('White Alone, Not Hispanic or Latino 16 Years Old  in&nbsp; Civilian Labor Force: Unemployed', 'SE_T048_003'), ('Occupied Housing Units: No Related Children of the Householder Under 18', 'SE_T167_008'), ('Total Population: 15 to 17 Years', 'SE_T007_005'), ('% Occupied Housing Units: Family Households: Other Family: Male Householder, No Wife Present: Householder 15 to 34 Years', 'PCT_SE_T165_009'), ('Foreign-Born Population: Americas: Latin America: Caribbean: Jamaica', 'SE_T139_097'), ('% Occupied Housing Units: Nonfamily Households: Householder Living Alone: Householder 15 to 34 Years', 'PCT_SE_T165_018'), ('Population 15 Years and Over: Separated', 'SE_T022_004'), ('% Renter-Occupied Housing Units: $35,000 To $49,999', 'PCT_SE_T225_010'), ('% Foreign-Born Population: Africa: Eastern Africa: Ethiopia', 'PCT_SE_T139_069'), ('Occupied Housing Units: Family Households: Other Family: Male Householder, No Wife Present: Householder 35 to 64 Years', 'SE_T165_010'), ('% Foreign-Born Population: Europe: Eastern Europe: Serbia', 'PCT_SE_T139_031'), ('Population 16 Years and Over: in Labor Force: Civilian', 'SE_T033_004'), ('Total Population: 75 to 84 Years', 'SE_T007_012'), ('Employed Civilian Population 16 Years and Over: Manufacturing', 'SE_T049_004'), ('% Workers 16 Years and Over: Did Not Work at Home: Less than 10 Minutes', 'PCT_SE_T129_003'), ('Population 3 Years and Over Enrolled in School: Private School: College', 'SE_T029_011'), ('Households: $15,000 to $19,999', 'SE_T056_004'), ('Population 3 Years and Over Enrolled in School: Public School', 'SE_T029_002'), ('% Foreign-Born Population: Asia: Western Asia: Iraq', 'PCT_SE_T139_059'), ('Occupied Housing Units: Family Households: Other Family: Male Householder, No Wife Present: Householder 65 Years and Over', 'SE_T165_011'), ('Foreign-Born Population: Americas: Latin America: South America: Chile', 'SE_T139_113'), ('Total Population: 85 Years and Over', 'SE_T007_013'), ('Foreign-Born Population: Oceania: Australia and New Zealand Subregion: Australia', 'SE_T139_087'), ('% Foreign-Born Population: Asia: Western Asia: Other Western Asia', 'PCT_SE_T139_065'), ('% Renter-Occupied Housing Units: Less Than $20,000: 30 Percent or More', 'PCT_SE_T225_005'), ('Average Commute to Work (in Min)', 'SE_T147_001'), ('Foreign-Born Population:', 'SE_T139_001'), ('Average Household Income (In 2016 Inflation Adjusted Dollars): Hispanic or Latino Householder', 'SE_T060_009'), ('% Foreign-Born Population: Asia: Eastern Asia: China: China, Excluding Hong Kong and Taiwan', 'PCT_SE_T139_037'), ('Foreign-Born Population: Oceania: Australia and New Zealand Subregion: Other Australian and New Zealand Subregion', 'SE_T139_088'), ('Foreign-Born Population: Americas: Latin America: South America', 'SE_T139_109'), ('% Foreign-Born Population: Africa: Western Africa: Nigeria', 'PCT_SE_T139_082'), ('Renter-Occupied Housing Units: Less Than $20,000: 20 To 29 Percent', 'SE_T225_004'), ('Foreign-Born Population: Asia: Eastern Asia', 'SE_T139_035'), ('Foreign-Born Population: Africa', 'SE_T139_067'), ('Employed Civilian Population 16 Years and Over:', 'SE_T140_001'), ('% Occupied Housing Units: Family Households: Other Family: Female Householder, No Husband Present: Householder 35 to 64 Years', 'PCT_SE_T165_014'), ('% Total Population: 5 to 9 Years', 'PCT_SE_T007_003'), ('% Foreign-Born Population: Europe: Western Europe: Austria', 'PCT_SE_T139_011'), ('Occupied Housing Units: Nonfamily Households', 'SE_T165_016'), ('% Foreign-Born Population: Asia: South Eastern Asia: Thailand', 'PCT_SE_T139_055'), ('Population 15 Years and Over: Now Married (Not Including Separated)', 'SE_T022_003'), ('Employed Civilian Population 16 Years and Over: Educational Services, and Health Care and Social  Assistance', 'SE_T049_011'), ('% Renter-Occupied Housing Units: $50,000 To $74,999: 20 To 29 Percent', 'PCT_SE_T225_016'), ('% Foreign-Born Population: Europe: Eastern Europe: Croatia', 'PCT_SE_T139_023'), ('Employed Civilian Population 16 Years and Over: Other Services, Except Public Administration', 'SE_T049_013'), ('Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved Within Same County', 'SE_T233_003'), ('Average Household Income (In 2016 Inflation Adjusted Dollars): White Alone Householder', 'SE_T060_002'), ('% Workers 16 Years and Over: Did Not Work at Home: 30 to 39 Minutes', 'PCT_SE_T129_006'), ('Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different County Within Same State', 'SE_T233_004'), ('Foreign-Born Population: Asia: South Eastern Asia', 'SE_T139_050'), ('% Foreign-Born Population: Americas: Latin America: Caribbean: Other Caribbean', 'PCT_SE_T139_099'), ('Average Household Income (In 2016 Inflation Adjusted Dollars): Asian Alone', 'SE_T060_005'), ('% Foreign-Born Population: Americas: Latin America: Caribbean: Haiti', 'PCT_SE_T139_096'), ('Occupied Housing Units: Nonfamily Households: Householder Living Alone: Householder 35 to 64 Years', 'SE_T165_019'), ('% Employed Civilian Population 16 Years and Over: Construction, Extraction, and Maintenance  Occupations', 'PCT_SE_T140_006'), ('Renter-Occupied Housing Units: $20,000 To $34,999: 20 To 29 Percent', 'SE_T225_008'), ('Foreign-Born Population: Asia: South Central Asia: India', 'SE_T139_046'), ('Area Total: Area (Water)', 'SE_T003_003'), ('Employed Civilian Population 16 Years and Over: Arts, Entertainment, and Recreation, and  Accommodation and Food Services', 'SE_T049_012'), ('Households: $50,000 to $59,999', 'SE_T056_011'), ('% Households: $150,000 to $199,999', 'PCT_SE_T056_016'), ('% Renter-Occupied Housing Units: $20,000 To $34,999', 'PCT_SE_T225_006'), ('% Foreign-Born Population: Asia: Eastern Asia: Korea', 'PCT_SE_T139_041'), ('% Employed Civilian Population 16 Years and Over: Production, Transportation, and Material Moving  Occupations: Production Occupations', 'PCT_SE_T140_008'), ('% Foreign-Born Population: Asia: South Eastern Asia: Cambodia', 'PCT_SE_T139_051'), ('% Workers 16 Years and Over: Did Not Work at Home: 20 to 29 Minutes', 'PCT_SE_T129_005'), ('Population 16 Years and Over: in Labor Force: Civilian: Employed', 'SE_T033_005'), ('% Total Population: 85 Years and Over', 'PCT_SE_T007_013'), ('Foreign-Born Population: Africa: Northern Africa', 'SE_T139_073'), ('Foreign-Born Population: Africa: Northern Africa: Egypt', 'SE_T139_074'), ('% Foreign-Born Population: Asia: South Eastern Asia: Laos', 'PCT_SE_T139_053'), ('% Workers 16 Years and Over: Did Not Work at Home: 60 to 89 Minutes', 'PCT_SE_T129_008'), ('% Foreign-Born Population: Asia: Eastern Asia: China: Hong Kong', 'PCT_SE_T139_038'), ('% Area Total: Area (Land)', 'PCT_SE_T003_002'), ('% Employed Civilian Population 16 Years and Over: Public Sector', 'PCT_SE_T053_003'), ('Foreign-Born Population: Americas: Latin America: South America: Uruguay', 'SE_T139_118'), ('% Occupied Housing Units: Nonfamily Households: Householder Not Living Alone: Householder 65 Years and Over', 'PCT_SE_T165_024'), ('% Foreign-Born Population: Oceania: Oceania, n.e.c.', 'PCT_SE_T139_089'), ('Average Household Income (In 2016 Inflation Adjusted Dollars): American Indian and Alaska Native Alone  Householder', 'SE_T060_004'), ('White Alone, Not Hispanic or Latino 16 Years Old  in Civilian Labor Force:', 'SE_T048_001'), ('Occupied Housing Units: Family Households: Married-Couple Family: Householder 35 to 64 Years', 'SE_T165_005'), ('Foreign-Born Population: Asia: Eastern Asia: China: Hong Kong', 'SE_T139_038'), ('% Households: $125,000 to $149,999', 'PCT_SE_T056_015'), ('Foreign-Born Population: Americas: Latin America: Central America: Other Central America', 'SE_T139_108'), ('% Workers 16 Years and Over: Did Not Work at Home: 90 or More Minutes', 'PCT_SE_T129_009'), ('% Foreign-Born Population: Americas: Latin America: South America: Guyana', 'PCT_SE_T139_116'), ('% Foreign-Born Population: Europe: Europe, n.e.c.', 'PCT_SE_T139_033'), ('% Foreign-Born Population: Africa: Western Africa: Ghana', 'PCT_SE_T139_080'), ('Total Population: 18 to 24 Years', 'SE_T007_006'), ('Employed Civilian Population 16 Years and Over: Self-Employed (Incorporated and Not Incorporated)', 'SE_T053_004'), ('Foreign-Born Population: Americas: Latin America: South America: Brazil', 'SE_T139_112'), ('Foreign-Born Population: Europe: Europe, n.e.c.', 'SE_T139_033'), ('% Occupied Housing Units: With Related Children of the Householder Under 18: With Own Children of the Householder Under 18: Under 6 Years Only', 'PCT_SE_T167_004'), ('Average Household Income (In 2016 Inflation Adjusted Dollars): Two or More Races Householder', 'SE_T060_008'), ('% Foreign-Born Population: Americas: Latin America: Caribbean: Cuba', 'PCT_SE_T139_094'), ('Foreign-Born Population: Asia: South Central Asia: Iran', 'SE_T139_047'), ('Foreign-Born Population: Americas: Latin America: South America: Venezuela', 'SE_T139_119'), ('% Foreign-Born Population: Asia: South Eastern Asia: Other South Eastern Asia', 'PCT_SE_T139_057'), ('Foreign-Born Population: Americas: Latin America: Central America: Costa Rica', 'SE_T139_102'), ('Total Population: 45 to 54 Years', 'SE_T007_009'), ('% Renter-Occupied Housing Units: $50,000 To $74,999: 30 Percent or More', 'PCT_SE_T225_017'), ('% Foreign-Born Population: Americas: Northern America: Other Northern America', 'PCT_SE_T139_123'), ('% Renter-Occupied Housing Units: $20,000 To $34,999: 30 Percent or More', 'PCT_SE_T225_009'), ('Average Household Income (In 2016 Inflation Adjusted Dollars): Native Hawaiian and Other Pacific Islander Alone  Householder', 'SE_T060_006'), ('% Occupied Housing Units: Nonfamily Households: Householder Living Alone: Householder 35 to 64 Years', 'PCT_SE_T165_019'), ('Workers 16 Years and Over: Worked at Home', 'SE_T129_010'), ('Population 15 Years and Over: Never Married', 'SE_T022_002'), ('Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: ', 'SE_T233_001'), ('Total Population', 'SE_T001_001'), ('% Foreign-Born Population: Americas: Latin America: Central America: Guatemala', 'PCT_SE_T139_104'), ('Foreign-Born Population: Africa: Eastern Africa: Kenya', 'SE_T139_070'), ('Occupied Housing Units: Nonfamily Households: Householder Living Alone: Householder 65 Years and Over', 'SE_T165_020'), ('Renter-Occupied Housing Units: Less Than $20,000: 30 Percent or More', 'SE_T225_005'), ('Households: $10,000 to $14,999', 'SE_T056_003'), ('Foreign-Born Population: Asia: South Central Asia: Afghanistan', 'SE_T139_044'), ('% Foreign-Born Population: Asia: Western Asia: Turkey', 'PCT_SE_T139_063'), ('% Foreign-Born Population: Europe: Northern Europe: Ireland', 'PCT_SE_T139_008'), ('Occupied Housing Units: With Related Children of the Householder Under 18: With Own Children of the Householder Under 18: Under 6 Years and 6 to 17 Years', 'SE_T167_005'), ('Population 16 Years and Over: Not in Labor Force', 'SE_T033_007'), ('Households: $40,000 to $44,999', 'SE_T056_009'), ('Foreign-Born Population: Europe: Eastern Europe: Other Eastern Europe', 'SE_T139_032'), ('Households: $35,000 to $39,999', 'SE_T056_008'), ('% Population 16 Years and Over: Not in Labor Force', 'PCT_SE_T033_007'), ('% Foreign-Born Population: Europe: Eastern Europe: Bosnia and Herzegovina', 'PCT_SE_T139_030'), ('% Occupied Housing Units: Family Households: Married-Couple Family: Householder 15 to 34 Years', 'PCT_SE_T165_004'), ('Total Population:', 'SE_T009_001'), ('Households: $45,000 to $49,999', 'SE_T056_010'), ('Households: $25,000 to $29,999', 'SE_T056_006'), ('Foreign-Born Population: Europe: Western Europe: France', 'SE_T139_012'), ('% Foreign-Born Population: Africa: Southern Africa: Other Southern Africa', 'PCT_SE_T139_078'), ('Total Population: 35 to 64 Years', 'SE_T009_004'), ('Foreign-Born Population: Asia: South Eastern Asia: Cambodia', 'SE_T139_051'), ('% Foreign-Born Population: Europe: Southern Europe: Other Southern Europe', 'PCT_SE_T139_021'), ('Employed Civilian Population 16 Years and Over: Private Non-Profit', 'SE_T053_005'), ('% Occupied Housing Units: Family Households: Married-Couple Family: Householder 35 to 64 Years', 'PCT_SE_T165_005'), ('% Occupied Housing Units: Family Households: Other Family: Female Householder, No Husband Present: Householder 15 to 34 Years', 'PCT_SE_T165_013'), ('% Foreign-Born Population: Asia: Western Asia: Israel', 'PCT_SE_T139_060'), ('Households: $60,000 to $74,999', 'SE_T056_012'), ('Renter-Occupied Housing Units: 30 to 49 Percent', 'SE_T103_004'), ('Foreign-Born Population: Europe: Western Europe: Other Western Europe', 'SE_T139_015'), ('Average Household Income (In 2016 Inflation Adjusted Dollars)', 'SE_T059_001'), ('Population 3 Years and Over Enrolled in School: Public School: 9-12', 'SE_T029_005'), ('% Occupied Housing Units: Family Households: Other Family: Male Householder, No Wife Present', 'PCT_SE_T165_008'), ('Foreign-Born Population: Americas: Latin America: Caribbean', 'SE_T139_092'), ('Foreign-Born Population: Europe: Western Europe: Germany', 'SE_T139_013'), ('Foreign-Born Population: Asia: Eastern Asia: Korea', 'SE_T139_041'), ('% Employed Civilian Population 16 Years and Over: Production, Transportation, and Material Moving  Occupations', 'PCT_SE_T140_007'), ('% Foreign-Born Population: Oceania: Australia and New Zealand Subregion: Other Australian and New Zealand Subregion', 'PCT_SE_T139_088'), ('% Households: $25,000 to $29,999', 'PCT_SE_T056_006'), ('Foreign-Born Population: Asia: Western Asia: Israel', 'SE_T139_060'), ('Foreign-Born Population: Americas: Latin America: South America: Guyana', 'SE_T139_116'), ('Households: $150,000 to $199,999', 'SE_T056_016'), ('% Foreign-Born Population: Asia: South Central Asia: Afghanistan', 'PCT_SE_T139_044'), ('Foreign-Born Population: Europe: Northern Europe: United Kingdom: United Kingdom, Excluding England and Scotland', 'SE_T139_005'), ('Foreign-Born Population: Europe: Northern Europe: Ireland', 'SE_T139_008'), ('Foreign-Born Population: Asia: Eastern Asia: Other Eastern Asia', 'SE_T139_042'), ('Foreign-Born Population: Asia: Western Asia: Turkey', 'SE_T139_063'), ('Renter-Occupied Housing Units: $35,000 To $49,999: 20 To 29 Percent', 'SE_T225_012'), ('Average Household Income (In 2016 Inflation Adjusted Dollars): Black or African American Alone Householder', 'SE_T060_003'), ('% Renter-Occupied Housing Units: Less Than $20,000: 20 To 29 Percent', 'PCT_SE_T225_004'), ('% Foreign-Born Population: Americas: Latin America: Central America: Panama', 'PCT_SE_T139_107'), ('Foreign-Born Population: Asia: Western Asia: Syria', 'SE_T139_062'), ('% Foreign-Born Population: Europe: Western Europe: Other Western Europe', 'PCT_SE_T139_015'), ('% Total Population: 25 to 34 Years', 'PCT_SE_T007_007'), ('Foreign-Born Population: Africa: Middle Africa', 'SE_T139_072'), ('% Foreign-Born Population: Asia: South Eastern Asia', 'PCT_SE_T139_050'), ('% Employed Civilian Population 16 Years and Over: Production, Transportation, and Material Moving  Occupations: Transportation and Material Moving Occupations', 'PCT_SE_T140_009'), ('% Renter-Occupied Housing Units: $35,000 To $49,999: 20 To 29 Percent', 'PCT_SE_T225_012'), ('Foreign-Born Population: Europe: Northern Europe: Other Northern Europe', 'SE_T139_009'), ('% Foreign-Born Population: Africa: Southern Africa', 'PCT_SE_T139_076'), ('% Foreign-Born Population: Europe: Eastern Europe: Czechoslovakia (Includes Czech Republic and Slovakia)', 'PCT_SE_T139_024'), ('Occupied Housing Units: Nonfamily Households: Householder Living Alone: Householder 15 to 34 Years', 'SE_T165_018'), ('Foreign-Born Population: Asia: South Central Asia: Pakistan', 'SE_T139_048'), ('Population 3 Years and Over Enrolled in School: Private School', 'SE_T029_007'), ('Renter-Occupied Housing Units', 'SE_T225_001'), ('Foreign-Born Population: Americas: Latin America', 'SE_T139_091'), ('Foreign-Born Population: Americas: Latin America: Caribbean: Trinidad and Tobago', 'SE_T139_098'), ('Employed Civilian Population 16 Years and Over: Public Administration', 'SE_T049_014'), ('Foreign-Born Population: Europe: Western Europe: Netherlands', 'SE_T139_014'), ('Foreign-Born Population: Americas: Latin America: South America: Other South America', 'SE_T139_120'), ('% Foreign-Born Population: Africa: Eastern Africa', 'PCT_SE_T139_068'), ('Employed Civilian Population 16 Years and Over: Production, Transportation, and Material Moving  Occupations', 'SE_T140_007'), ('% Occupied Housing Units: With Related Children of the Householder Under 18: No Own Children of the Householder Under 18', 'PCT_SE_T167_007'), ('Employed Civilian Population 16 Years and Over: Finance and Insurance, and Real Estate and Rental  and Leasing', 'SE_T049_009'), ('% Foreign-Born Population: Africa: Western Africa: Liberia', 'PCT_SE_T139_081'), ('% Population 16 Years and Over: in Labor Force', 'PCT_SE_T033_002'), ('Average Household Income (In 2016 Inflation Adjusted Dollars): Some Other Race Alone Householder', 'SE_T060_007'), ('% Renter-Occupied Housing Units: No Cash Rent', 'PCT_SE_T225_023'), ('Employed Civilian Population 16 Years and Over', 'SE_T049_001'), ('Foreign-Born Population: Americas: Latin America: Central America: Honduras', 'SE_T139_105'), ('Foreign-Born Population: Americas: Latin America: Central America: Nicaragua', 'SE_T139_106'), ('% Households: $45,000 to $49,999', 'PCT_SE_T056_010'), ('Occupied Housing Units: Family Households', 'SE_T165_002'), ('% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: ', 'PCT_SE_T233_001'), ('% Employed Civilian Population 16 Years and Over: Management, Professional, and Related Occupations', 'PCT_SE_T140_002'), ('% Foreign-Born Population: Americas: Latin America: South America: Argentina', 'PCT_SE_T139_110'), ('Occupied Housing Units: Family Households: Married-Couple Family: Householder 15 to 34 Years', 'SE_T165_004'), ('% Foreign-Born Population: Asia: Western Asia: Armenia', 'PCT_SE_T139_064'), ('Renter-Occupied Housing Units: Less Than $20,000', 'SE_T225_002'), ('Foreign-Born Population: Europe: Northern Europe: United Kingdom', 'SE_T139_004'), ('Occupied Housing Units: Family Households: Other Family', 'SE_T165_007'), ('% Foreign-Born Population: Americas: Latin America: Central America: Mexico', 'PCT_SE_T139_101'), ('Employed Civilian Population 16 Years and Over: Sales and Office Occupations', 'SE_T140_004'), ('Total Population: 5 to 9 Years', 'SE_T007_003'), ('% Foreign-Born Population: Asia: South Central Asia: Iran', 'PCT_SE_T139_047'), ('% Renter-Occupied Housing Units: $75,000 or More: 20 To 29 Percent', 'PCT_SE_T225_020'), ('% Renter-Occupied Housing Units: $75,000 or More', 'PCT_SE_T225_018'), ('% Foreign-Born Population: Americas: Northern America', 'PCT_SE_T139_121'), ('Foreign-Born Population: Europe: Eastern Europe: Russia', 'SE_T139_028'), ('% Occupied Housing Units: Family Households: Other Family: Female Householder, No Husband Present', 'PCT_SE_T165_012'), ('Renter-Occupied Housing Units: $35,000 To $49,999: Less Than 20 Percent', 'SE_T225_011'), ('Foreign-Born Population: Asia: South Eastern Asia: Vietnam', 'SE_T139_056'), ('% Foreign-Born Population: Europe: Eastern Europe: Russia', 'PCT_SE_T139_028'), ('% Renter-Occupied Housing Units: $20,000 To $34,999: 20 To 29 Percent', 'PCT_SE_T225_008'), ('Population 16 Years and Over: in Labor Force: Civilian: Unemployed', 'SE_T033_006'), ('Occupied Housing Units: Family Households: Other Family: Male Householder, No Wife Present: Householder 15 to 34 Years', 'SE_T165_009'), ('Households: $75,000 to $99,999', 'SE_T056_013'), ('Occupied Housing Units: Nonfamily Households: Householder Not Living Alone: Householder 35 to 64 Years', 'SE_T165_023'), ('% Total Population: 75 to 84 Years', 'PCT_SE_T007_012'), ('Population 3 Years and Over Enrolled in School: Public School: K-8', 'SE_T029_004'), ('% Renter-Occupied Housing Units: $50,000 To $74,999: Less Than 20 Percent', 'PCT_SE_T225_015'), ('% Households: $10,000 to $14,999', 'PCT_SE_T056_003'), ('Foreign-Born Population: Asia: Asia, n.e.c.', 'SE_T139_066'), ('% Foreign-Born Population: Europe: Southern Europe: Spain', 'PCT_SE_T139_020'), ('Employed Civilian Population 16 Years and Over: Construction', 'SE_T049_003'), ('Foreign-Born Population: Asia: Western Asia: Armenia', 'SE_T139_064'), ('Foreign-Born Population: Europe: Eastern Europe: Ukraine', 'SE_T139_029'), ('% Employed Civilian Population 16 Years and Over: Farming, Fishing, and Forestry Occupations', 'PCT_SE_T140_005'), ('% Foreign-Born Population: Americas: Latin America: South America: Bolivia', 'PCT_SE_T139_111'), ('% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Abroad', 'PCT_SE_T233_006'), ('Foreign-Born Population: Asia: Western Asia: Other Western Asia', 'SE_T139_065'), ('Foreign-Born Population: Europe: Southern Europe', 'SE_T139_016'), ('% Workers 16 Years and Over: Did Not Work at Home: 40 to 59 Minutes', 'PCT_SE_T129_007'), ('Foreign-Born Population: Oceania', 'SE_T139_085'), ('% Foreign-Born Population: Americas: Latin America: Central America: Nicaragua', 'PCT_SE_T139_106'), ('Employed Civilian Population 16 Years and Over: Production, Transportation, and Material Moving  Occupations: Production Occupations', 'SE_T140_008'), ('Employed Civilian Population 16 Years and Over: Transportation and Warehousing, and Utilities', 'SE_T049_007'), ('Area Total: Area (Land)', 'SE_T003_002'), ('% Foreign-Born Population: Europe: Northern Europe: Other Northern Europe', 'PCT_SE_T139_009'), ('Population 16 Years and Over: in Labor Force', 'SE_T033_002'), ('% Occupied Housing Units: Nonfamily Households: Householder Not Living Alone: Householder 15 to 34 Years', 'PCT_SE_T165_022'), ('Workers 16 Years and Over: Did Not Work at Home: 60 to 89 Minutes', 'SE_T129_008'), ('Occupied Housing Units: Family Households: Other Family: Female Householder, No Husband Present: Householder 65 Years and Over', 'SE_T165_015'), ('% Foreign-Born Population: Europe: Eastern Europe', 'PCT_SE_T139_022'), ('% Foreign-Born Population: Europe: Western Europe: Netherlands', 'PCT_SE_T139_014'), ('% Foreign-Born Population: Europe: Northern Europe', 'PCT_SE_T139_003'), ('% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Same House 1 Year Ago', 'PCT_SE_T233_002'), ('% Foreign-Born Population: Asia: South Central Asia: Pakistan', 'PCT_SE_T139_048'), ('Households:', 'SE_T056_001'), ('% Renter-Occupied Housing Units: Zero or Negative Income', 'PCT_SE_T225_022'), ('Population 3 Years and Over Enrolled in School', 'SE_T029_001'), ('% Foreign-Born Population: Europe: Eastern Europe: Poland', 'PCT_SE_T139_026'), ('Workers 16 Years and Over: Did Not Work at Home: 10 to 19 Minutes', 'SE_T129_004'), ('% Foreign-Born Population: Africa: Northern Africa', 'PCT_SE_T139_073'), ('Occupied Housing Units: Family Households: Other Family: Male Householder, No Wife Present', 'SE_T165_008'), ('Occupied Housing Units: Nonfamily Households: Householder Living Alone', 'SE_T165_017'), ('Renter-Occupied Housing Units: $75,000 or More: 30 Percent or More', 'SE_T225_021'), ('Households: $100,000 to $124,999', 'SE_T056_014'), ('% Foreign-Born Population: Americas: Latin America', 'PCT_SE_T139_091'), ('% Foreign-Born Population: Americas: Latin America: Central America: Other Central America', 'PCT_SE_T139_108'), ('Foreign-Born Population: Asia: South Eastern Asia: Philippines', 'SE_T139_054'), ('Foreign-Born Population: Asia', 'SE_T139_034'), ('% Total Population: 18 to 24 Years', 'PCT_SE_T007_006'), ('Foreign-Born Population: Asia: South Central Asia: Other South Central Asia', 'SE_T139_049'), ('% Foreign-Born Population: Asia: Western Asia: Lebanon', 'PCT_SE_T139_061'), ('% Foreign-Born Population: Asia: South Central Asia: Bangladesh', 'PCT_SE_T139_045'), ('% Employed Civilian Population 16 Years and Over: Private Sector', 'PCT_SE_T053_002'), ('Renter-Occupied Housing Units: $50,000 To $74,999', 'SE_T225_014'), ('Renter-Occupied Housing Units: $20,000 To $34,999: Less Than 20 Percent', 'SE_T225_007'), ('Foreign-Born Population: Europe: Eastern Europe', 'SE_T139_022'), ('Employed Civilian Population 16 Years and Over: Unpaid Family Workers', 'SE_T053_006'), ('Renter-Occupied Housing Units: $75,000 or More: 20 To 29 Percent', 'SE_T225_020'), ('% Renter-Occupied Housing Units: $35,000 To $49,999: 30 Percent or More', 'PCT_SE_T225_013'), ('Renter-Occupied Housing Units:', 'SE_T103_001'), ('Renter-Occupied Housing Units: No Cash Rent', 'SE_T225_023'), ('% Foreign-Born Population: Asia: South Central Asia', 'PCT_SE_T139_043'), ('% Households: $30,000 to $34,999', 'PCT_SE_T056_007'), ('Population 15 Years and Over: Divorced', 'SE_T022_006'), ('% Foreign-Born Population: Asia: Eastern Asia: China', 'PCT_SE_T139_036'), ('Foreign-Born Population: Africa: Eastern Africa', 'SE_T139_068'), ('Foreign-Born Population: Oceania: Oceania, n.e.c.', 'SE_T139_089'), ('Foreign-Born Population: Europe: Southern Europe: Spain', 'SE_T139_020'), ('% Foreign-Born Population: Europe: Southern Europe: Italy', 'PCT_SE_T139_018'), ('Foreign-Born Population: Africa: Southern Africa', 'SE_T139_076'), ('% Foreign-Born Population: Asia: Asia, n.e.c.', 'PCT_SE_T139_066'), ('Foreign-Born Population: Americas: Northern America: Other Northern America', 'SE_T139_123'), ('Workers 16 Years and Over:', 'SE_T129_001'), ('Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different State', 'SE_T233_005'), ('Renter-Occupied Housing Units: $20,000 To $34,999: 30 Percent or More', 'SE_T225_009'), ('Foreign-Born Population: Europe: Eastern Europe: Czechoslovakia (Includes Czech Republic and Slovakia)', 'SE_T139_024'), ('Foreign-Born Population: Africa: Southern Africa: Other Southern Africa', 'SE_T139_078'), ('Foreign-Born Population: Americas', 'SE_T139_090'), ('Population 3 Years and Over Enrolled in School: Public School: College', 'SE_T029_006'), ('% Foreign-Born Population: Americas: Latin America: Caribbean: Dominican Republic', 'PCT_SE_T139_095'), ('% Foreign-Born Population: Europe: Southern Europe: Portugal', 'PCT_SE_T139_019'), ('% Renter-Occupied Housing Units: $20,000 To $34,999: Less Than 20 Percent', 'PCT_SE_T225_007'), ('Average Household Income (In 2016 Inflation Adjusted Dollars):', 'SE_T060_001'), ('% Foreign-Born Population: Europe: Southern Europe: Greece', 'PCT_SE_T139_017'), ('Employed Civilian Population 16 Years and Over: Information', 'SE_T049_008'), ('Occupied Housing Units: With Related Children of the Householder Under 18: With Own Children of the Householder Under 18: 6 to 17 Years', 'SE_T167_006'), ('% Households: $40,000 to $44,999', 'PCT_SE_T056_009'), ('Occupied Housing Units', 'SE_T167_001'), ('% Renter-Occupied Housing Units: $50,000 To $74,999', 'PCT_SE_T225_014'), ('% Foreign-Born Population: Asia: Eastern Asia: Japan', 'PCT_SE_T139_040'), ('% Workers 16 Years and Over: Did Not Work at Home: 10 to 19 Minutes', 'PCT_SE_T129_004'), ('Renter-Occupied Housing Units: $50,000 To $74,999: 20 To 29 Percent', 'SE_T225_016'), ('Foreign-Born Population: Europe: Western Europe: Austria', 'SE_T139_011'), ('Foreign-Born Population: Americas: Latin America: South America: Bolivia', 'SE_T139_111'), ('% Foreign-Born Population: Africa: Northern Africa: Egypt', 'PCT_SE_T139_074'), ('% Foreign-Born Population: Asia: Western Asia: Syria', 'PCT_SE_T139_062'), ('Foreign-Born Population: Europe: Northern Europe: United Kingdom: Scotland', 'SE_T139_007'), ('Total Population: 18 to 34 Years', 'SE_T009_003'), ('Occupied Housing Units: With Related Children of the Householder Under 18: With Own Children of the Householder Under 18', 'SE_T167_003'), ('% Total Population: 15 to 17 Years', 'PCT_SE_T007_005'), ('Occupied Housing Units: Family Households: Married-Couple Family', 'SE_T165_003'), ('% Foreign-Born Population: Europe: Northern Europe: United Kingdom', 'PCT_SE_T139_004'), ('Renter-Occupied Housing Units: Less Than $20,000: Less Than 20 Percent', 'SE_T225_003'), ('Employed Civilian Population 16 Years and Over: Professional, Scientific, and Management, and  Administrative and Waste Management Services', 'SE_T049_010'), ('Total Population: 25 to 34 Years', 'SE_T007_007'), ('Total Population: 10 to 14 Years', 'SE_T007_004'), ('Average Household Income (In 2016 Inflation Adjusted Dollars): White Alone Householder, Not Hispanic or Latino', 'SE_T060_010'), ('% Occupied Housing Units: Nonfamily Households: Householder Not Living Alone', 'PCT_SE_T165_021'), ('Occupied Housing Units: With Related Children of the Householder Under 18: No Own Children of the Householder Under 18', 'SE_T167_007'), ('% Workers 16 Years and Over: Worked at Home', 'PCT_SE_T129_010'), ('% Foreign-Born Population: Asia: Eastern Asia: Other Eastern Asia', 'PCT_SE_T139_042'), ('% Households: $50,000 to $59,999', 'PCT_SE_T056_011'), ('% Foreign-Born Population: Africa: Southern Africa: South Africa', 'PCT_SE_T139_077'), ('% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different County Within Same State', 'PCT_SE_T233_004'), ('% Occupied Housing Units: Nonfamily Households: Householder Living Alone: Householder 65 Years and Over', 'PCT_SE_T165_020'), ('% Foreign-Born Population: Americas: Latin America: South America: Peru', 'PCT_SE_T139_117'), ('% Foreign-Born Population: Americas: Latin America: Caribbean: Jamaica', 'PCT_SE_T139_097'), ('% Foreign-Born Population: Americas: Latin America: Central America', 'PCT_SE_T139_100'), ('% Total Population: 35 to 44 Years', 'PCT_SE_T007_008'), ('% Total Population: 10 to 14 Years', 'PCT_SE_T007_004'), ('Employed Civilian Population 16 Years and Over: Construction, Extraction, and Maintenance  Occupations', 'SE_T140_006'), ('Foreign-Born Population: Europe: Northern Europe: United Kingdom: England', 'SE_T139_006'), ('% Occupied Housing Units: With Related Children of the Householder Under 18: With Own Children of the Householder Under 18', 'PCT_SE_T167_003'), ('Area Total:', 'SE_T003_001'), ('Occupied Housing Units: Family Households: Other Family: Female Householder, No Husband Present', 'SE_T165_012'), ('Occupied Housing Units: Family Households: Other Family: Female Householder, No Husband Present: Householder 35 to 64 Years', 'SE_T165_014'), ('Workers 16 Years and Over: Did Not Work at Home: 20 to 29 Minutes', 'SE_T129_005'), ('Total: No Health Insurance Coverage', 'SE_T145_002'), ('Households: $125,000 to $149,999', 'SE_T056_015'), ('% Foreign-Born Population: Europe: Western Europe: Germany', 'PCT_SE_T139_013'), ('Foreign-Born Population: Asia: Eastern Asia: China', 'SE_T139_036'), ('Renter-Occupied Housing Units: Less than 10 Percent', 'SE_T103_002'), ('Foreign-Born Population: Americas: Latin America: Central America: Guatemala', 'SE_T139_104'), ('% Foreign-Born Population: Americas: Latin America: Caribbean', 'PCT_SE_T139_092'), ('% Foreign-Born Population: Africa: Middle Africa', 'PCT_SE_T139_072'), ('Foreign-Born Population: Europe: Eastern Europe: Poland', 'SE_T139_026'), ('Employed Civilian Population 16 Years and Over: Farming, Fishing, and Forestry Occupations', 'SE_T140_005'), ('Renter-Occupied Housing Units: $50,000 To $74,999: 30 Percent or More', 'SE_T225_017'), ('% Renter-Occupied Housing Units: $75,000 or More: 30 Percent or More', 'PCT_SE_T225_021'), ('Total: with Health Insurance Coverage', 'SE_T145_003'), ('Foreign-Born Population: Americas: Northern America: Canada', 'SE_T139_122'), ('Employed Civilian Population 16 Years and Over: Wholesale Trade', 'SE_T049_005'), ('Total Population: 65 to 74 Years', 'SE_T007_011'), ('Renter-Occupied Housing Units: 10 to 29 Percent', 'SE_T103_003'), ('% Renter-Occupied Housing Units: $75,000 or More: Less Than 20 Percent', 'PCT_SE_T225_019'), ('Foreign-Born Population: Asia: South Central Asia: Bangladesh', 'SE_T139_045'), ('Population 3 Years and Over Enrolled in School: Private School: K-8', 'SE_T029_009'), ('% Foreign-Born Population: Americas: Latin America: South America: Colombia', 'PCT_SE_T139_114'), ('Median Household Income (In 2016 Inflation Adjusted Dollars):', 'SE_T058_001'), ('Workers 16 Years and Over: Did Not Work at Home: 40 to 59 Minutes', 'SE_T129_007'), ('Occupied Housing Units: Nonfamily Households: Householder Not Living Alone: Householder 15 to 34 Years', 'SE_T165_022'), ('Occupied Housing Units: Nonfamily Households: Householder Not Living Alone', 'SE_T165_021'), ('Foreign-Born Population: Americas: Latin America: South America: Peru', 'SE_T139_117'), ('Population 1 Year and Over in Households in the United States', 'SE_T233_007'), ('% Renter-Occupied Housing Units: Less Than $20,000: Less Than 20 Percent', 'PCT_SE_T225_003'), ('% Households: $60,000 to $74,999', 'PCT_SE_T056_012'), ('Population 3 Years and Over Enrolled in School: Private School: 9-12', 'SE_T029_010'), ('Foreign-Born Population: Europe: Eastern Europe: Hungary', 'SE_T139_025'), ('% Households: Less than $10,000', 'PCT_SE_T056_002'), ('Renter-Occupied Housing Units: Zero or Negative Income', 'SE_T225_022'), ('Employed Civilian Population 16 Years and Over: Management, Professional, and Related Occupations', 'SE_T140_002'), ('Foreign-Born Population: Asia: Eastern Asia: China: Taiwan', 'SE_T139_039'), ('% Foreign-Born Population: Europe: Eastern Europe: Romania', 'PCT_SE_T139_027'), ('Foreign-Born Population: Asia: Eastern Asia: Japan', 'SE_T139_040'), ('Occupied Housing Units: With Related Children of the Householder Under 18', 'SE_T167_002'), ('% Renter-Occupied Housing Units: $35,000 To $49,999: Less Than 20 Percent', 'PCT_SE_T225_011'), ('% Workers 16 Years and Over: Did Not Work at Home', 'PCT_SE_T129_002'), ('Renter-Occupied Housing Units: Not Computed', 'SE_T103_006'), ('% Population 16 Years and Over: in Labor Force: Civilian: Unemployed', 'PCT_SE_T033_006'), ('Foreign-Born Population: Europe', 'SE_T139_002'), ('Housing Units', 'SE_T093_001'), ('% Total Population: 55 to 64 Years', 'PCT_SE_T007_010'), ('% Occupied Housing Units: With Related Children of the Householder Under 18: With Own Children of the Householder Under 18: Under 6 Years and 6 to 17 Years', 'PCT_SE_T167_005'), ('Foreign-Born Population: Americas: Latin America: Central America: Panama', 'SE_T139_107'), ('Occupied Housing Units: Family Households: Other Family: Female Householder, No Husband Present: Householder 15 to 34 Years', 'SE_T165_013'), ('Total Population: 35 to 44 Years', 'SE_T007_008'), ('Foreign-Born Population: Americas: Latin America: South America: Argentina', 'SE_T139_110'), ('Foreign-Born Population: Americas: Latin America: South America: Ecuador', 'SE_T139_115'), ('% Foreign-Born Population: Oceania: Australia and New Zealand Subregion: Australia', 'PCT_SE_T139_087'), ('Population 3 Years and Over Enrolled in School: Public School: Pre-School', 'SE_T029_003'), ('% Households: $100,000 to $124,999', 'PCT_SE_T056_014'), ('% Foreign-Born Population: Americas: Latin America: South America: Venezuela', 'PCT_SE_T139_119'), ('% Foreign-Born Population: Americas: Latin America: South America', 'PCT_SE_T139_109'), ('% Foreign-Born Population: Europe: Western Europe', 'PCT_SE_T139_010'), ('Average Household Size', 'SE_T021_001'), ('Households: $200,000 or More', 'SE_T056_017'), ('% Foreign-Born Population: Europe: Western Europe: France', 'PCT_SE_T139_012'), ('Employed Civilian Population 16 Years and Over:', 'SE_T053_001'), ('Foreign-Born Population: Africa: Western Africa: Nigeria', 'SE_T139_082'), ('% Total Population: 45 to 54 Years', 'PCT_SE_T007_009'), ('Foreign-Born Population: Americas: Latin America: Central America: Mexico', 'SE_T139_101'), ('% Foreign-Born Population: Americas: Latin America: Caribbean: Trinidad and Tobago', 'PCT_SE_T139_098'), ('% Foreign-Born Population: Asia: South Central Asia: India', 'PCT_SE_T139_046'), ('Foreign-Born Population: Europe: Southern Europe: Italy', 'SE_T139_018'), ('% Foreign-Born Population: Africa: Northern Africa: Other Northern Africa', 'PCT_SE_T139_075'), ('Foreign-Born Population: Americas: Latin America: Central America: El Salvador', 'SE_T139_103'), ('Total Population: Under 5 Years', 'SE_T007_002'), ('Employed Civilian Population 16 Years and Over: Private Sector', 'SE_T053_002'), ('% Foreign-Born Population: Africa: Africa, n.e.c.', 'PCT_SE_T139_084'), ('Households: $20,000 to $24,999', 'SE_T056_005'), ('Foreign-Born Population: Africa: Eastern Africa: Other Eastern Africa', 'SE_T139_071'), ('% Foreign-Born Population: Asia: South Central Asia: Other South Central Asia', 'PCT_SE_T139_049'), ('Population 16 Years and Over: in Labor Force: in Armed Forces', 'SE_T033_003'), ('Renter-Occupied Housing Units: 50 Percent or More', 'SE_T103_005'), ('Foreign-Born Population: Europe: Southern Europe: Greece', 'SE_T139_017'), ('% Foreign-Born Population: Americas: Latin America: South America: Chile', 'PCT_SE_T139_113'), ('Foreign-Born Population: Asia: Western Asia', 'SE_T139_058'), ('Population 16 Years and Over:', 'SE_T033_001'), ('Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Same House 1 Year Ago', 'SE_T233_002'), ('Total Population: Under 18 Years', 'SE_T009_002'), ('Foreign-Born Population: Europe: Northern Europe', 'SE_T139_003'), ('Renter-Occupied Housing Units: $50,000 To $74,999: Less Than 20 Percent', 'SE_T225_015'), ('% Households: $75,000 to $99,999', 'PCT_SE_T056_013'), ('Foreign-Born Population: Asia: South Eastern Asia: Laos', 'SE_T139_053'), ('% Population 16 Years and Over: in Labor Force: Civilian: Employed', 'PCT_SE_T033_005'), ('% Foreign-Born Population: Americas: Northern America: Canada', 'PCT_SE_T139_122'), ('% Households: $200,000 or More', 'PCT_SE_T056_017'), ('% Employed Civilian Population 16 Years and Over: Self-Employed (Incorporated and Not Incorporated)', 'PCT_SE_T053_004'), ('% Foreign-Born Population: Africa: Western Africa: Other Western Africa', 'PCT_SE_T139_083'), ('Foreign-Born Population: Oceania: Australia and New Zealand Subregion', 'SE_T139_086'), ('% Foreign-Born Population: Asia: South Eastern Asia: Indonesia', 'PCT_SE_T139_052'), ('Employed Civilian Population 16 Years and Over: Agriculture, Forestry, Fishing and Hunting, and Mining', 'SE_T049_002'), ('% Occupied Housing Units: With Related Children of the Householder Under 18: With Own Children of the Householder Under 18: 6 to 17 Years', 'PCT_SE_T167_006'), ('Workers 16 Years and Over: Did Not Work at Home', 'SE_T129_002'), ('Foreign-Born Population: Asia: South Eastern Asia: Thailand', 'SE_T139_055'), ('Total: with Health Insurance Coverage: Private Health Insurance', 'SE_T145_005'), ('% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved Within Same County', 'PCT_SE_T233_003'), ('% Foreign-Born Population: Europe: Eastern Europe: Ukraine', 'PCT_SE_T139_029'), ('Renter-Occupied Housing Units: $75,000 or More: Less Than 20 Percent', 'SE_T225_019'), ('Workers 16 Years and Over: Did Not Work at Home: 90 or More Minutes', 'SE_T129_009'), ('Workers 16 Years and Over: Did Not Work at Home: Less than 10 Minutes', 'SE_T129_003'), ('Foreign-Born Population: Africa: Western Africa: Liberia', 'SE_T139_081'), ('% Renter-Occupied Housing Units: Less Than $20,000', 'PCT_SE_T225_002'), ('Total: with Health Insurance Coverage: Public Health Coverage', 'SE_T145_004'), ('Households: Less than $10,000', 'SE_T056_002'), ('% Foreign-Born Population: Europe: Northern Europe: United Kingdom: Scotland', 'PCT_SE_T139_007'), ('% Foreign-Born Population: Americas: Latin America: South America: Brazil', 'PCT_SE_T139_112'), ('% Foreign-Born Population: Americas: Latin America: South America: Other South America', 'PCT_SE_T139_120'), ('% Employed Civilian Population 16 Years and Over: Sales and Office Occupations', 'PCT_SE_T140_004'), ('Employed Civilian Population 16 Years and Over: Production, Transportation, and Material Moving  Occupations: Transportation and Material Moving Occupations', 'SE_T140_009'), ('% Foreign-Born Population: Asia: South Eastern Asia: Philippines', 'PCT_SE_T139_054'), ('% Foreign-Born Population: Americas: Latin America: South America: Uruguay', 'PCT_SE_T139_118'), ('% Employed Civilian Population 16 Years and Over: Service Occupations', 'PCT_SE_T140_003'), ('Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Abroad', 'SE_T233_006'), ('Employed Civilian Population 16 Years and Over: Service Occupations', 'SE_T140_003'), ('Foreign-Born Population: Asia: Western Asia: Iraq', 'SE_T139_059'), ('Foreign-Born Population: Africa: Western Africa: Ghana', 'SE_T139_080'), ('Foreign-Born Population: Europe: Eastern Europe: Serbia', 'SE_T139_031'), ('% Foreign-Born Population: Europe: Southern Europe', 'PCT_SE_T139_016'), ('% Foreign-Born Population: Americas: Latin America: Central America: Costa Rica', 'PCT_SE_T139_102'), ('% Occupied Housing Units: Family Households: Other Family: Female Householder, No Husband Present: Householder 65 Years and Over', 'PCT_SE_T165_015'), ('Foreign-Born Population: Europe: Southern Europe: Other Southern Europe', 'SE_T139_021'), ('Foreign-Born Population: Asia: South Central Asia', 'SE_T139_043'), ('% Foreign-Born Population: Asia: South Eastern Asia: Vietnam', 'PCT_SE_T139_056'), ('% Area Total: Area (Water)', 'PCT_SE_T003_003'), ('% Population 16 Years and Over: in Labor Force: Civilian', 'PCT_SE_T033_004'), ('% Occupied Housing Units: Family Households: Other Family', 'PCT_SE_T165_007'), ('Foreign-Born Population: Asia: Western Asia: Lebanon', 'SE_T139_061'), ('Foreign-Born Population: Europe: Eastern Europe: Croatia', 'SE_T139_023'), ('% Foreign-Born Population: Europe: Northern Europe: United Kingdom: United Kingdom, Excluding England and Scotland', 'PCT_SE_T139_005'), ('% Total Population: 65 to 74 Years', 'PCT_SE_T007_011'), ('% Foreign-Born Population: Asia: Western Asia', 'PCT_SE_T139_058'), ('% Foreign-Born Population: Americas: Latin America: Caribbean: Barbados', 'PCT_SE_T139_093'), ('% Foreign-Born Population: Europe: Eastern Europe: Other Eastern Europe', 'PCT_SE_T139_032'), ('Foreign-Born Population: Africa: Western Africa', 'SE_T139_079'), ('Foreign-Born Population: Africa: Northern Africa: Other Northern Africa', 'SE_T139_075'), ('Foreign-Born Population: Africa: Africa, n.e.c.', 'SE_T139_084'), ('Occupied Housing Units: Nonfamily Households: Householder Not Living Alone: Householder 65 Years and Over', 'SE_T165_024'), ('% Occupied Housing Units: Family Households: Married-Couple Family: Householder 65 Years and Over', 'PCT_SE_T165_006'), ('Employed Civilian Population 16 Years and Over: Retail Trade', 'SE_T049_006'), ('Total Population: 55 to 64 Years', 'SE_T007_010'), ('% Occupied Housing Units: Family Households: Other Family: Male Householder, No Wife Present: Householder 65 Years and Over', 'PCT_SE_T165_011'), ('Occupied Housing Units: Family Households: Married-Couple Family: Householder 65 Years and Over', 'SE_T165_006'), ('Population 15 Years and Over: Widowed', 'SE_T022_005'), ('Foreign-Born Population: Europe: Southern Europe: Portugal', 'SE_T139_019'), ('% Foreign-Born Population: Europe: Eastern Europe: Hungary', 'PCT_SE_T139_025'), ('Households: $30,000 to $34,999', 'SE_T056_007'), ('Foreign-Born Population: Africa: Eastern Africa: Ethiopia', 'SE_T139_069'), ('Renter-Occupied Housing Units: $35,000 To $49,999', 'SE_T225_010'), ('% Foreign-Born Population: Asia: Eastern Asia', 'PCT_SE_T139_035'), ('% Households: $15,000 to $19,999', 'PCT_SE_T056_004'), ('Foreign-Born Population: Americas: Latin America: South America: Colombia', 'SE_T139_114'), ('Foreign-Born Population: Europe: Western Europe', 'SE_T139_010'), ('% Population 1 Year and Over in Households in the United States: Householder Lived in Renter-Occupied Housing Units: Moved From Different State', 'PCT_SE_T233_005'), ('Renter-Occupied Housing Units: $75,000 or More', 'SE_T225_018'), ('% Foreign-Born Population: Asia: Eastern Asia: China: Taiwan', 'PCT_SE_T139_039'), ('Renter-Occupied Housing Units: $35,000 To $49,999: 30 Percent or More', 'SE_T225_013'), ('% Foreign-Born Population: Americas: Latin America: Central America: Honduras', 'PCT_SE_T139_105'), ('Occupied Housing Units: With Related Children of the Householder Under 18: With Own Children of the Householder Under 18: Under 6 Years Only', 'SE_T167_004'), ('White Alone, Not Hispanic or Latino 16 Years Old  in&nbsp; Civilian Labor Force: Employed', 'SE_T048_002'), ('% Employed Civilian Population 16 Years and Over: Private Non-Profit', 'PCT_SE_T053_005'), ('% Foreign-Born Population: Africa: Eastern Africa: Kenya', 'PCT_SE_T139_070'), ('Foreign-Born Population: Americas: Latin America: Caribbean: Cuba', 'SE_T139_094'), ('Foreign-Born Population: Europe: Eastern Europe: Romania', 'SE_T139_027'), ('Total Population:', 'SE_T007_001'), ('Foreign-Born Population: Americas: Northern America', 'SE_T139_121'), ('% Occupied Housing Units: Nonfamily Households: Householder Not Living Alone: Householder 35 to 64 Years', 'PCT_SE_T165_023'), ('Geographic Component', 'Geo_GEOCOMP'), ('US', 'Geo_US'), ('Region', 'Geo_REGION'), ('Division', 'Geo_DIVISION'), ('State (Census Code)', 'Geo_STATECE'), ('County', 'Geo_COUNTY'), ('County Subdivision (FIPS)', 'Geo_COUSUB'), ('Place (FIPS Code)', 'Geo_PLACE'), ('Place (State FIPS + Place FIPS)', 'Geo_PLACESE'), ('Census Tract', 'Geo_TRACT'), ('Block Group', 'Geo_BLKGRP'), ('Consolidated City', 'Geo_CONCIT'), ('American Indian Area/Alaska Native Area/Hawaiian Home Land (Census)', 'Geo_AIANHH'), ('American Indian Area/Alaska Native Area/Hawaiian Home Land (FIPS)', 'Geo_AIANHHFP'), ('American Indian Trust Land/Hawaiian Home Land Indicator', 'Geo_AIHHTLI'), ('American Indian Tribal Subdivision (Census)', 'Geo_AITSCE'), ('American Indian Tribal Subdivision (FIPS)', 'Geo_AITS'), ('Alaska Native Regional Corporation (FIPS)', 'Geo_ANRC'), ('Metropolitan and Micropolitan Statistical Area', 'Geo_CBSA'), ('Combined Statistical Area', 'Geo_CSA'), ('Metropolitan Division', 'Geo_METDIV'), ('Metropolitan Area Central City', 'Geo_MACC'), ('Metropolitan/Micropolitan Indicator Flag', 'Geo_MEMI'), ('New England City and Town Combined Statistical Area', 'Geo_NECTA'), ('New England City and Town Area', 'Geo_CNECTA'), ('New England City and Town Area Division', 'Geo_NECTADIV'), ('Urban Area', 'Geo_UA'), ('Urban Area Central Place', 'Geo_UACP'), ('Current Congressional District ***', 'Geo_CDCURR'), ('State Legislative District Upper', 'Geo_SLDU'), ('State Legislative District Lower', 'Geo_SLDL'), ('Voting District', 'Geo_VTD'), ('ZIP Code Tabulation Area (3-digit)', 'Geo_ZCTA3'), ('ZIP Code Tabulation Area (5-digit)', 'Geo_ZCTA5'), ('Subbarrio (FIPS)', 'Geo_SUBMCD'), ('Urban/Rural', 'Geo_UR'), ('Principal City Indicator', 'Geo_PCI'), ('Traffic Analysis Zone', 'Geo_TAZ'), ('Urban Growth Area', 'Geo_UGA'), ('Public Use Microdata Area - 5% File', 'Geo_PUMA5'), ('Public Use Microdata Area - 1% File', 'Geo_PUMA1'), ('Tribal Tract', 'Geo_BTTR'), ('Tribal Block Group', 'Geo_BTBG'), ('Total Population:', 'SE_T013_001'), ('Total Population: White Alone', 'SE_T013_002'), ('Total Population: Black or African American Alone', 'SE_T013_003'), ('Total Population: American Indian and Alaska Native Alone', 'SE_T013_004'), ('Total Population: Asian Alone', 'SE_T013_005'), ('Total Population: Native Hawaiian and Other Pacific Islander Alone', 'SE_T013_006'), ('Total Population: Some Other Race Alone', 'SE_T013_007'), ('Total Population: Two or More Races', 'SE_T013_008'), ('Population 25 Years and Over: Less than High School', 'SE_T025_002'), ('Population 25 Years and Over: High School Graduate (Includes Equivalency)', 'SE_T025_003'), ('Population 25 Years and Over: Some College', 'SE_T025_004'), ("Population 25 Years and Over: Bachelor's Degree", 'SE_T025_005'), ("Population 25 Years and Over: Master's Degree", 'SE_T025_006'), ('Population 25 Years and Over: Professional School Degree', 'SE_T025_007'), ('Population 25 Years and Over: Doctorate Degree', 'SE_T025_008'), ('Population 3 Years and Over: Enrolled in School', 'SE_T028_002'), ('Population 3 Years and Over: Not Enrolled in School', 'SE_T028_003'), ('Civilian Population 16 to 19 Years: Not High School Graduate, Not Enrolled (Dropped Out)', 'SE_T030_002'), ('Civilian Population 16 to 19 Years: High School Graduate, or Enrolled (in School)', 'SE_T030_003'), ('Civilian Population in Labor Force 16 Years and Over:', 'SE_T037_001'), ('Civilian Population in Labor Force 16 Years and Over: Employed', 'SE_T037_002'), ('Civilian Population in Labor Force 16 Years and Over: Unemployed', 'SE_T037_003'), ('Families:', 'SE_T113_001'), ('Families: Income in Below Poverty Level', 'SE_T113_002'), ('Families: Income in Below Poverty Level: Married Couple Family: with Related Child Living  Bellow Poverty Level', 'SE_T113_003'), ('Families: Income in Below Poverty Level: Married Couple Family: No Related Children Under 18 Years', 'SE_T113_004'), ('Families: Income in Below Poverty Level: Male Householder, No Wife Present', 'SE_T113_005'), ('Families: Income in Below Poverty Level: Male Householder, No Wife Present: with Related Children Under 18 Years', 'SE_T113_006'), ('Families: Income in Below Poverty Level: Male Householder, No Wife Present: No Related Children Under 18 Years', 'SE_T113_007'), ('Families: Income in Below Poverty Level: Female Householder, No Husband Present', 'SE_T113_008'), ('Families: Income in Below Poverty Level: Female Householder, No Husband Present: with Related Children Under 18 Years', 'SE_T113_009'), ('Families: Income in Below Poverty Level: Female Householder, No Husband Present: No Related Children Under 18 Years', 'SE_T113_010'), ('Families: Income in at or Above Poverty Level', 'SE_T113_011'), ('% Families: Income in Below Poverty Level: Married Couple Family: with Related Child Living  Bellow Poverty Level', 'PCT_SE_T113_003'), ('% Families: Income in Below Poverty Level: Married Couple Family: No Related Children Under 18 Years', 'PCT_SE_T113_004'), ('% Families: Income in Below Poverty Level: Male Householder, No Wife Present', 'PCT_SE_T113_005'), ('% Families: Income in Below Poverty Level: Male Householder, No Wife Present: with Related Children Under 18 Years', 'PCT_SE_T113_006'), ('% Families: Income in Below Poverty Level: Male Householder, No Wife Present: No Related Children Under 18 Years', 'PCT_SE_T113_007'), ('% Families: Income in Below Poverty Level: Female Householder, No Husband Present', 'PCT_SE_T113_008'), ('% Families: Income in Below Poverty Level: Female Householder, No Husband Present: with Related Children Under 18 Years', 'PCT_SE_T113_009'), ('% Families: Income in Below Poverty Level: Female Householder, No Husband Present: No Related Children Under 18 Years', 'PCT_SE_T113_010'), ('Population Under 18 Years of Age for Whom Poverty Status Is Determined: Living in Poverty', 'SE_T114_002'), ('Population Under 18 Years of Age for Whom Poverty Status Is Determined: at or Above Poverty Level', 'SE_T114_003'), ('Total:', 'SE_T130_001'), ('Total: Same House 1 Year Ago', 'SE_T130_002'), ('Total: Moved Within Same County', 'SE_T130_003'), ('Total: Moved From Different County Within Same State', 'SE_T130_004'), ('Total: Moved From Different State', 'SE_T130_005'), ('Total: Moved From Abroad', 'SE_T130_006'), ('Total Population:', 'SE_T133_001'), ('Total Population: Native Born', 'SE_T133_002'), ('Total Population: Foreign Born', 'SE_T133_003'), ('Total Population: Foreign Born: Naturalized Citizen', 'SE_T133_004'), ('Total Population: Foreign Born: Not a Citizen', 'SE_T133_005')]

# Drop these variables from each dataset:
smallacs = smallacs.drop(smalldrops, axis=1)
fullacs = fullacs.drop(fulldrops, axis=1)

In [6]:
print(len(list(fullacs.columns)))
print(len(list(smallacs.columns)))

126
56

In [7]:
# See columns in full dataset than aren't in smaller data set:
set(fullacs.columns) - set(smallacs.columns)

{('% Employed Civilian Population 16 Years and Over: Agriculture, Forestry, Fishing and Hunting, and Mining',
  'PCT_SE_T049_002'),
 ('% Employed Civilian Population 16 Years and Over: Arts, Entertainment, and Recreation, and  Accommodation and Food Services',
  'PCT_SE_T049_012'),
 ('% Employed Civilian Population 16 Years and Over: Construction',
  'PCT_SE_T049_003'),
 ('% Employed Civilian Population 16 Years and Over: Educational Services, and Health Care and Social  Assistance',
  'PCT_SE_T049_011'),
 ('% Employed Civilian Population 16 Years and Over: Finance and Insurance, and Real Estate and Rental  and Leasing',
  'PCT_SE_T049_009'),
 ('% Employed Civilian Population 16 Years and Over: Information',
  'PCT_SE_T049_008'),
 ('% Employed Civilian Population 16 Years and Over: Manufacturing',
  'PCT_SE_T049_004'),
 ('% Employed Civilian Population 16 Years and Over: Other Services, Except Public Administration',
  'PCT_SE_T049_013'),
 ('% Employed Civilian Population 16 Years and Over: Professional, Scientific, and Management, and  Administrative and Waste Management Services',
  'PCT_SE_T049_010'),
 ('% Employed Civilian Population 16 Years and Over: Public Administration',
  'PCT_SE_T049_014'),
 ('% Employed Civilian Population 16 Years and Over: Retail Trade',
  'PCT_SE_T049_006'),
 ('% Employed Civilian Population 16 Years and Over: Transportation and Warehousing, and Utilities',
  'PCT_SE_T049_007'),
 ('% Employed Civilian Population 16 Years and Over: Unpaid Family Workers',
  'PCT_SE_T053_006'),
 ('% Employed Civilian Population 16 Years and Over: Wholesale Trade',
  'PCT_SE_T049_005'),
 ('% Foreign-Born Population: Africa', 'PCT_SE_T139_067'),
 ('% Foreign-Born Population: Americas', 'PCT_SE_T139_090'),
 ('% Foreign-Born Population: Asia', 'PCT_SE_T139_034'),
 ('% Foreign-Born Population: Europe', 'PCT_SE_T139_002'),
 ('% Foreign-Born Population: Oceania', 'PCT_SE_T139_085'),
 ('% Occupied Housing Units: Family Households', 'PCT_SE_T165_002'),
 ('% Occupied Housing Units: Family Households: Married-Couple Family',
  'PCT_SE_T165_003'),
 ('% Occupied Housing Units: No Related Children of the Householder Under 18',
  'PCT_SE_T167_008'),
 ('% Occupied Housing Units: Nonfamily Households', 'PCT_SE_T165_016'),
 ('% Occupied Housing Units: Nonfamily Households: Householder Living Alone',
  'PCT_SE_T165_017'),
 ('% Occupied Housing Units: With Related Children of the Householder Under 18',
  'PCT_SE_T167_002'),
 ('% Population 15 Years and Over: Divorced', 'PCT_SE_T022_006'),
 ('% Population 15 Years and Over: Never Married', 'PCT_SE_T022_002'),
 ('% Population 15 Years and Over: Now Married (Not Including Separated)',
  'PCT_SE_T022_003'),
 ('% Population 15 Years and Over: Separated', 'PCT_SE_T022_004'),
 ('% Population 15 Years and Over: Widowed', 'PCT_SE_T022_005'),
 ('% Population 3 Years and Over Enrolled in School: Private School',
  'PCT_SE_T029_007'),
 ('% Population 3 Years and Over Enrolled in School: Private School: 9-12',
  'PCT_SE_T029_010'),
 ('% Population 3 Years and Over Enrolled in School: Private School: College',
  'PCT_SE_T029_011'),
 ('% Population 3 Years and Over Enrolled in School: Private School: K-8',
  'PCT_SE_T029_009'),
 ('% Population 3 Years and Over Enrolled in School: Private School: Pre-School',
  'PCT_SE_T029_008'),
 ('% Population 3 Years and Over Enrolled in School: Public School',
  'PCT_SE_T029_002'),
 ('% Population 3 Years and Over Enrolled in School: Public School: 9-12',
  'PCT_SE_T029_005'),
 ('% Population 3 Years and Over Enrolled in School: Public School: College',
  'PCT_SE_T029_006'),
 ('% Population 3 Years and Over Enrolled in School: Public School: K-8',
  'PCT_SE_T029_004'),
 ('% Population 3 Years and Over Enrolled in School: Public School: Pre-School',
  'PCT_SE_T029_003'),
 ('% Renter-Occupied Housing Units: 10 to 29 Percent', 'PCT_SE_T103_003'),
 ('% Renter-Occupied Housing Units: 30 to 49 Percent', 'PCT_SE_T103_004'),
 ('% Renter-Occupied Housing Units: 50 Percent or More', 'PCT_SE_T103_005'),
 ('% Renter-Occupied Housing Units: Less than 10 Percent', 'PCT_SE_T103_002'),
 ('% Renter-Occupied Housing Units: Not Computed', 'PCT_SE_T103_006'),
 ('% Total Population: 18 to 34 Years', 'PCT_SE_T009_003'),
 ('% Total Population: 35 to 64 Years', 'PCT_SE_T009_004'),
 ('% Total Population: 65 and Over', 'PCT_SE_T009_005'),
 ('% Total Population: Under 18 Years', 'PCT_SE_T009_002'),
 ('% Total: No Health Insurance Coverage', 'PCT_SE_T145_002'),
 ('% Total: with Health Insurance Coverage', 'PCT_SE_T145_003'),
 ('% Total: with Health Insurance Coverage: Private Health Insurance',
  'PCT_SE_T145_005'),
 ('% Total: with Health Insurance Coverage: Public Health Coverage',
  'PCT_SE_T145_004'),
 ('% White Alone, Not Hispanic or Latino 16 Years Old  in&nbsp; Civilian Labor Force: Employed',
  'PCT_SE_T048_002'),
 ('% White Alone, Not Hispanic or Latino 16 Years Old  in&nbsp; Civilian Labor Force: Unemployed',
  'PCT_SE_T048_003'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): American Indian and Alaska Native Alone  Householder',
  'SE_T058_004'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): Asian Alone',
  'SE_T058_005'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): Black or African American Alone Householder',
  'SE_T058_003'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): Hispanic or Latino Householder',
  'SE_T058_009'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): Native Hawaiian and Other Pacific Islander Alone  Householder',
  'SE_T058_006'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): Some Other Race Alone Householder',
  'SE_T058_007'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): Two or More Races Householder',
  'SE_T058_008'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): White Alone Householder',
  'SE_T058_002'),
 ('Median Household Income (In 2016 Inflation Adjusted Dollars): White Alone Householder, Not Hispanic or Latino',
  'SE_T058_010'),
 ('Median Value', 'SE_T101_001'),
 ('Median Year Structure Built', 'SE_T098_001'),
 ('Occupied Housing Units', 'SE_T165_001'),
 ('Per Capita Income (In 2016 Inflation Adjusted Dollars)', 'SE_T083_001'),
 ('Population 15 Years and Over:', 'SE_T022_001'),
 ('Total:', 'SE_T145_001')}

In [8]:
#turn the concatenated files into CSVs
fullacs.to_csv("ACS_2016_sd-merged_FULL.csv", index = False)
smallacs.to_csv("ACS_2016_sd-merged_SMALL.csv", index = False)