# Calculate the open and close year for each school

In [2]:
#"final.csv" is a file merged by files that contain all the public schools in U.S. from 1998 - 2016
#I'm trying to get the openYear and closeYear for each school and make a new big file.
import csv
import pandas
from os import listdir
import numpy as np
from operator import eq

In [60]:
# Read the source file
df = pandas.read_csv("final.csv")

/Users/shiji/anaconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (0,2,3,4,6,7,9,11,12,13,14,15,16,20,21,22,23,24,28,29,31,32,33,34,35,37,39,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,67,269,270,271,272,352,353,354,355,356,357,358,359,361,362,363,365,366,368,369,371,372,374,375,377,378,380,381,383,384,386,387,389,390,392,393,395,396,398,399,401,402,403,404,406,408,409,411,413,414,416,418,419,421,422,423,425) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [61]:
#make two series to store the newly created columns
length = df.shape[0]

#initialize the two columns
YEAR_OPENED = ["NA" for i in range(length)]
YEAR_CLOSED = [None for i in range(length)]

#the names of all the status col
status = df[['STATUS98', 'STATUS99', 'STATUS00', 'STATUS01', 'STATUS02', 'STATUS03',\
             'STATUS04', 'STATUS05', 'STATUS06', 'STATUS07', 'STATUS08', 'STATUS09',\
             'STATUS10', 'STATUS11', 'STATUS12', 'STATUS13', 'SY_STATUS', 'SY_STATUS15', 'SY_STATUS16']]

#status.to_csv("status.csv", index = False)

#dictionary of (status col : corresponding year)
cols = {'STATUS98' : '1998', 'STATUS99' : '1999', 'STATUS00' : '2000', 'STATUS01' : '2001',\
        'STATUS02' : '2002', 'STATUS03' : '2003', 'STATUS04' : '2004', 'STATUS05' : '2005',\
        'STATUS06' : '2006', 'STATUS07' : '2007', 'STATUS08' : '2008', 'STATUS09' : '2009',\
        'STATUS10' : '2010', 'STATUS11' : '2011', 'STATUS12' : '2012', 'STATUS13' : '2013',\
        'SY_STATUS' : '2014', 'SY_STATUS15' : '2015', 'SY_STATUS16' : '2016'}

#status as a list
b = ['STATUS98', 'STATUS99', 'STATUS00', 'STATUS01', 'STATUS02', 'STATUS03', 'STATUS04',\
     'STATUS05', 'STATUS06', 'STATUS07', 'STATUS08', 'STATUS09', 'STATUS10', 'STATUS11',\
     'STATUS12', 'STATUS13', 'SY_STATUS', 'SY_STATUS15', 'SY_STATUS16']

In [62]:
#check all the years before the year we are looking. 
#if there is a number(except for -1, 5, 6, 7) appears, return False.
#else return True.

def checkPrevYears(statusArr, currYear):
    allNeg1 = True
    for prevStat in statusArr[:b.index(currYear)]:
        if prevStat != -1 and prevStat != 5 and prevStat != 6 and prevStat != 7:
            allNeg1 = False
    return allNeg1

In [63]:
#check all the years after the year we are looking.
#if there is a 2 or 6, return True. else return False

def checkAfterYears(statusArr, currYear):
    is2or6 = False
    for afterStat in statusArr[b.index(currYear):]:
        if afterStat == 2 or afterStat == 6:
            is2or6 = True
    return is2or6

In [64]:
def checkAfter6(statusArr, currYear):
    anythingAfter = False
    for afterStat in statusArr[b.index(currYear):]:
        if afterStat != None:
            anythingAfter = True
    return anythingAfter

In [65]:
#check all the years for a certain school.
#if there exist a 2 or 6, return True; else return False;

def checkAllYears(statusArr):
    is2or6 = False
    for stat in statusArr:
        if stat == 2 or stat == 6:
            is2or6 = True
    return is2or6

In [66]:
#main algorithm for a certain interval, inclusive.
#go through each row
YEAR_OPENED = ["NA" for i in range(length)]
YEAR_CLOSED = ["NA" for i in range(length)]
for index, row in status.iterrows():
    #only calculate for the input interval
    if index >= 0 and index < df.shape[0]:
        statusArr = [] #a list used to store all status for a year

        #putting things in statusArr
        for i in range(len(cols)):
            if np.isnan(row[b[i]]):
                statusArr += [-1] #-1 if there is a nan in certain status
            else:
                statusArr += [int(row[b[i]])]

        #main logic         
        for col in cols:    
            stat = -1
            if(not np.isnan(row[col])):
                stat = int(row[col])

            #if there is a 2, the close_year should be this year
            if(stat == 2):
                YEAR_CLOSED[index] = cols.get(col)

            #if 1,3 or 8, checkPreYears, if no previous status, open_year should be this year
            if(stat == 1 or stat == 3 or stat == 8):
                if checkPrevYears(statusArr, col):
                    YEAR_OPENED[index] = cols.get(col)

            #if 4, checkPrevYears, if no previous status, open_year should be the year before this year        
            if(stat == 4):
                if checkPrevYears(statusArr, col):
                    YEAR_OPENED[index] = cols.get(b[(b.index(col) - 1)])

            #if 8, checkLaterYear, if nothing after, year_closed should be this year
            if(stat == 8):
                if not checkAfterYears(statusArr, col):
                    YEAR_CLOSED[index] = 'NA'
            
            #if nothing after 6, year_closed should be this year
            if(stat == 6):
                if not checkAfter6(statusArr, col):
                    YEAR_CLOSED[index] = cols.get(col)

        #if never 2 or 6, year_closed is 'NA'
        if not checkAllYears(statusArr):
            YEAR_CLOSED[index] = 'NA'

In [67]:
# This is used for testing only
for index in range(0, df.shape[0]):
    if YEAR_CLOSED[index] == None or YEAR_OPENED[index] == None:
        print(index,"|", YEAR_OPENED[index],"|", YEAR_CLOSED[index])

In [68]:
# Create two dataframe for the mappings
label = ['YEAR_OPENED']
label2 = ['YEAR_CLOSED']
dfOpened = pandas.DataFrame(YEAR_OPENED, columns = label)
dfClosed = pandas.DataFrame(YEAR_CLOSED, columns = label2)

In [69]:
print(dfOpened)

       YEAR_OPENED
0             1998
1             1998
2             2003
3             2003
4             1998
5             1998
6             2006
7             1998
8             1998
9             1998
10            1998
11            1998
12            2009
13            1998
14            1998
15            1998
16            1998
17            1998
18            1998
19            1998
20            1998
21            2016
22            2016
23            1999
24            2001
25            2003
26            1998
27            1998
28            2012
29            1998
...            ...
136774        2016
136775        2016
136776        2016
136777        2016
136778        2016
136779        2016
136780        2016
136781        2016
136782        2016
136783        2016
136784        2016
136785        2016
136786        2016
136787        2016
136788        2016
136789        2016
136790        2016
136791        2016
136792        2016
136793        2016
136794        2016
136795        2016
136796        2016
136797        2016
136798        2016
136799        2016
136800        2016
136801        2016
136802        2016
136803        2016

[136804 rows x 1 columns]

In [70]:
print(dfClosed)

       YEAR_CLOSED
0               NA
1             2014
2               NA
3               NA
4               NA
5               NA
6               NA
7               NA
8               NA
9               NA
10              NA
11              NA
12              NA
13              NA
14              NA
15              NA
16              NA
17              NA
18              NA
19              NA
20              NA
21              NA
22              NA
23              NA
24              NA
25              NA
26              NA
27              NA
28              NA
29              NA
...            ...
136774          NA
136775          NA
136776          NA
136777          NA
136778          NA
136779          NA
136780          NA
136781          NA
136782          NA
136783          NA
136784          NA
136785          NA
136786          NA
136787          NA
136788          NA
136789          NA
136790          NA
136791          NA
136792          NA
136793          NA
136794          NA
136795          NA
136796          NA
136797          NA
136798          NA
136799          NA
136800          NA
136801          NA
136802          NA
136803          NA

[136804 rows x 1 columns]

In [71]:
print(df)

         SURVYEAR  FIPST STABR STATENAME                          SEANAME  \
0       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
1       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
2       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
3       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
4       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
5       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
6       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
7       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
8       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
9       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
10      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
11      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
12      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
13      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
14      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
15      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
16      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
17      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
18      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
19      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
20      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
21      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
22      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
23      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
24      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
25      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
26      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
27      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
28      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
29      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
...           ...    ...   ...       ...                              ...
136774        NaN    NaN   NaN       NaN                              NaN
136775        NaN    NaN   NaN       NaN                              NaN
136776        NaN    NaN   NaN       NaN                              NaN
136777        NaN    NaN   NaN       NaN                              NaN
136778        NaN    NaN   NaN       NaN                              NaN
136779        NaN    NaN   NaN       NaN                              NaN
136780        NaN    NaN   NaN       NaN                              NaN
136781        NaN    NaN   NaN       NaN                              NaN
136782        NaN    NaN   NaN       NaN                              NaN
136783        NaN    NaN   NaN       NaN                              NaN
136784        NaN    NaN   NaN       NaN                              NaN
136785        NaN    NaN   NaN       NaN                              NaN
136786        NaN    NaN   NaN       NaN                              NaN
136787        NaN    NaN   NaN       NaN                              NaN
136788        NaN    NaN   NaN       NaN                              NaN
136789        NaN    NaN   NaN       NaN                              NaN
136790        NaN    NaN   NaN       NaN                              NaN
136791        NaN    NaN   NaN       NaN                              NaN
136792        NaN    NaN   NaN       NaN                              NaN
136793        NaN    NaN   NaN       NaN                              NaN
136794        NaN    NaN   NaN       NaN                              NaN
136795        NaN    NaN   NaN       NaN                              NaN
136796        NaN    NaN   NaN       NaN                              NaN
136797        NaN    NaN   NaN       NaN                              NaN
136798        NaN    NaN   NaN       NaN                              NaN
136799        NaN    NaN   NaN       NaN                              NaN
136800        NaN    NaN   NaN       NaN                              NaN
136801        NaN    NaN   NaN       NaN                              NaN
136802        NaN    NaN   NaN       NaN                              NaN
136803        NaN    NaN   NaN       NaN                              NaN

           LEAID ST_LEAID                LEA_NAME   SCHID ST_SCHID  \
0       100002.0      210  Alabama Youth Services   277.0       20
1       100002.0      210  Alabama Youth Services  1402.0       25
2       100002.0      210  Alabama Youth Services  1667.0       50
3       100002.0      210  Alabama Youth Services  1670.0       60
4       100002.0      210  Alabama Youth Services  1705.0       30
5       100002.0      210  Alabama Youth Services  1706.0       40
6       100002.0      210  Alabama Youth Services  1876.0        1
7       100005.0      101        Albertville City   870.0       10
8       100005.0      101        Albertville City   871.0       20
9       100005.0      101        Albertville City   879.0      110
10      100005.0      101        Albertville City   889.0      200
11      100005.0      101        Albertville City  1616.0       35
12      100005.0      101        Albertville City  2150.0        5
13      100006.0       48         Marshall County   193.0      143
14      100006.0       48         Marshall County   872.0       30
15      100006.0       48         Marshall County   876.0       70
16      100006.0       48         Marshall County   877.0       90
17      100006.0       48         Marshall County   878.0      100
18      100006.0       48         Marshall County   880.0      120
19      100006.0       48         Marshall County   883.0      140
20      100006.0       48         Marshall County   887.0      180
21      100006.0       48         Marshall County   986.0      150
22      100006.0       48         Marshall County   987.0      160
23      100006.0       48         Marshall County  1413.0       95
24      100006.0       48         Marshall County  1434.0       40
25      100006.0       48         Marshall County  1585.0       42
26      100006.0       48         Marshall County  1685.0      145
27      100006.0       48         Marshall County  1812.0      105
28      100006.0       48         Marshall County  2209.0       35
29      100007.0      158             Hoover City    91.0      820
...          ...      ...                     ...     ...      ...
136774       NaN      NaN                     NaN     NaN      NaN
136775       NaN      NaN                     NaN     NaN      NaN
136776       NaN      NaN                     NaN     NaN      NaN
136777       NaN      NaN                     NaN     NaN      NaN
136778       NaN      NaN                     NaN     NaN      NaN
136779       NaN      NaN                     NaN     NaN      NaN
136780       NaN      NaN                     NaN     NaN      NaN
136781       NaN      NaN                     NaN     NaN      NaN
136782       NaN      NaN                     NaN     NaN      NaN
136783       NaN      NaN                     NaN     NaN      NaN
136784       NaN      NaN                     NaN     NaN      NaN
136785       NaN      NaN                     NaN     NaN      NaN
136786       NaN      NaN                     NaN     NaN      NaN
136787       NaN      NaN                     NaN     NaN      NaN
136788       NaN      NaN                     NaN     NaN      NaN
136789       NaN      NaN                     NaN     NaN      NaN
136790       NaN      NaN                     NaN     NaN      NaN
136791       NaN      NaN                     NaN     NaN      NaN
136792       NaN      NaN                     NaN     NaN      NaN
136793       NaN      NaN                     NaN     NaN      NaN
136794       NaN      NaN                     NaN     NaN      NaN
136795       NaN      NaN                     NaN     NaN      NaN
136796       NaN      NaN                     NaN     NaN      NaN
136797       NaN      NaN                     NaN     NaN      NaN
136798       NaN      NaN                     NaN     NaN      NaN
136799       NaN      NaN                     NaN     NaN      NaN
136800       NaN      NaN                     NaN     NaN      NaN
136801       NaN      NaN                     NaN     NaN      NaN
136802       NaN      NaN                     NaN     NaN      NaN
136803       NaN      NaN                     NaN     NaN      NaN

             ...        RECONSTY10_y.1 RECONSTF10_y.1  \
0            ...                     N            2.0
1            ...                     N            2.0
2            ...                     N            2.0
3            ...                     N            2.0
4            ...                     N            2.0
5            ...                     N            2.0
6            ...                     N            2.0
7            ...                     N            2.0
8            ...                     N            2.0
9            ...                     N            2.0
10           ...                     N            2.0
11           ...                     N            2.0
12           ...                     N            2.0
13           ...                     N            2.0
14           ...                     N            2.0
15           ...                     N            2.0
16           ...                     N            2.0
17           ...                     N            2.0
18           ...                     N            2.0
19           ...                     N            2.0
20           ...                     N            2.0
21           ...                     N            2.0
22           ...                     N            2.0
23           ...                     N            2.0
24           ...                     N            2.0
25           ...                     N            2.0
26           ...                     N            2.0
27           ...                     N            2.0
28           ...                     N            2.0
29           ...                     N            2.0
...          ...                   ...            ...
136774       ...                   NaN            NaN
136775       ...                   NaN            NaN
136776       ...                   NaN            NaN
136777       ...                   NaN            NaN
136778       ...                   NaN            NaN
136779       ...                   NaN            NaN
136780       ...                   NaN            NaN
136781       ...                   NaN            NaN
136782       ...                   NaN            NaN
136783       ...                   NaN            NaN
136784       ...                   NaN            NaN
136785       ...                   NaN            NaN
136786       ...                   NaN            NaN
136787       ...                   NaN            NaN
136788       ...                   NaN            NaN
136789       ...                   NaN            NaN
136790       ...                   NaN            NaN
136791       ...                   NaN            NaN
136792       ...                   NaN            NaN
136793       ...                   NaN            NaN
136794       ...                   NaN            NaN
136795       ...                   NaN            NaN
136796       ...                   NaN            NaN
136797       ...                   NaN            NaN
136798       ...                   NaN            NaN
136799       ...                   NaN            NaN
136800       ...                   NaN            NaN
136801       ...                   NaN            NaN
136802       ...                   NaN            NaN
136803       ...                   NaN            NaN

                                SCHNAM15 CHARTER_TEXT15 SY_STATUS15  \
0       Sequoyah Sch - Chalkville Campus             No         1.0
1                                    NaN            NaN         NaN
2                                  Camps             No         1.0
3                                Det Ctr             No         1.0
4          Wallace Sch - Mt Meigs Campus             No         1.0
5              McNeel Sch - Vacca Campus             No         1.0
6                 Alabama Youth Services             No         1.0
7                  Ala Avenue Middle Sch             No         1.0
8                   Albertville High Sch             No         1.0
9                         Evans Elem Sch             No         1.0
10                  Albertville Elem Sch             No         1.0
11           Big Spring Lake Kinderg Sch             No         1.0
12               Albertville Primary Sch             No         1.0
13          Kate Duncan Smith DAR Middle             No         1.0
14                            Asbury Sch             No         1.0
15                Claysville Jr High Sch             No         1.0
16                      Douglas Elem Sch             No         1.0
17                      Douglas High Sch             No         1.0
18                       Grassy Elem Sch             No         1.0
19             Kate D Smith DAR High Sch             No         1.0
20                  Union Grove Elem Sch             No         1.0
21                      Marshall Alt Sch             No         1.0
22                     Marshall Tech Sch             No         1.0
23               Robert D Sloman Primary             No         1.0
24                Brindlee Mt Middle Sch             No         1.0
25                  Brindlee Mt High Sch             No         1.0
26             Kate D Smith DAR Elem Sch             No         1.0
27                    Douglas Middle Sch             No         1.0
28                       Asbury Elem Sch             No         1.0
29              Trace Crossings Elem Sch             No         1.0
...                                  ...            ...         ...
136774                               NaN            NaN         NaN
136775                               NaN            NaN         NaN
136776                               NaN            NaN         NaN
136777                               NaN            NaN         NaN
136778                               NaN            NaN         NaN
136779                               NaN            NaN         NaN
136780                               NaN            NaN         NaN
136781                               NaN            NaN         NaN
136782                               NaN            NaN         NaN
136783                               NaN            NaN         NaN
136784                               NaN            NaN         NaN
136785                               NaN            NaN         NaN
136786                               NaN            NaN         NaN
136787                               NaN            NaN         NaN
136788                               NaN            NaN         NaN
136789                               NaN            NaN         NaN
136790                               NaN            NaN         NaN
136791                               NaN            NaN         NaN
136792                               NaN            NaN         NaN
136793                               NaN            NaN         NaN
136794                               NaN            NaN         NaN
136795                               NaN            NaN         NaN
136796                               NaN            NaN         NaN
136797                               NaN            NaN         NaN
136798                               NaN            NaN         NaN
136799                               NaN            NaN         NaN
136800                               NaN            NaN         NaN
136801                               NaN            NaN         NaN
136802                               NaN            NaN         NaN
136803                               NaN            NaN         NaN

       RECON_STATUS15                                SCHNAM16  CHARTER_TEXT16  \
0                  No        Sequoyah Sch - Chalkville Campus              No
1                 NaN                                     NaN             NaN
2                  No                                   Camps              No
3                  No                                 Det Ctr              No
4                  No           Wallace Sch - Mt Meigs Campus              No
5                  No               McNeel Sch - Vacca Campus              No
6                  No                  Alabama Youth Services              No
7                  No                   Ala Avenue Middle Sch              No
8                  No                    Albertville High Sch              No
9                  No                          Evans Elem Sch              No
10                 No                    Albertville Elem Sch              No
11                 No             Big Spring Lake Kinderg Sch              No
12                 No                 Albertville Primary Sch              No
13                 No            Kate Duncan Smith DAR Middle              No
14                 No                              Asbury Sch              No
15                 No                  Claysville Jr High Sch              No
16                 No                        Douglas Elem Sch              No
17                 No                        Douglas High Sch              No
18                 No                         Grassy Elem Sch              No
19                 No               Kate D Smith DAR High Sch              No
20                 No                    Union Grove Elem Sch              No
21                 No                        Marshall Alt Sch              No
22                 No                       Marshall Tech Sch              No
23                 No                 Robert D Sloman Primary              No
24                 No                  Brindlee Mt Middle Sch              No
25                 No                    Brindlee Mt High Sch              No
26                 No               Kate D Smith DAR Elem Sch              No
27                 No                      Douglas Middle Sch              No
28                 No                         Asbury Elem Sch              No
29                 No                Trace Crossings Elem Sch              No
...               ...                                     ...             ...
136774            NaN  Charles Cotesworth Pinckney Elementary  Not applicable
136775            NaN       Robert E. Galer Elementary School  Not applicable
136776            NaN      Charles F Bolden Elementary/Middle  Not applicable
136777            NaN                  Johnson Primary School  Not applicable
136778            NaN                Bitz Intermediate School  Not applicable
136779            NaN                Gordon Elementary School  Not applicable
136780            NaN                Devers Elementary School  Not applicable
136781            NaN                 Albritton Middle School  Not applicable
136782            NaN                     Lejeune High School  Not applicable
136783            NaN               Delalio Elementary School  Not applicable
136784            NaN        Tarawa Terrace Elementary School  Not applicable
136785            NaN            West Point Elementary School  Not applicable
136786            NaN                West Point Middle School  Not applicable
136787            NaN              Antilles Elementary School  Not applicable
136788            NaN                  Antilles Middle School  Not applicable

In [72]:
# Concatenating the two mapping dataframe to our source
# Here we use concat instead of merge because the sequence of NCESSCH is preserved
result = pandas.concat([df, dfOpened, dfClosed], axis=1)

In [73]:
print(result)

         SURVYEAR  FIPST STABR STATENAME                          SEANAME  \
0       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
1       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
2       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
3       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
4       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
5       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
6       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
7       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
8       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
9       2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
10      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
11      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
12      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
13      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
14      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
15      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
16      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
17      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
18      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
19      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
20      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
21      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
22      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
23      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
24      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
25      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
26      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
27      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
28      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
29      2014-2015    1.0    AL   ALABAMA  Alabama Department Of Education
...           ...    ...   ...       ...                              ...
136774        NaN    NaN   NaN       NaN                              NaN
136775        NaN    NaN   NaN       NaN                              NaN
136776        NaN    NaN   NaN       NaN                              NaN
136777        NaN    NaN   NaN       NaN                              NaN
136778        NaN    NaN   NaN       NaN                              NaN
136779        NaN    NaN   NaN       NaN                              NaN
136780        NaN    NaN   NaN       NaN                              NaN
136781        NaN    NaN   NaN       NaN                              NaN
136782        NaN    NaN   NaN       NaN                              NaN
136783        NaN    NaN   NaN       NaN                              NaN
136784        NaN    NaN   NaN       NaN                              NaN
136785        NaN    NaN   NaN       NaN                              NaN
136786        NaN    NaN   NaN       NaN                              NaN
136787        NaN    NaN   NaN       NaN                              NaN
136788        NaN    NaN   NaN       NaN                              NaN
136789        NaN    NaN   NaN       NaN                              NaN
136790        NaN    NaN   NaN       NaN                              NaN
136791        NaN    NaN   NaN       NaN                              NaN
136792        NaN    NaN   NaN       NaN                              NaN
136793        NaN    NaN   NaN       NaN                              NaN
136794        NaN    NaN   NaN       NaN                              NaN
136795        NaN    NaN   NaN       NaN                              NaN
136796        NaN    NaN   NaN       NaN                              NaN
136797        NaN    NaN   NaN       NaN                              NaN
136798        NaN    NaN   NaN       NaN                              NaN
136799        NaN    NaN   NaN       NaN                              NaN
136800        NaN    NaN   NaN       NaN                              NaN
136801        NaN    NaN   NaN       NaN                              NaN
136802        NaN    NaN   NaN       NaN                              NaN
136803        NaN    NaN   NaN       NaN                              NaN

           LEAID ST_LEAID                LEA_NAME   SCHID ST_SCHID  \
0       100002.0      210  Alabama Youth Services   277.0       20
1       100002.0      210  Alabama Youth Services  1402.0       25
2       100002.0      210  Alabama Youth Services  1667.0       50
3       100002.0      210  Alabama Youth Services  1670.0       60
4       100002.0      210  Alabama Youth Services  1705.0       30
5       100002.0      210  Alabama Youth Services  1706.0       40
6       100002.0      210  Alabama Youth Services  1876.0        1
7       100005.0      101        Albertville City   870.0       10
8       100005.0      101        Albertville City   871.0       20
9       100005.0      101        Albertville City   879.0      110
10      100005.0      101        Albertville City   889.0      200
11      100005.0      101        Albertville City  1616.0       35
12      100005.0      101        Albertville City  2150.0        5
13      100006.0       48         Marshall County   193.0      143
14      100006.0       48         Marshall County   872.0       30
15      100006.0       48         Marshall County   876.0       70
16      100006.0       48         Marshall County   877.0       90
17      100006.0       48         Marshall County   878.0      100
18      100006.0       48         Marshall County   880.0      120
19      100006.0       48         Marshall County   883.0      140
20      100006.0       48         Marshall County   887.0      180
21      100006.0       48         Marshall County   986.0      150
22      100006.0       48         Marshall County   987.0      160
23      100006.0       48         Marshall County  1413.0       95
24      100006.0       48         Marshall County  1434.0       40
25      100006.0       48         Marshall County  1585.0       42
26      100006.0       48         Marshall County  1685.0      145
27      100006.0       48         Marshall County  1812.0      105
28      100006.0       48         Marshall County  2209.0       35
29      100007.0      158             Hoover City    91.0      820
...          ...      ...                     ...     ...      ...
136774       NaN      NaN                     NaN     NaN      NaN
136775       NaN      NaN                     NaN     NaN      NaN
136776       NaN      NaN                     NaN     NaN      NaN
136777       NaN      NaN                     NaN     NaN      NaN
136778       NaN      NaN                     NaN     NaN      NaN
136779       NaN      NaN                     NaN     NaN      NaN
136780       NaN      NaN                     NaN     NaN      NaN
136781       NaN      NaN                     NaN     NaN      NaN
136782       NaN      NaN                     NaN     NaN      NaN
136783       NaN      NaN                     NaN     NaN      NaN
136784       NaN      NaN                     NaN     NaN      NaN
136785       NaN      NaN                     NaN     NaN      NaN
136786       NaN      NaN                     NaN     NaN      NaN
136787       NaN      NaN                     NaN     NaN      NaN
136788       NaN      NaN                     NaN     NaN      NaN
136789       NaN      NaN                     NaN     NaN      NaN
136790       NaN      NaN                     NaN     NaN      NaN
136791       NaN      NaN                     NaN     NaN      NaN
136792       NaN      NaN                     NaN     NaN      NaN
136793       NaN      NaN                     NaN     NaN      NaN
136794       NaN      NaN                     NaN     NaN      NaN
136795       NaN      NaN                     NaN     NaN      NaN
136796       NaN      NaN                     NaN     NaN      NaN
136797       NaN      NaN                     NaN     NaN      NaN
136798       NaN      NaN                     NaN     NaN      NaN
136799       NaN      NaN                     NaN     NaN      NaN
136800       NaN      NaN                     NaN     NaN      NaN
136801       NaN      NaN                     NaN     NaN      NaN
136802       NaN      NaN                     NaN     NaN      NaN
136803       NaN      NaN                     NaN     NaN      NaN

           ...                               SCHNAM15 CHARTER_TEXT15  \
0          ...       Sequoyah Sch - Chalkville Campus             No
1          ...                                    NaN            NaN
2          ...                                  Camps             No
3          ...                                Det Ctr             No
4          ...          Wallace Sch - Mt Meigs Campus             No
5          ...              McNeel Sch - Vacca Campus             No
6          ...                 Alabama Youth Services             No
7          ...                  Ala Avenue Middle Sch             No
8          ...                   Albertville High Sch             No
9          ...                         Evans Elem Sch             No
10         ...                   Albertville Elem Sch             No
11         ...            Big Spring Lake Kinderg Sch             No
12         ...                Albertville Primary Sch             No
13         ...           Kate Duncan Smith DAR Middle             No
14         ...                             Asbury Sch             No
15         ...                 Claysville Jr High Sch             No
16         ...                       Douglas Elem Sch             No
17         ...                       Douglas High Sch             No
18         ...                        Grassy Elem Sch             No
19         ...              Kate D Smith DAR High Sch             No
20         ...                   Union Grove Elem Sch             No
21         ...                       Marshall Alt Sch             No
22         ...                      Marshall Tech Sch             No
23         ...                Robert D Sloman Primary             No
24         ...                 Brindlee Mt Middle Sch             No
25         ...                   Brindlee Mt High Sch             No
26         ...              Kate D Smith DAR Elem Sch             No
27         ...                     Douglas Middle Sch             No
28         ...                        Asbury Elem Sch             No
29         ...               Trace Crossings Elem Sch             No
...        ...                                    ...            ...
136774     ...                                    NaN            NaN
136775     ...                                    NaN            NaN
136776     ...                                    NaN            NaN
136777     ...                                    NaN            NaN
136778     ...                                    NaN            NaN
136779     ...                                    NaN            NaN
136780     ...                                    NaN            NaN
136781     ...                                    NaN            NaN
136782     ...                                    NaN            NaN
136783     ...                                    NaN            NaN
136784     ...                                    NaN            NaN
136785     ...                                    NaN            NaN
136786     ...                                    NaN            NaN
136787     ...                                    NaN            NaN
136788     ...                                    NaN            NaN
136789     ...                                    NaN            NaN
136790     ...                                    NaN            NaN
136791     ...                                    NaN            NaN
136792     ...                                    NaN            NaN
136793     ...                                    NaN            NaN
136794     ...                                    NaN            NaN
136795     ...                                    NaN            NaN
136796     ...                                    NaN            NaN
136797     ...                                    NaN            NaN
136798     ...                                    NaN            NaN
136799     ...                                    NaN            NaN
136800     ...                                    NaN            NaN
136801     ...                                    NaN            NaN
136802     ...                                    NaN            NaN
136803     ...                                    NaN            NaN

       SY_STATUS15 RECON_STATUS15                                SCHNAM16  \
0              1.0             No        Sequoyah Sch - Chalkville Campus
1              NaN            NaN                                     NaN
2              1.0             No                                   Camps
3              1.0             No                                 Det Ctr
4              1.0             No           Wallace Sch - Mt Meigs Campus
5              1.0             No               McNeel Sch - Vacca Campus
6              1.0             No                  Alabama Youth Services
7              1.0             No                   Ala Avenue Middle Sch
8              1.0             No                    Albertville High Sch
9              1.0             No                          Evans Elem Sch
10             1.0             No                    Albertville Elem Sch
11             1.0             No             Big Spring Lake Kinderg Sch
12             1.0             No                 Albertville Primary Sch
13             1.0             No            Kate Duncan Smith DAR Middle
14             1.0             No                              Asbury Sch
15             1.0             No                  Claysville Jr High Sch
16             1.0             No                        Douglas Elem Sch
17             1.0             No                        Douglas High Sch
18             1.0             No                         Grassy Elem Sch
19             1.0             No               Kate D Smith DAR High Sch
20             1.0             No                    Union Grove Elem Sch
21             1.0             No                        Marshall Alt Sch
22             1.0             No                       Marshall Tech Sch
23             1.0             No                 Robert D Sloman Primary
24             1.0             No                  Brindlee Mt Middle Sch
25             1.0             No                    Brindlee Mt High Sch
26             1.0             No               Kate D Smith DAR Elem Sch
27             1.0             No                      Douglas Middle Sch
28             1.0             No                         Asbury Elem Sch
29             1.0             No                Trace Crossings Elem Sch
...            ...            ...                                     ...
136774         NaN            NaN  Charles Cotesworth Pinckney Elementary
136775         NaN            NaN       Robert E. Galer Elementary School
136776         NaN            NaN      Charles F Bolden Elementary/Middle
136777         NaN            NaN                  Johnson Primary School
136778         NaN            NaN                Bitz Intermediate School
136779         NaN            NaN                Gordon Elementary School
136780         NaN            NaN                Devers Elementary School
136781         NaN            NaN                 Albritton Middle School
136782         NaN            NaN                     Lejeune High School
136783         NaN            NaN               Delalio Elementary School
136784         NaN            NaN        Tarawa Terrace Elementary School
136785         NaN            NaN            West Point Elementary School
136786         NaN            NaN                West Point Middle School
136787         NaN            NaN              Antilles Elementary School
136788         NaN            NaN                  Antilles Middle School
136789         NaN            NaN                    Antilles High School
136790         NaN            NaN                            Ramey School
136791         NaN            NaN                         Dahlgren School
136792         NaN            NaN             Quantico Middle/High School
136793         NaN            NaN       WT Sampson Elementary/High School
136794         NaN            NaN                  Shughart Middle School
136795         NaN            NaN                Heroes Elementary School
136796         NaN            NaN              Shughart Elementary School
136797         NaN            NaN               DoDEA Virtual High School
136798         NaN            NaN            Crossroads Elementary School
136799         NaN            NaN         Kimberly Hampton Primary School
136800         NaN            NaN                Bowley Elementary School
136801         NaN            NaN               Irwin Intermediate School
136802         NaN            NaN                  Brewster Middle School
136803         NaN            NaN             J.P. TORRES SUCCESS ACADEMY

        CHARTER_TEXT16 SY_STATUS16  RECON_STATUS16  YEAR_OPENED  YEAR_CLOSED
0                   No         1.0              No         1998           NA
1                  NaN         NaN             NaN         1998         2014
2                   No         1.0              No         2003           NA
3                   No         1.0              No         2003           NA
4                   No         1.0              No         1998           NA
5                   No         1.0              No         1998           NA
6                   No         1.0              No         2006           NA
7                   No         1.0              No         1998           NA
8                   No         1.0              No         1998           NA
9                   No         1.0              No         1998           NA
10                  No         1.0              No         1998           NA
11                  No         1.0              No         1998           NA
12                  No         1.0              No         2009           NA
13                  No         1.0              No         1998           NA
14                  No         1.0              No         1998           NA
15                  No         1.0              No         1998           NA
16                  No         1.0              No         1998           NA
17                  No         1.0              No         1998           NA
18                  No         1.0              No         1998           NA
19                  No         1.0              No         1998           NA
20                  No         1.0              No         1998           NA
21                  No         1.0              No         2016           NA
22                  No         1.0              No         2016           NA
23                  No         1.0              No         1999           NA
24                  No         1.0              No         2001           NA
25                  No         1.0              No         2003           NA
26                  No         1.0              No         1998           NA
27                  No         1.0              No         1998           NA
28                  No         1.0              No         2012           NA

In [74]:
#Turn the merged dataframe to csv file
result.to_csv("openAndClose.csv", index = False)

In [75]:
#check duplicates
print(len(result['NCESSCH']) == len(result['NCESSCH'].unique()), len(result['NCESSCH']), len(result['NCESSCH'].unique()), " unique for file 1")

True 136804 136804  unique for file 1