In [1]:
# Import packages & functions:
import pandas
import numpy

In [2]:
import pandas as pd # For working with DataFrames
import ast # For working with strings
import numpy as np # For numerical things
import re # For cleaning webtext

# For loading functions from files in data_tools directory:
import sys; sys.path.insert(0, "../../data_tools")

In [3]:
# For displaying basic DF info, storing DFs for memory efficiency, and loading a filtered DF:
from df_tools import check_df, convert_df, load_filtered_df, replace_df_nulls

# For quickly loading & saving pickle files in Python:
from quickpickle import quickpickle_dump, quickpickle_load 

# For saving and loading text lists to/from file:
from textlist_file import write_list, load_list 

# For calculating densities, years opened and closed, and school closure rates:
from df_calc import density_calc, closerate_calc

In [4]:
# Input files:
charters_path = "../../nowdata/charters_2015.pkl"
pubschools_path = "../../nowdata/pubschools_2015.pkl"

charters_small_loc = "../../nowdata/backups/charters_parsed_03-04_no-text_SMALL.csv"
ACSsmall_loc = "../data/ACS_2016_sd-merged_SMALL.csv"
ACSfull_loc = "../data/ACS_2016_sd-merged_FULL.csv"
SAIPE_loc = "../data/SAIPE_2016_sd.txt"

In [5]:
# Define variables to keep from full charter data set
keepvars = ['LEVEL', 'MEMBER', 'SE_T002_002', 'TOTETH', 'WH', 'TOTFRL', 'PCT_SE_T113_002', 
            'ESS_VALID_RATIO', 'PROG_VALID_RATIO', 'INQUIRY_RATIO', 'DISCIPLINE_RATIO', 'LSTATE', 'CMO_NAME', 
            'LEAID', 'GEO_LEAID', 'NCESSCH', 'SY_STATUS15', 'TITLEI', 'FTE', 'SCHNAM15',
            'LAT1516', 'LON1516', 'ADDRESS16', 'ALL_RLA00PCTPROF_1516', 'ALL_MTH00PCTPROF_1516']

statusyears_list = ['STATUS98', 'STATUS99', 'STATUS00', 'STATUS01', 'STATUS02', 'STATUS03', 
                    'STATUS04', 'STATUS05', 'STATUS06', 'STATUS07', 'STATUS08', 'STATUS09', 
                    'STATUS10', 'STATUS11', 'STATUS12', 'STATUS13', 'SY_STATUS', 'SY_STATUS15', 'SY_STATUS16']

In [6]:
# Load and filter charter data set
charterdf = load_filtered_df(charters_path, keepvars+statusyears_list)

# rows and cols:  (10965, 43)
# duplicates by NCESSCH: 0

Columns and # missing cases (if any):
LEVEL: 3577 missing
MEMBER: 4034 missing
SE_T002_002: 7951 missing
TOTETH: 4034 missing
WH: 4034 missing
TOTFRL: 4034 missing
PCT_SE_T113_002: 7892 missing
ESS_VALID_RATIO: 4103 missing
PROG_VALID_RATIO: 4103 missing
INQUIRY_RATIO: 4103 missing
DISCIPLINE_RATIO: 4103 missing
LSTATE: 3577 missing
CMO_NAME: 8421 missing
LEAID: 4016 missing
GEO_LEAID: 3612 missing
NCESSCH
SY_STATUS15: 3619 missing
TITLEI: 4597 missing
FTE: 4192 missing
SCHNAM15: 3619 missing
LAT1516: 3613 missing
LON1516: 3613 missing
ADDRESS16: 3532 missing
ALL_RLA00PCTPROF_1516: 4663 missing
ALL_MTH00PCTPROF_1516: 4665 missing
STATUS98: 9600 missing
STATUS99: 9048 missing
STATUS00: 8570 missing
STATUS01: 8186 missing
STATUS02: 7749 missing
STATUS03: 7355 missing
STATUS04: 6781 missing
STATUS05: 6393 missing
STATUS06: 6178 missing
STATUS07: 6019 missing
STATUS08: 5652 missing
STATUS09: 5396 missing
STATUS10: 5017 missing
STATUS11: 4632 missing
STATUS12: 4332 missing
STATUS13: 3991 missing
SY_STATUS: 3577 missing
SY_STATUS16: 3532 missing

In [7]:
# Filter to only open schools
filtered_STATUS = (charterdf['SY_STATUS15'] == 1) | (charterdf['SY_STATUS15'] == 3) | (charterdf['SY_STATUS15'] == 4) | (charterdf['SY_STATUS15'] == 5) | (charterdf['SY_STATUS15'] == 8)
df = charterdf.loc[filtered_STATUS].reset_index(drop=True)

check_df(df, "NCESSCH")

# rows and cols:  (6947, 43)
# duplicates by NCESSCH: 0

Columns and # missing cases (if any):
LEVEL
MEMBER: 19 missing
SE_T002_002: 4076 missing
TOTETH: 19 missing
WH: 19 missing
TOTFRL: 19 missing
PCT_SE_T113_002: 4017 missing
ESS_VALID_RATIO: 647 missing
PROG_VALID_RATIO: 647 missing
INQUIRY_RATIO: 647 missing
DISCIPLINE_RATIO: 647 missing
LSTATE
CMO_NAME: 4582 missing
LEAID: 3 missing
GEO_LEAID
NCESSCH
SY_STATUS15
TITLEI: 908 missing
FTE: 541 missing
SCHNAM15
LAT1516
LON1516
ADDRESS16: 33 missing
ALL_RLA00PCTPROF_1516: 649 missing
ALL_MTH00PCTPROF_1516: 651 missing
STATUS98: 6018 missing
STATUS99: 5762 missing
STATUS00: 5521 missing
STATUS01: 5269 missing
STATUS02: 4975 missing
STATUS03: 4703 missing
STATUS04: 4350 missing
STATUS05: 4069 missing
STATUS06: 3790 missing
STATUS07: 3530 missing
STATUS08: 3199 missing
STATUS09: 2907 missing
STATUS10: 2465 missing
STATUS11: 1934 missing
STATUS12: 1498 missing
STATUS13: 964 missing
SY_STATUS
SY_STATUS16: 33 missing

In [12]:
df

,LEVEL,MEMBER,SE_T002_002,TOTETH,WH,TOTFRL,PCT_SE_T113_002,ESS_VALID_RATIO,PROG_VALID_RATIO,INQUIRY_RATIO,...,STATUS06,STATUS07,STATUS08,STATUS09,STATUS10,STATUS11,STATUS12,STATUS13,SY_STATUS,SY_STATUS16
0,1,170.0,0.706206,167.0,3.0,149.0,21.83,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,1,190.0,2.822938,127.0,63.0,102.0,7.54,0.000000,0.000752,0.003762,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,1,169.0,2.822938,91.0,78.0,88.0,7.54,0.000212,0.000177,0.009768,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,1,377.0,175.587500,99.0,278.0,0.0,5.63,0.000000,0.000000,0.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4,4,503.0,175.587500,194.0,309.0,0.0,5.63,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
5,1,273.0,175.587500,69.0,204.0,0.0,5.63,0.000322,0.000644,0.009728,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6,1,176.0,175.587500,37.0,139.0,0.0,5.63,0.000000,0.000000,0.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
7,4,270.0,175.587500,76.0,194.0,0.0,5.63,0.000128,0.000257,0.007451,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
8,4,163.0,175.587500,70.0,93.0,0.0,5.63,0.000000,0.000000,0.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
9,1,468.0,175.587500,92.0,376.0,0.0,5.63,NaN,NaN,NaN,...,NaN,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
10,1,326.0,175.587500,311.0,15.0,326.0,5.63,0.000000,0.000000,0.000000,...,NaN,NaN,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
11,4,101.0,175.587500,39.0,62.0,0.0,5.63,0.000000,0.000000,0.001610,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
12,1,74.0,12.037320,35.0,39.0,19.0,4.23,0.000218,0.000436,0.015738,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
13,1,181.0,3.585432,28.0,153.0,0.0,7.13,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
14,1,92.0,3.585432,19.0,73.0,25.0,7.13,0.000000,0.000000,0.001215,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
15,1,162.0,3.585432,29.0,133.0,36.0,7.13,0.000000,0.000845,0.000844,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
16,1,256.0,3.585432,79.0,177.0,56.0,7.13,0.000000,0.000169,0.002026,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
17,1,241.0,4.010054,43.0,198.0,0.0,6.43,0.000000,0.000000,0.000861,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
18,1,189.0,4.010054,33.0,156.0,0.0,6.43,0.000000,0.000000,0.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
19,4,174.0,4.010054,43.0,131.0,0.0,6.43,0.000000,0.000000,0.005198,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
20,4,391.0,4.010054,63.0,328.0,0.0,6.43,0.000000,0.000110,0.004067,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
21,1,249.0,4.010054,64.0,185.0,0.0,6.43,0.000000,0.000000,0.001439,...,NaN,NaN,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
22,1,388.0,4.010054,107.0,281.0,0.0,6.43,0.000204,0.000123,0.005641,...,NaN,NaN,NaN,NaN,3.0,1.0,1.0,1.0,1.0,1.0
23,2,61.0,299.345200,46.0,15.0,0.0,8.21,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
24,1,152.0,13.647740,31.0,121.0,0.0,4.75,0.000000,0.000000,0.003650,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
25,3,191.0,13.647740,69.0,122.0,60.0,4.75,0.000000,0.000000,0.004057,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
26,3,156.0,13.647740,121.0,35.0,108.0,4.75,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
27,1,200.0,13.647740,43.0,157.0,0.0,4.75,0.000000,0.000000,0.006734,...,NaN,NaN,NaN,3.0,1.0,1.0,1.0,1.0,1.0,1.0
28,1,675.0,276.134600,93.0,582.0,60.0,4.06,0.000000,0.000000,0.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
29,3,105.0,NaN,40.0,65.0,63.0,NaN,0.000000,0.000000,0.010542,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6917,1,393.0,1030.846000,393.0,0.0,341.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6918,1,104.0,1030.846000,104.0,0.0,92.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6919,1,382.0,1030.846000,382.0,0.0,314.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6920,1,393.0,1030.846000,392.0,1.0,352.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6921,1,170.0,1030.846000,169.0,1.0,144.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6922,1,304.0,1030.846000,304.0,0.0,268.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6923,1,665.0,1030.846000,665.0,0.0,558.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6924,1,301.0,1030.846000,301.0,0.0,253.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6925,1,286.0,1030.846000,286.0,0.0,242.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6926,1,114.0,1030.846000,114.0,0.0,95.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6927,3,577.0,1030.846000,577.0,0.0,510.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6928,1,158.0,1030.846000,158.0,0.0,140.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6929,1,302.0,1030.846000,302.0,0.0,259.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6930,4,567.0,1030.846000,566.0,1.0,497.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6931,1,213.0,1030.846000,213.0,0.0,184.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6932,1,314.0,1030.846000,314.0,0.0,270.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6933,1,166.0,1030.846000,164.0,2.0,142.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6934,1,183.0,1030.846000,183.0,0.0,158.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6935,1,286.0,1030.846000,285.0,1.0,249.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6936,4,580.0,1030.846000,580.0,0.0,515.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6937,1,263.0,1030.846000,261.0,2.0,218.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6938,1,200.0,1030.846000,196.0,4.0,173.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6939,2,754.0,1030.846000,754.0,0.0,680.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6940,1,97.0,1030.846000,97.0,0.0,83.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6941,2,425.0,1030.846000,425.0,0.0,385.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6942,2,522.0,1030.846000,522.0,0.0,469.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6943,3,144.0,1030.846000,144.0,0.0,126.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0
6944,2,411.0,1030.846000,411.0,0.0,372.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6945,2,489.0,1030.846000,489.0,0.0,440.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6946,1,395.0,1030.846000,395.0,0.0,340.0,41.24,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [8]:
df[df['SY_STATUS15'] != df['SY_STATUS']][['SY_STATUS', 'SY_STATUS15']]

      SY_STATUS  SY_STATUS15
2153        2.0          3.0
6552        2.0          1.0
6563        2.0          1.0
6623        1.0          5.0
6624        1.0          5.0
6625        1.0          5.0

In [12]:
df.iloc[6563]

LEVEL                                                  N
MEMBER                                               NaN
SE_T002_002                                          NaN
TOTETH                                               NaN
WH                                                   NaN
TOTFRL                                               NaN
PCT_SE_T113_002                                      NaN
ESS_VALID_RATIO                                      NaN
PROG_VALID_RATIO                                     NaN
INQUIRY_RATIO                                        NaN
DISCIPLINE_RATIO                                     NaN
LSTATE                                                UT
CMO_NAME                                             NaN
LEAID                                                NaN
GEO_LEAID                                     4.9006e+06
NCESSCH                                      4.90016e+11
SY_STATUS15                                            1
TITLEI                                                 0
FTE                                                   -1
SCHNAM15                 WASATCH INSTITUTE OF TECHNOLOGY
LAT1516                                          40.6625
LON1516                                         -111.895
ADDRESS16                                            NaN
ALL_RLA00PCTPROF_1516                                NaN
ALL_MTH00PCTPROF_1516                                NaN
STATUS98                                             NaN
STATUS99                                             NaN
STATUS00                                             NaN
STATUS01                                             NaN
STATUS02                                             NaN
STATUS03                                             NaN
STATUS04                                             NaN
STATUS05                                             NaN
STATUS06                                             NaN
STATUS07                                             NaN
STATUS08                                             NaN
STATUS09                                             NaN
STATUS10                                             NaN
STATUS11                                               7
STATUS12                                               7
STATUS13                                               2
SY_STATUS                                              2
SY_STATUS16                                          NaN
Name: 6563, dtype: object

In [59]:
df[df['STATUS13'] != result['SY_STATUS']]

,LEVEL,MEMBER,SE_T002_002,TOTETH,WH,TOTFRL,PCT_SE_T113_002,ESS_VALID_RATIO,PROG_VALID_RATIO,INQUIRY_RATIO,...,STATUS06,STATUS07,STATUS08,STATUS09,STATUS10,STATUS11,STATUS12,STATUS13,SY_STATUS,SY_STATUS16
11,4,101.0,175.587500,39.0,62.0,0.0,5.63,0.000000,0.000000,0.001610,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
42,3,13.0,NaN,0.0,13.0,-1.0,NaN,0.000876,0.000876,0.013363,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
52,2,0.0,NaN,0.0,0.0,-2.0,NaN,0.000324,0.000462,0.004407,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,6.0
61,3,862.0,NaN,179.0,683.0,-1.0,NaN,0.000246,0.000205,0.006572,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
120,1,376.0,NaN,120.0,256.0,218.0,NaN,0.000250,0.000083,0.003419,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,1.0,1.0
121,4,1499.0,NaN,468.0,1031.0,760.0,NaN,0.000256,0.000403,0.006451,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
147,3,193.0,NaN,169.0,24.0,172.0,NaN,0.000664,0.000332,0.005641,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
149,1,87.0,NaN,65.0,22.0,57.0,NaN,0.000932,0.000000,0.010266,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
180,3,90.0,NaN,29.0,61.0,55.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
233,1,208.0,NaN,167.0,41.0,146.0,NaN,0.000440,0.000000,0.014512,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
270,2,3.0,NaN,1.0,2.0,-1.0,NaN,0.000000,0.000000,0.004608,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
321,4,215.0,NaN,183.0,32.0,173.0,NaN,0.000587,0.000000,0.005575,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
360,4,443.0,NaN,191.0,252.0,110.0,NaN,0.000089,0.000125,0.002106,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
379,1,96.0,NaN,40.0,56.0,58.0,NaN,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
380,1,307.0,NaN,63.0,244.0,59.0,NaN,0.000434,0.000568,0.007550,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
381,1,160.0,NaN,22.0,138.0,-1.0,NaN,0.000456,0.000182,0.005468,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
427,3,189.0,NaN,185.0,4.0,182.0,NaN,0.000437,0.000109,0.002622,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
440,1,394.0,NaN,260.0,134.0,3.0,NaN,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
444,1,471.0,NaN,230.0,241.0,194.0,NaN,0.002016,0.000000,0.048682,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
446,4,112.0,NaN,36.0,76.0,-1.0,NaN,0.000059,0.000059,0.003610,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
500,1,531.0,NaN,171.0,360.0,-1.0,NaN,0.000529,0.001190,0.005684,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,3.0,1.0,1.0
502,1,133.0,NaN,85.0,48.0,77.0,NaN,0.000171,0.000812,0.007348,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,3.0,1.0,1.0
506,2,43.0,NaN,29.0,14.0,43.0,NaN,0.001174,0.000000,0.014873,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,3.0,1.0,1.0
511,1,74.0,NaN,23.0,51.0,-1.0,NaN,0.000632,0.000140,0.011102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
512,3,368.0,NaN,344.0,24.0,184.0,NaN,0.000247,0.000123,0.001665,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
513,4,793.0,NaN,458.0,335.0,-1.0,NaN,0.000000,0.000279,0.003345,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,1.0,1.0
514,1,45.0,NaN,40.0,5.0,37.0,NaN,0.000789,0.000789,0.001577,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
515,1,65.0,NaN,23.0,42.0,26.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
516,2,296.0,NaN,141.0,155.0,57.0,NaN,0.000022,0.000110,0.004984,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
517,1,310.0,NaN,178.0,132.0,165.0,NaN,0.000853,0.000244,0.008425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6724,1,903.0,573.707300,238.0,665.0,295.0,1.76,0.000000,0.000000,0.006811,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,1.0,1.0
6725,3,994.0,573.707300,242.0,752.0,309.0,1.76,0.000000,0.000000,0.004023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,1.0,1.0
6745,1,310.0,6235.461000,297.0,13.0,18.0,24.13,0.000767,0.000000,0.016910,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
6746,4,1051.0,6235.461000,1034.0,17.0,876.0,24.13,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
6747,4,1325.0,6235.461000,1319.0,6.0,1068.0,24.13,0.000534,0.000267,0.007141,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
6748,4,507.0,6235.461000,481.0,26.0,26.0,24.13,0.000000,0.002188,0.006565,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
6749,3,99.0,6235.461000,93.0,6.0,34.0,24.13,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
6756,1,150.0,7.143125,26.0,124.0,102.0,6.79,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
6757,4,0.0,7.143125,0.0,0.0,-2.0,6.79,0.000403,0.000058,0.006041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
6762,4,13.0,35.193580,1.0,12.0,6.0,7.41,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
6766,2,66.0,59.465990,19.0,47.0,29.0,7.21,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,1.0,1.0
6768,3,54.0,103.649600,3.0,51.0,25.0,7.02,0.000000,0.000000,0.052288,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
6769,3,42.0,103.649600,7.0,35.0,30.0,7.02,0.000000,0.000000,0.024155,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
6771,2,72.0,72.906850,3.0,69.0,23.0,6.62,0.002653,0.000000,0.010638,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
6778,4,15.0,99.959660,1.0,14.0,9.0,9.46,0.000210,0.000468,0.001215,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
6780,1,191.0,1379.434000,165.0,26.0,174.0,11.85,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
6784,4,12.0,41.532560,1.0,11.0,3.0,10.19,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
6788,1,123.0,104.229800,20.0,103.0,42.0,7.21,0.000000,0.000000,0.007772,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
6791,3,22.0,44.064750,0.0,22.0,3.0,1.98,0.000080,0.000034,0.004698,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
6808,2,60.0,61.230660,7.0,53.0,25.0,12.32,0.000000,0.000352,0.005170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
6812,2,52.0,155.639700,10.0,42.0,18.0,6.54,0.000000,0.000000,0.001493,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
6813,1,44.0,45.184200,9.0,35.0,14.0,6.08,0.000000,0.000000,0.011024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
6814,4,1.0,29.027650,0.0,1.0,-1.0,7.10,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
6818,3,74.0,719.469500,22.0,52.0,21.0,4.44,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,3.0,1.0,1.0
6821,1,66.0,43.869480,5.0,61.0,17.0,8.84,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,1.0,1.0
6822,3,51.0,187.703100,7.0,44.0,19.0,7.36,0.000073,0.000656,0.015824,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,1.0,1.0
6826,1,51.0,1343.588000,9.0,42.0,9.0,6.76,0.000000,0.000000,0.012088,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
6834,4,115.0,3577.740000,58.0,57.0,11.0,2.66,0.000000,0.000000,0.009901,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,3.0,1.0,1.0
6836,3,69.0,525.100600,10.0,59.0,27.0,4.95,0.000503,0.000000,0.003965,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0
6839,4,0.0,151.720900,0.0,0.0,-2.0,12.16,0.000091,0.000364,0.009921,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,1.0

In [13]:
df['SY_STATUS15'].value_counts()

1.0    6407
3.0     418
5.0     119
8.0       3
Name: SY_STATUS15, dtype: int64

## lambda/apply() version (faster but currently not working)

In [14]:
def openclose_calc(statusdf, statusvars_list, uniqueid):
    """Determines year that each school was opened and (if applicable) closed.
    
    Args:
        DataFrame holding years opened and closed raw data,
        list of status-years to keep from DF,
        unique identifier for each entity (e.g., NCES school #).
        
    Returns:
        1-column DF holding year opened for each entity,
        1-column DF holding year closed for each entity."""
    
    # Trim input DFs to only relevant variables for finding close rates and merging
    statusdf = statusdf[statusvars_list]
    
    # Get length of input DF
    length = statusdf.shape[0]
    
    cols = statusvars_list # Simplify naming for more interpretable functions
    
    # Define dictionary of status-year vars as (status col : corresponding year)
    yeardict = {'STATUS98' : 1998, 'STATUS99' : 1999, 'STATUS00' : 2000, 'STATUS01' : 2001, 
                'STATUS02' : 2002, 'STATUS03' : 2003, 'STATUS04' : 2004, 'STATUS05' : 2005,
                'STATUS06' : 2006, 'STATUS07' : 2007, 'STATUS08' : 2008, 'STATUS09' : 2009,
                'STATUS10' : 2010, 'STATUS11' : 2011, 'STATUS12' : 2012, 'STATUS13' : 2013,
                'SY_STATUS' : 2014, 'SY_STATUS15' : 2015, 'SY_STATUS16' : 2016}

    # Define helper functions for workhorse algorithm below
    def checkOpenData(statusArr, currYear):
        """Check for any open status data all the years before given year. 
        If no previous data on open status, open_year should be this year.
        If there is a number with meaningful data on openness (this excludes -1, 2, 6, 7), 
        then return False; else return True."""
        
        allNeg1 = True
        for prevStat in statusArr[:cols.index(currYear)]:
            if prevStat != -1 and prevStat != 2 and prevStat != 6 and prevStat != 7:
                allNeg1 = False
        return allNeg1

    def checkClosedAfter(statusArr, currYear):
        """Check for any closure status data all the years AFTER given year.
        If no later data on closure status, closed_year should be this year.
        If there is a 2 or 6, return True; else return False."""
        
        is2or6 = False
        for afterStat in statusArr[cols.index(currYear):]:
            if afterStat == 2 or afterStat == 6:
                is2or6 = True
        return is2or6

    def checkCloseData(statusArr):
        """Check for any closure status data ALL years for a given school.
        If there exist a 2 or 6 at any point, return True; else return False."""
        
        is2or6 = False
        for stat in statusArr:
            if stat == 2 or stat == 6:
                is2or6 = True
        return is2or6

    def getyears_openclose(daterow):
        """Main algorithm to detect year opened and closed.
        Goes through certain interval of years, inclusive.
        
        Args:
            Row with dates of status (1 thru 8) for each year in cols (1998-2016).
            
        Returns:
            Year that entity opened, year that entity closed."""
        
        statusArr = [] # stores status values for each year

        # Initialize the two series to store year opened and closed
        YEAR_OPENED = numpy.NaN
        YEAR_CLOSED = numpy.NaN

        # Put things in statusArr
        for i in range(len(cols)):
            if numpy.isnan(daterow[cols[i]]):
                statusArr += [-1] #-1 if there is a nan in certain status
            else:
                statusArr += [int(daterow[cols[i]])]

        # Main logic         
        for col in cols:    
            stat = -1
            if(not numpy.isnan(daterow[col])):
                stat = int(daterow[col])

            # If there is a 2, then close_year should be this year
            if(stat == 2):
                YEAR_CLOSED = yeardict.get(col)

            # If 1, 3, 4, 5, or 8, run checkOpenData()
            # If no previous status, open_year should be this year
            if(stat in [1, 3, 4, 5, 8]):
                if checkOpenData(statusArr, col):
                    YEAR_OPENED = yeardict.get(col)

            # If 4, run checkOpenData()
            # If no previous status, open_year should be the year before this year        
            if(stat == 4):
                if checkOpenData(statusArr, col):
                    YEAR_OPENED = yeardict.get(cols[(cols.index(col) - 1)])

            # If 8, run checkClosedAfter()
            # If no closure status data (2 or 6) after this year, year_closed should be nothing
            if(stat == 8):
                if not checkClosedAfter(statusArr, col):
                    YEAR_CLOSED = numpy.NaN

            # If 6, run checkClosedAfter()
            # If no closure status data (2 or 6) after this year, year_closed should be this year
            if(stat == 6):
                if not checkClosedAfter(statusArr, col):
                    YEAR_CLOSED = yeardict.get(col)

        # If never 2 or 6, year_closed is numpy.NaN
        # Use checkCloseData() to check this
        if not checkCloseData(statusArr):
            YEAR_CLOSED = numpy.NaN
            
        return YEAR_OPENED, YEAR_CLOSED
    
    
    statusdf['YEAR_OPENED'], statusdf['YEAR_CLOSED'] = statusdf.apply(lambda x: getyears_openclose(x), axis=1)
    
    return statusdf['YEAR_OPENED'], statusdf['YEAR_CLOSED']

In [15]:
# Create new variable with years schools were opened and closed
#df["YEAR_OPENED_FUN"], df["YEAR_CLOSED_FUN"] = openclose_calc(df, statusyears_list, 'NCESSCH')
#df["YEAR_OPENED_FUN"], df["YEAR_CLOSED_FUN"] = openclose_calc(df, statusyears_list, 'NCESSCH')
#print("# empties:", df["YEAR_OPENED_FUN"].isnull().sum())

In [16]:
df.columns

Index(['LEVEL', 'MEMBER', 'SE_T002_002', 'TOTETH', 'WH', 'TOTFRL',
       'PCT_SE_T113_002', 'ESS_VALID_RATIO', 'PROG_VALID_RATIO',
       'INQUIRY_RATIO', 'DISCIPLINE_RATIO', 'LSTATE', 'CMO_NAME', 'LEAID',
       'GEO_LEAID', 'NCESSCH', 'SY_STATUS15', 'TITLEI', 'FTE', 'SCHNAM15',
       'LAT1516', 'LON1516', 'ADDRESS16', 'ALL_RLA00PCTPROF_1516',
       'ALL_MTH00PCTPROF_1516', 'STATUS98', 'STATUS99', 'STATUS00', 'STATUS01',
       'STATUS02', 'STATUS03', 'STATUS04', 'STATUS05', 'STATUS06', 'STATUS07',
       'STATUS08', 'STATUS09', 'STATUS10', 'STATUS11', 'STATUS12', 'STATUS13',
       'SY_STATUS', 'SY_STATUS16'],
      dtype='object')

## Array-based version (slower but functional)

In [17]:
#make two series to store the newly created columns
length = df.shape[0]

#initialize the two columns
YEAR_OPENED = ["NA" for i in range(length)]
YEAR_CLOSED = [None for i in range(length)]

#the names of all the status col
status = df[['STATUS98', 'STATUS99', 'STATUS00', 'STATUS01', 'STATUS02', 'STATUS03',\
             'STATUS04', 'STATUS05', 'STATUS06', 'STATUS07', 'STATUS08', 'STATUS09',\
             'STATUS10', 'STATUS11', 'STATUS12', 'STATUS13', 'SY_STATUS', 'SY_STATUS15', 'SY_STATUS16']]

#dictionary of (status col : corresponding year)
cols = {'STATUS98' : '1998', 'STATUS99' : '1999', 'STATUS00' : '2000', 'STATUS01' : '2001',\
        'STATUS02' : '2002', 'STATUS03' : '2003', 'STATUS04' : '2004', 'STATUS05' : '2005',\
        'STATUS06' : '2006', 'STATUS07' : '2007', 'STATUS08' : '2008', 'STATUS09' : '2009',\
        'STATUS10' : '2010', 'STATUS11' : '2011', 'STATUS12' : '2012', 'STATUS13' : '2013',\
        'SY_STATUS' : '2014', 'SY_STATUS15' : '2015', 'SY_STATUS16' : '2016'}

#status as a list
b = ['STATUS98', 'STATUS99', 'STATUS00', 'STATUS01', 'STATUS02', 'STATUS03', 'STATUS04',\
     'STATUS05', 'STATUS06', 'STATUS07', 'STATUS08', 'STATUS09', 'STATUS10', 'STATUS11',\
     'STATUS12', 'STATUS13', 'SY_STATUS', 'SY_STATUS15', 'SY_STATUS16']

### Ji's functions

In [18]:
'''
#check all the years before the year we are looking. 
#if there is a number(except for -1, 5, 6, 7) appears, return False.
#else return True.

def checkPrevYears(statusArr, currYear):
    allNeg1 = True
    for prevStat in statusArr[:b.index(currYear)]:
        if prevStat != -1 and prevStat != 5 and prevStat != 6 and prevStat != 7:
            allNeg1 = False
    return allNeg1

#check all the years after the year we are looking.
#if there is a 2 or 6, return True. else return False

def checkAfterYears(statusArr, currYear):
    is2or6 = False
    for afterStat in statusArr[b.index(currYear):]:
        if afterStat == 2 or afterStat == 6:
            is2or6 = True
    return is2or6

def checkAfter6(statusArr, currYear):
    anythingAfter = False
    for afterStat in statusArr[b.index(currYear):]:
        if afterStat != None:
            anythingAfter = True
    return anythingAfter

#check all the years for a certain school.
#if there exist a 2 or 6, return True; else return False;

def checkAllYears(statusArr):
    is2or6 = False
    for stat in statusArr:
        if stat == 2 or stat == 6:
            is2or6 = True
    return is2or6

#main algorithm for a certain interval, inclusive.
#go through each row
YEAR_OPENED = [np.NaN for i in range(length)]
YEAR_CLOSED = [np.NaN for i in range(length)]
for index, row in status.iterrows():
    #only calculate for the input interval
    if index >= 0 and index < df.shape[0]:
        statusArr = [] #a list used to store all status for a year

        #putting things in statusArr
        for i in range(len(cols)):
            if np.isnan(row[b[i]]):
                statusArr += [-1] #-1 if there is a nan in certain status
            else:
                statusArr += [int(row[b[i]])]

        #main logic         
        for col in cols:    
            stat = -1
            if(not np.isnan(row[col])):
                stat = int(row[col])

            #if there is a 2, the close_year should be this year
            if(stat == 2):
                YEAR_CLOSED[index] = cols.get(col)

            #if 1,3 or 8, checkPreYears, if no previous status, open_year should be this year
            if(stat == 1 or stat == 3 or stat == 8):
                if checkPrevYears(statusArr, col):
                    YEAR_OPENED[index] = cols.get(col)

            #if 4, checkPrevYears. If no previous status, open_year should be the year before this year        
            if(stat == 4):
                if checkPrevYears(statusArr, col):
                    YEAR_OPENED[index] = cols.get(b[(b.index(col) - 1)])

            #if 8, checkLaterYear. If nothing after, year_closed should be this year
            if(stat == 8):
                if not checkAfterYears(statusArr, col):
                    YEAR_CLOSED[index] = np.NaN
            
            #if nothing after 6, year_closed should be this year
            if(stat == 6):
                if not checkAfter6(statusArr, col):
                    YEAR_CLOSED[index] = cols.get(col)

        #if never 2 or 6, year_closed is 'NA'
        if not checkAllYears(statusArr):
            YEAR_CLOSED[index] = 'NA'
            
            '''

"\n#check all the years before the year we are looking. \n#if there is a number(except for -1, 5, 6, 7) appears, return False.\n#else return True.\n\ndef checkPrevYears(statusArr, currYear):\n    allNeg1 = True\n    for prevStat in statusArr[:b.index(currYear)]:\n        if prevStat != -1 and prevStat != 5 and prevStat != 6 and prevStat != 7:\n            allNeg1 = False\n    return allNeg1\n\n#check all the years after the year we are looking.\n#if there is a 2 or 6, return True. else return False\n\ndef checkAfterYears(statusArr, currYear):\n    is2or6 = False\n    for afterStat in statusArr[b.index(currYear):]:\n        if afterStat == 2 or afterStat == 6:\n            is2or6 = True\n    return is2or6\n\ndef checkAfter6(statusArr, currYear):\n    anythingAfter = False\n    for afterStat in statusArr[b.index(currYear):]:\n        if afterStat != None:\n            anythingAfter = True\n    return anythingAfter\n\n#check all the years for a certain school.\n#if there exist a 2 or 6, return True; else return False;\n\ndef checkAllYears(statusArr):\n    is2or6 = False\n    for stat in statusArr:\n        if stat == 2 or stat == 6:\n            is2or6 = True\n    return is2or6\n\n#main algorithm for a certain interval, inclusive.\n#go through each row\nYEAR_OPENED = [np.NaN for i in range(length)]\nYEAR_CLOSED = [np.NaN for i in range(length)]\nfor index, row in status.iterrows():\n    #only calculate for the input interval\n    if index >= 0 and index < df.shape[0]:\n        statusArr = [] #a list used to store all status for a year\n\n        #putting things in statusArr\n        for i in range(len(cols)):\n            if np.isnan(row[b[i]]):\n                statusArr += [-1] #-1 if there is a nan in certain status\n            else:\n                statusArr += [int(row[b[i]])]\n\n        #main logic         \n        for col in cols:    \n            stat = -1\n            if(not np.isnan(row[col])):\n                stat = int(row[col])\n\n            #if there is a 2, the close_year should be this year\n            if(stat == 2):\n                YEAR_CLOSED[index] = cols.get(col)\n\n            #if 1,3 or 8, checkPreYears, if no previous status, open_year should be this year\n            if(stat == 1 or stat == 3 or stat == 8):\n                if checkPrevYears(statusArr, col):\n                    YEAR_OPENED[index] = cols.get(col)\n\n            #if 4, checkPrevYears. If no previous status, open_year should be the year before this year        \n            if(stat == 4):\n                if checkPrevYears(statusArr, col):\n                    YEAR_OPENED[index] = cols.get(b[(b.index(col) - 1)])\n\n            #if 8, checkLaterYear. If nothing after, year_closed should be this year\n            if(stat == 8):\n                if not checkAfterYears(statusArr, col):\n                    YEAR_CLOSED[index] = np.NaN\n            \n            #if nothing after 6, year_closed should be this year\n            if(stat == 6):\n                if not checkAfter6(statusArr, col):\n                    YEAR_CLOSED[index] = cols.get(col)\n\n        #if never 2 or 6, year_closed is 'NA'\n        if not checkAllYears(statusArr):\n            YEAR_CLOSED[index] = 'NA'\n            \n            "

### Jaren's functions

In [19]:
# Simplify naming for more interpretable functions
cols = ['STATUS98', 'STATUS99', 'STATUS00', 'STATUS01', 'STATUS02', 'STATUS03', 'STATUS04',\
     'STATUS05', 'STATUS06', 'STATUS07', 'STATUS08', 'STATUS09', 'STATUS10', 'STATUS11',\
     'STATUS12', 'STATUS13', 'SY_STATUS', 'SY_STATUS15', 'SY_STATUS16']
    
# Define dictionary of status-year vars as (status col : corresponding year)
yeardict = {'STATUS98' : 1998, 'STATUS99' : 1999, 'STATUS00' : 2000, 'STATUS01' : 2001, 
                'STATUS02' : 2002, 'STATUS03' : 2003, 'STATUS04' : 2004, 'STATUS05' : 2005,
                'STATUS06' : 2006, 'STATUS07' : 2007, 'STATUS08' : 2008, 'STATUS09' : 2009,
                'STATUS10' : 2010, 'STATUS11' : 2011, 'STATUS12' : 2012, 'STATUS13' : 2013,
                'SY_STATUS' : 2014, 'SY_STATUS15' : 2015, 'SY_STATUS16' : 2016}

# Define helper functions for workhorse algorithm below
def checkOpenData(statusArr, currYear):
        """Check for any open status data all the years before given year. 
        If no previous data on open status, open_year should be this year.
        If there is a number with meaningful data on openness (this excludes -1, 2, 6, 7), 
        then return False; else return True."""
        
        allNeg1 = True
        for prevStat in statusArr[:cols.index(currYear)]:
            if prevStat != -1 and prevStat != 2 and prevStat != 6 and prevStat != 7:
                allNeg1 = False
        return allNeg1

def checkClosedAfter(statusArr, currYear):
        """Check for any closure status data all the years AFTER given year.
        If no later data on closure status, closed_year should be this year.
        If there is a 2 or 6, return True; else return False."""
        
        is2or6 = False
        for afterStat in statusArr[cols.index(currYear):]:
            if afterStat == 2 or afterStat == 6:
                is2or6 = True
        return is2or6

def checkCloseData(statusArr):
        """Check for any closure status data ALL years for a given school.
        If there exist a 2 or 6 at any point, return True; else return False."""
        
        is2or6 = False
        for stat in statusArr:
            if stat == 2 or stat == 6:
                is2or6 = True
        return is2or6

# Initialize the two series to store years opened and closed
YEAR_OPENED = [numpy.NaN for i in range(length)]
YEAR_CLOSED = [numpy.NaN for i in range(length)]

# Main algorithm to detect year opened and closed.
# Goes through each row for a certain interval, inclusive.
    
for index, row in df.iterrows():
    #only calculate for the input interval
    if index >= 0 and index < length:
        statusArr = [] #a list used to store all status for a year

        # Put things in statusArr
        for i in range(len(cols)):
            if numpy.isnan(row[cols[i]]):
                statusArr += [-1] #-1 if there is a nan in certain status
            else:
                statusArr += [int(row[cols[i]])]

        # Main logic         
        for col in cols:    
            stat = -1
            if(not numpy.isnan(row[col])):
                stat = int(row[col])

            # If there is a 2, then close_year should be this year
            if(stat == 2):
                YEAR_CLOSED[index] = yeardict.get(col)

            # If 1, 3, 4, 5, or 8, run checkOpenData()
            # If no previous status, open_year should be this year
            if(stat in [1, 3, 4, 5, 8]):
                if checkOpenData(statusArr, col):
                    YEAR_OPENED[index] = yeardict.get(col)

            # If 4, run checkOpenData()
            # If no previous status, open_year should be the year before this year        
            if(stat == 4):
                if checkOpenData(statusArr, col):
                    YEAR_OPENED[index] = yeardict.get(cols[(cols.index(col) - 1)])

            # If 8, run checkClosedAfter()
            # If no closure status data (2 or 6) after this year, year_closed should be nothing
            if(stat == 8):
                if not checkClosedAfter(statusArr, col):
                    YEAR_CLOSED[index] = numpy.NaN

            # If 6, run checkClosedAfter()
            # If no closure status data (2 or 6) after this year, year_closed should be this year
            if(stat == 6):
                if not checkClosedAfter(statusArr, col):
                    YEAR_CLOSED[index] = yeardict.get(col)

        # If never 2 or 6, year_closed is numpy.NaN
        # Use checkCloseData() to check this
        if not checkCloseData(statusArr):
            YEAR_CLOSED[index] = numpy.NaN

### Testing/ quality check

In [20]:
# This is used for testing only
for index in range(0, df.shape[0]):
    if YEAR_CLOSED[index] == None or YEAR_OPENED[index] == None:
        print(index,"|", YEAR_OPENED[index],"|", YEAR_CLOSED[index])

In [21]:
# Create two dataframe for the mappings
label = ['YEAR_OPENED']
label2 = ['YEAR_CLOSED']
dfOpened = pandas.DataFrame(YEAR_OPENED, columns = label)
dfClosed = pandas.DataFrame(YEAR_CLOSED, columns = label2)

In [22]:
# Concatenating the two mapping dataframe to our source
# Here we use concat instead of merge because the sequence of NCESSCH is preserved
result = df.copy()
result['YEAR_OPENED'] = dfOpened['YEAR_OPENED']
result['YEAR_CLOSED'] = dfClosed['YEAR_CLOSED']

In [23]:
result["YEAR_OPENED"].value_counts()

2014    1058
1998     959
2013     581
2011     477
2012     460
2010     385
2009     323
2008     320
2004     311
2005     305
2006     305
1999     254
2000     252
2002     250
2007     241
2003     235
2001     229
2015       2
Name: YEAR_OPENED, dtype: int64

In [45]:
a = result[result['SY_STATUS15'] == 1.0]
len(a[result['SY_STATUS'] != 1.0])

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

2

In [25]:
check_df(result, "NCESSCH")

# rows and cols:  (6947, 45)
# duplicates by NCESSCH: 0

Columns and # missing cases (if any):
LEVEL
MEMBER: 19 missing
SE_T002_002: 4076 missing
TOTETH: 19 missing
WH: 19 missing
TOTFRL: 19 missing
PCT_SE_T113_002: 4017 missing
ESS_VALID_RATIO: 647 missing
PROG_VALID_RATIO: 647 missing
INQUIRY_RATIO: 647 missing
DISCIPLINE_RATIO: 647 missing
LSTATE
CMO_NAME: 4582 missing
LEAID: 3 missing
GEO_LEAID
NCESSCH
SY_STATUS15
TITLEI: 908 missing
FTE: 541 missing
SCHNAM15
LAT1516
LON1516
ADDRESS16: 33 missing
ALL_RLA00PCTPROF_1516: 649 missing
ALL_MTH00PCTPROF_1516: 651 missing
STATUS98: 6018 missing
STATUS99: 5762 missing
STATUS00: 5521 missing
STATUS01: 5269 missing
STATUS02: 4975 missing
STATUS03: 4703 missing
STATUS04: 4350 missing
STATUS05: 4069 missing
STATUS06: 3790 missing
STATUS07: 3530 missing
STATUS08: 3199 missing
STATUS09: 2907 missing
STATUS10: 2465 missing
STATUS11: 1934 missing
STATUS12: 1498 missing
STATUS13: 964 missing
SY_STATUS
SY_STATUS16: 33 missing
YEAR_OPENED
YEAR_CLOSED: 6753 missing

In [26]:
result [result["YEAR_OPENED"]==2014] [["STATUS12", "STATUS13", "SY_STATUS", "SY_STATUS15"]]

      STATUS12  STATUS13  SY_STATUS  SY_STATUS15
11         NaN       NaN        3.0          3.0
42         NaN       NaN        1.0          1.0
120        NaN       7.0        1.0          1.0
121        NaN       NaN        3.0          3.0
233        NaN       NaN        1.0          1.0
270        NaN       NaN        3.0          3.0
321        NaN       NaN        1.0          1.0
380        NaN       NaN        1.0          1.0
381        NaN       NaN        3.0          3.0
444        NaN       NaN        1.0          1.0
446        NaN       NaN        1.0          1.0
513        NaN       7.0        1.0          1.0
515        NaN       NaN        1.0          1.0
516        NaN       NaN        1.0          1.0
517        NaN       NaN        1.0          1.0
518        NaN       7.0        1.0          1.0
519        NaN       NaN        1.0          1.0
520        NaN       NaN        1.0          1.0
521        NaN       NaN        1.0          1.0
522        NaN       7.0        1.0          1.0
524        NaN       NaN        1.0          1.0
531        NaN       7.0        1.0          1.0
532        NaN       NaN        1.0          1.0
533        NaN       NaN        1.0          1.0
534        NaN       NaN        1.0          1.0
535        NaN       NaN        1.0          1.0
536        NaN       NaN        1.0          1.0
537        NaN       NaN        1.0          1.0
538        NaN       NaN        1.0          1.0
539        NaN       NaN        1.0          1.0
...        ...       ...        ...          ...
6654       NaN       NaN        3.0          3.0
6656       NaN       NaN        5.0          5.0
6661       NaN       NaN        3.0          3.0
6665       NaN       NaN        1.0          1.0
6668       NaN       NaN        3.0          3.0
6669       NaN       NaN        3.0          3.0
6673       NaN       NaN        3.0          3.0
6684       NaN       NaN        1.0          1.0
6694       NaN       7.0        1.0          1.0
6695       NaN       NaN        1.0          1.0
6710       NaN       7.0        1.0          1.0
6713       NaN       7.0        1.0          1.0
6723       NaN       NaN        3.0          3.0
6724       NaN       7.0        1.0          1.0
6725       NaN       7.0        1.0          1.0
6749       NaN       NaN        1.0          1.0
6756       NaN       NaN        1.0          1.0
6757       NaN       NaN        3.0          3.0
6762       NaN       NaN        1.0          1.0
6766       NaN       7.0        1.0          1.0
6769       NaN       NaN        1.0          1.0
6780       NaN       NaN        1.0          1.0
6784       NaN       NaN        1.0          1.0
6808       NaN       NaN        1.0          1.0
6812       NaN       NaN        3.0          3.0
6813       NaN       NaN        3.0          3.0
6814       NaN       NaN        1.0          1.0
6821       NaN       7.0        1.0          1.0
6822       NaN       7.0        1.0          1.0
6826       NaN       NaN        1.0          1.0

[1058 rows x 4 columns]

In [53]:
result[result['SY_STATUS15'] != result['SY_STATUS']][['SY_STATUS', 'SY_STATUS15']]

      SY_STATUS  SY_STATUS15
2153        2.0          3.0
6552        2.0          1.0
6563        2.0          1.0
6623        1.0          5.0
6624        1.0          5.0
6625        1.0          5.0

In [27]:
result [result["YEAR_OPENED"]==2015] [["STATUS12", "STATUS13", "SY_STATUS", "SY_STATUS15"]]

      STATUS12  STATUS13  SY_STATUS  SY_STATUS15
2153       NaN       NaN        2.0          3.0
6563       7.0       2.0        2.0          1.0

In [28]:
result [result["SY_STATUS"]==1] [result["SY_STATUS15"]==1] \
[["YEAR_OPENED", "YEAR_CLOSED", "STATUS12", "STATUS13", "SY_STATUS", "SY_STATUS15"]]

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

      YEAR_OPENED  YEAR_CLOSED  STATUS12  STATUS13  SY_STATUS  SY_STATUS15
0            1999          NaN       1.0       1.0        1.0          1.0
1            1998          NaN       1.0       1.0        1.0          1.0
2            2003          NaN       1.0       1.0        1.0          1.0
3            1998          NaN       1.0       1.0        1.0          1.0
4            1998          NaN       1.0       1.0        1.0          1.0
5            2005          NaN       1.0       1.0        1.0          1.0
6            2005          NaN       1.0       1.0        1.0          1.0
7            2003          NaN       1.0       1.0        1.0          1.0
8            2003          NaN       1.0       1.0        1.0          1.0
9            2007          NaN       1.0       1.0        1.0          1.0
10           2008          NaN       1.0       1.0        1.0          1.0
12           1998          NaN       1.0       1.0        1.0          1.0
13           1998          NaN       1.0       1.0        1.0          1.0
14           1998          NaN       1.0       1.0        1.0          1.0
15           2002          NaN       1.0       1.0        1.0          1.0
16           2004          NaN       1.0       1.0        1.0          1.0
17           1998          NaN       1.0       1.0        1.0          1.0
18           1998          NaN       1.0       1.0        1.0          1.0
19           2002          NaN       1.0       1.0        1.0          1.0
20           2005          NaN       1.0       1.0        1.0          1.0
21           2008          NaN       1.0       1.0        1.0          1.0
22           2010          NaN       1.0       1.0        1.0          1.0
23           1998          NaN       1.0       1.0        1.0          1.0
24           1998          NaN       1.0       1.0        1.0          1.0
25           2004          NaN       1.0       1.0        1.0          1.0
26           2005          NaN       1.0       1.0        1.0          1.0
27           2009          NaN       1.0       1.0        1.0          1.0
28           2005          NaN       1.0       1.0        1.0          1.0
29           1998          NaN       1.0       1.0        1.0          1.0
30           1998          NaN       1.0       1.0        1.0          1.0
...           ...          ...       ...       ...        ...          ...
6917         1998          NaN       1.0       1.0        1.0          1.0
6918         1998          NaN       1.0       1.0        1.0          1.0
6919         1998          NaN       1.0       1.0        1.0          1.0
6920         1998          NaN       1.0       1.0        1.0          1.0
6921         1998          NaN       1.0       1.0        1.0          1.0
6922         1998          NaN       1.0       1.0        1.0          1.0
6923         1998          NaN       1.0       1.0        1.0          1.0
6924         1998          NaN       1.0       1.0        1.0          1.0
6925         1998          NaN       1.0       1.0        1.0          1.0
6926         1998          NaN       1.0       1.0        1.0          1.0
6927         1998          NaN       1.0       1.0        1.0          1.0
6928         1998          NaN       1.0       1.0        1.0          1.0
6929         1998          NaN       1.0       1.0        1.0          1.0
6930         1998          NaN       1.0       1.0        1.0          1.0
6931         1998          NaN       1.0       1.0        1.0          1.0
6932         1998          NaN       1.0       1.0        1.0          1.0
6933         1998          NaN       1.0       1.0        1.0          1.0
6934         1998          NaN       1.0       1.0        1.0          1.0
6935         1998          NaN       1.0       1.0        1.0          1.0
6936         1998          NaN       1.0       1.0        1.0          1.0
6937         1998          NaN       1.0       1.0        1.0          1.0
6938         1998          NaN       1.0       1.0        1.0          1.0
6939         1998          NaN       1.0       1.0        1.0          1.0
6940         1998          NaN       1.0       1.0        1.0          1.0
6941         1998          NaN       1.0       1.0        1.0          1.0
6942         1998          NaN       1.0       1.0        1.0          1.0
6943         1998       2016.0       1.0       1.0        1.0          1.0
6944         1998          NaN       1.0       1.0        1.0          1.0
6945         1998          NaN       1.0       1.0        1.0          1.0
6946         1998          NaN       1.0       1.0        1.0          1.0

[6405 rows x 6 columns]