In [9]:
import pandas as pd
folder_prefix = '/home/jovyan/work/'

In [10]:
pwd

'/home/jovyan/work/data_management/data/cleandata'

In [11]:
x = pd.read_csv('../../../nowdata/parsing/overlaps_removed_df.csv', encoding= 'latin-1')

ParserError: Error tokenizing data. C error: Expected 1133 fields in line 28, saw 2057

In [17]:
the_parsed = pd.read_csv(folder_prefix + "nowdata/parsing/overlaps_removed_df.csv", sep="\t", low_memory=False, encoding="utf-8")

In [18]:
the_parsed.sort_index(axis=1) #how to get alphabetically

,"% Civilian Population 16 to 19 Years: High School Graduate, or Enrolled (in School)","% Civilian Population 16 to 19 Years: Not High School Graduate, Not Enrolled (Dropped Out)",% Civilian Population in Labor Force 16 Years and Over: Employed,% Civilian Population in Labor Force 16 Years and Over: Unemployed,"% Employed Civilian Population 16 Years and Over: Agriculture, Forestry, Fishing and Hunting, and Mining","% Employed Civilian Population 16 Years and Over: Arts, Entertainment, and Recreation, and Accommodation and Food Services",% Employed Civilian Population 16 Years and Over: Construction,"% Employed Civilian Population 16 Years and Over: Educational Services, and Health Care and Social Assistance","% Employed Civilian Population 16 Years and Over: Finance and Insurance, and Real Estate and Rental and Leasing",% Employed Civilian Population 16 Years and Over: Information,...,close_rate13,close_rate14,close_rate15,close_rate16,close_rate99,ess_strength_x,ess_strength_y,index,prog_strength_x,prog_strength_y
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.0000,0.000000,0.000000,NaN,NaN,11229.0,NaN,NaN
1,88.03,11.97,81.70,18.30,0.83,3.50,3.89,36.46,3.12,1.71,...,0.000000,0.000000,0.0000,0.000000,0.000000,0.137931,0.137931,6555.0,0.034483,0.034483
2,89.50,10.50,92.43,7.57,4.12,7.45,7.89,21.39,5.10,2.36,...,0.000000,0.000000,0.0000,0.100000,0.000000,0.041058,0.041058,6557.0,0.105839,0.105839
3,89.50,10.50,92.43,7.57,4.12,7.45,7.89,21.39,5.10,2.36,...,0.000000,0.000000,0.0000,0.100000,0.000000,0.037500,0.037500,6556.0,0.087500,0.087500
4,96.88,3.12,93.95,6.05,3.63,10.46,6.39,23.01,4.86,2.44,...,0.000000,0.000000,0.0000,0.000000,0.010000,0.095385,0.095385,6565.0,0.087179,0.087179
5,96.88,3.12,93.95,6.05,3.63,10.46,6.39,23.01,4.86,2.44,...,0.000000,0.000000,0.0000,0.000000,0.010000,0.114286,0.114286,6564.0,0.028571,0.028571
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.0000,0.000000,0.010000,NaN,NaN,3754.0,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.0000,0.000000,0.010000,NaN,NaN,3755.0,NaN,NaN
8,96.88,3.12,93.95,6.05,3.63,10.46,6.39,23.01,4.86,2.44,...,0.000000,0.000000,0.0000,0.000000,0.010000,0.040000,0.040000,6563.0,0.320000,0.320000
9,96.88,3.12,93.95,6.05,3.63,10.46,6.39,23.01,4.86,2.44,...,0.000000,0.000000,0.0000,0.000000,0.010000,0.299401,0.299401,6566.0,0.101796,0.101796
10,96.88,3.12,93.95,6.05,3.63,10.46,6.39,23.01,4.86,2.44,...,0.000000,0.000000,0.0000,0.000000,0.010000,0.169069,0.169069,6562.0,0.110092,0.110092
11,96.88,3.12,93.95,6.05,3.63,10.46,6.39,23.01,4.86,2.44,...,0.000000,0.000000,0.0000,0.000000,0.010000,0.114987,0.114987,6561.0,0.077519,0.077519
12,96.88,3.12,93.95,6.05,3.63,10.46,6.39,23.01,4.86,2.44,...,0.000000,0.000000,0.0000,0.000000,0.010000,0.114286,0.114286,6560.0,0.028571,0.028571
13,96.88,3.12,93.95,6.05,3.63,10.46,6.39,23.01,4.86,2.44,...,0.000000,0.000000,0.0000,0.000000,0.010000,0.108716,0.108716,6559.0,0.148079,0.148079
14,96.88,3.12,93.95,6.05,3.63,10.46,6.39,23.01,4.86,2.44,...,0.000000,0.000000,0.0000,0.000000,0.010000,NaN,NaN,6558.0,NaN,NaN
15,98.08,1.92,95.07,4.93,4.20,7.40,6.22,22.15,3.65,2.36,...,0.000000,0.000000,0.0000,0.000000,0.000000,0.058824,0.058824,6567.0,0.227704,0.227704
16,93.75,6.25,91.29,8.71,12.46,9.65,7.97,24.22,3.68,1.12,...,0.000000,0.022222,0.0000,0.000000,0.024390,0.114286,0.114286,6571.0,0.028571,0.028571
17,93.75,6.25,91.29,8.71,12.46,9.65,7.97,24.22,3.68,1.12,...,0.000000,0.022222,0.0000,0.000000,0.024390,0.014963,0.014963,6570.0,0.374480,0.374480
18,93.75,6.25,91.29,8.71,12.46,9.65,7.97,24.22,3.68,1.12,...,0.000000,0.022222,0.0000,0.000000,0.024390,0.005208,0.005208,6569.0,0.036458,0.036458
19,93.75,6.25,91.29,8.71,12.46,9.65,7.97,24.22,3.68,1.12,...,0.000000,0.022222,0.0000,0.000000,0.024390,0.068421,0.068421,6568.0,0.257237,0.257237
20,95.54,4.46,90.14,9.86,5.88,8.13,12.25,23.17,3.02,2.42,...,0.000000,0.000000,0.0000,0.000000,0.000000,0.048151,0.048151,6577.0,0.051591,0.051591
21,95.54,4.46,90.14,9.86,5.88,8.13,12.25,23.17,3.02,2.42,...,0.000000,0.000000,0.0000,0.000000,0.000000,0.227273,0.227273,6576.0,0.181818,0.181818
22,95.54,4.46,90.14,9.86,5.88,8.13,12.25,23.17,3.02,2.42,...,0.000000,0.000000,0.0000,0.000000,0.000000,0.030864,0.030864,6575.0,0.074074,0.074074
23,95.54,4.46,90.14,9.86,5.88,8.13,12.25,23.17,3.02,2.42,...,0.000000,0.000000,0.0000,0.000000,0.000000,0.250000,0.250000,6574.0,0.000000,0.000000
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.0000,0.000000,0.000000,NaN,NaN,5067.0,NaN,NaN
25,95.54,4.46,90.14,9.86,5.88,8.13,12.25,23.17,3.02,2.42,...,0.000000,0.000000,0.0000,0.000000,0.000000,0.051252,0.051252,6573.0,0.052426,0.052426
26,95.54,4.46,90.14,9.86,5.88,8.13,12.25,23.17,3.02,2.42,...,0.000000,0.000000,0.0000,0.000000,0.000000,0.057273,0.057273,6572.0,0.230455,0.230455
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.0000,0.000000,0.000000,NaN,NaN,3756.0,NaN,NaN
28,87.00,13.00,89.76,10.24,4.85,6.50,3.53,36.49,3.14,0.44,...,0.000000,0.000000,0.0000,0.000000,0.000000,0.156667,0.156667,6580.0,0.283333,0.283333
29,97.92,2.08,91.54,8.46,2.72,9.05,7.99,27.07,2.82,1.80,...,0.000000,0.000000,0.0000,0.000000,0.028571,0.073307,0.073307,6584.0,0.085370,0.085370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10935,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11147.0,NaN,NaN
10936,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11146.0,NaN,NaN
10937,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11145.0,NaN,NaN
10938,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11144.0,NaN,NaN
10939,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11143.0,NaN,NaN
10940,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11142.0,NaN,NaN
10941,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11141.0,NaN,NaN
10942,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11140.0,NaN,NaN
10943,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11139.0,NaN,NaN
10944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,4146.0,NaN,NaN
10945,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,3335.0,NaN,NaN
10946,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,3334.0,NaN,NaN
10947,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11138.0,NaN,NaN
10948,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11137.0,NaN,NaN
10949,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11203.0,NaN,NaN
10950,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11204.0,NaN,NaN
10951,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11136.0,NaN,NaN
10952,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11135.0,NaN,NaN
10953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,4147.0,NaN,NaN
10954,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11133.0,NaN,NaN
10955,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11132.0,NaN,NaN
10956,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11131.0,NaN,NaN
10957,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11129.0,NaN,NaN
10958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,3345.0,NaN,NaN
10959,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11127.0,NaN,NaN
10960,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11227.0,NaN,NaN
10961,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11228.0,NaN,NaN
10962,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11225.0,NaN,NaN
10963,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11226.0,NaN,NaN
10964,95.46,4.54,82.30,17.70,1.37,9.30,5.36,23.60,5.39,1.98,...,0.006878,0.051939,0.0437,0.032675,0.010904,NaN,NaN,11224.0,NaN,NaN

In [32]:
the_parsed =the_parsed[['SCH_NAME','NCESSCH','YEAR_OPENED','MEMBER','ADDRESS16','PCTFRL', 'PCTETH']]
the_parsed

,SCH_NAME,NCESSCH,YEAR_OPENED,MEMBER,ADDRESS16,PCTFRL,PCTETH
0,NaN,1.001970e+10,2016.0,0.0,"3100 Cottage Hill Rd , Mobile AL 36606.0",NaN,NaN
1,NaN,2.000010e+10,1999.0,177.0,"1010 Fourth Avenue , Bethel AK 99559.0",0.905882,0.982353
2,NaN,2.001500e+10,1998.0,163.0,"410 Schoenbar , Ketchikan AK 99901.0",0.394737,0.668421
3,NaN,2.001500e+10,2003.0,183.0,"410 Schoenbar Road , Ketchikan AK 99901.0",0.579882,0.538462
4,NaN,2.001800e+10,1998.0,379.0,"1705 W 32nd Ave , Anchorage AK 99517.0",0.000000,0.262599
5,NaN,2.001800e+10,1998.0,541.0,"401 E Fireweed Lane Suite 100 , Anchorage AK ...",0.000000,0.385686
6,NaN,2.001800e+10,1998.0,0.0,NaN,NaN,NaN
7,NaN,2.001800e+10,1998.0,0.0,NaN,NaN,NaN
8,NaN,2.001800e+10,2005.0,267.0,"4802 Bryn MAWR Court , Anchorage AK 99508.0",0.000000,0.252747
9,NaN,2.001800e+10,2005.0,177.0,"10901 Mausel St Suite 101 , Eagle River AK 99...",0.000000,0.210227
10,NaN,2.001800e+10,2003.0,267.0,"400 W Northern Lights Blvd #9 , Anchorage AK ...",0.000000,0.281481
11,NaN,2.001800e+10,2003.0,193.0,"5530 E Northern Lights Suite 1 , Anchorage AK...",0.000000,0.429448
12,NaN,2.001800e+10,2007.0,443.0,"650 W International Airport Rd , Anchorage AK...",0.123932,0.196581
13,NaN,2.001800e+10,2008.0,334.0,"550 Bragaw Street , Anchorage AK 99504.0",1.024540,0.953988
14,NaN,2.001800e+10,2015.0,0.0,"616 W 10th Ave , Anchorage AK 99501.0",NaN,0.386139
15,NaN,2.002100e+10,1998.0,100.0,"430 Fourth Street , Juneau AK 99801.0",0.337838,0.472973
16,NaN,2.003900e+10,1998.0,188.0,"705 Frontage Rd Suite A , Kenai AK 99611.0",0.000000,0.154696
17,NaN,2.003900e+10,1998.0,103.0,"995 Soundview Ave , Homer AK 99603.0",0.489130,0.206522
18,NaN,2.003900e+10,2002.0,155.0,"162 E Park Street , Soldotna AK 99669.0",0.000000,0.179012
19,NaN,2.003900e+10,2004.0,253.0,"549 N Forest Dr , Kenai AK 99611.0",0.191406,0.308594
20,NaN,2.005100e+10,1998.0,234.0,"801 East Arctic , Palmer AK 99645.0",0.000000,0.178423
21,NaN,2.005100e+10,1998.0,192.0,"7362 W Parks #714 , Wasilla AK 99623.0",0.000000,0.174603
22,NaN,2.005100e+10,2002.0,185.0,"7362 W Parks Hwy #723 , Wasilla AK 99623.0",0.000000,0.247126
23,NaN,2.005100e+10,2005.0,315.0,"141 E Seldon Road Suite C , Wasilla AK 99654.0",0.000000,0.161125
24,NaN,2.005100e+10,2003.0,0.0,NaN,NaN,NaN
25,NaN,2.005100e+10,2008.0,249.0,"7010 E Bogard Road , Wasilla AK 99654.0",0.000000,0.257028
26,NaN,2.005100e+10,2010.0,360.0,"7101 E Palmer Wasilla Highway , Palmer AK 996...",0.000000,0.275773
27,NaN,2.005200e+10,1998.0,0.0,NaN,NaN,NaN
28,NaN,2.005700e+10,1998.0,60.0,"Mile 3.5 Nome-Teller Highway , Nome AK 99762.0",0.000000,0.754098
29,NaN,2.006000e+10,1998.0,150.0,"3002 International Street , Fairbanks AK 9970...",0.000000,0.203947
...,...,...,...,...,...,...,...
10935,NaN,7.200030e+11,1998.0,290.0,"URB JARDINES DE COUNTRY CLUB C , CAROLINA PR ...",0.861842,1.000000
10936,NaN,7.200030e+11,1998.0,649.0,"CALLE ALMENDRO VALLE ARRIBA HI , CAROLINA PR ...",0.882707,1.000000
10937,NaN,7.200030e+11,1998.0,402.0,"CARR 831 URB LOMAS VERDES , BAYAMON PR 956.0",1.205980,1.000000
10938,NaN,7.200030e+11,1998.0,310.0,"CALLE 10 URB MAGNOLIA GARDENS , BAYAMON PR 95...",0.979021,1.000000
10939,NaN,7.200030e+11,1998.0,179.0,"CALLE 19 URB FLAMBOYAN GARDENS , BAYAMON PR 9...",1.412281,1.000000
10940,NaN,7.200030e+11,1998.0,364.0,"CARR 840 KM 1 HM 1 SECTOR LA A , BAYAMON PR 9...",0.570191,1.000000
10941,NaN,7.200030e+11,1998.0,228.0,"URB SIERRA BAYAMON CALLE 33 , BAYAMON PR 961.0",1.297468,1.000000
10942,NaN,7.200030e+11,1998.0,371.0,"CARR 722 BO RABANAL , AIBONITO PR 705.0",1.112583,1.000000
10943,NaN,7.200030e+11,1998.0,603.0,"CARR 14 KM 46 HM 5 BO ASOMANTE , AIBONITO PR ...",0.961199,0.998236
10944,NaN,7.200030e+11,1998.0,0.0,NaN,NaN,NaN
10945,NaN,7.200030e+11,1998.0,197.0,NaN,NaN,NaN
10946,NaN,7.200030e+11,1998.0,175.0,NaN,NaN,NaN
10947,NaN,7.200030e+11,1998.0,200.0,"CARR 2 KM 44 HM 4 BO CANTERA , MANATI PR 674.0",0.849765,1.000000
10948,NaN,7.200030e+11,1998.0,348.0,"CARR 670 KM 4 HM 9 BO PUEBLITO , MANATI PR 67...",1.003185,1.000000
10949,NaN,7.200030e+11,1998.0,214.0,"CARR 2 KM 46 HM 8 BO CAMPO ALE , MANATI PR 67...",1.162651,0.987952
10950,NaN,7.200030e+11,1998.0,211.0,"CARR 566 KM 2 HM I BO SALTOS , OROCOVIS PR 72...",1.043716,1.000000
10951,NaN,7.200030e+11,1998.0,256.0,"CARR 157 KM 23 BO BARROS , OROCOVIS PR 720.0",0.807692,0.996503
10952,NaN,7.200030e+11,1998.0,637.0,"CARR 638 HM 5 BO MIRAFLORES , ARECIBO PR 612.0",0.993103,1.000000
10953,NaN,7.200030e+11,1998.0,0.0,NaN,NaN,NaN
10954,NaN,7.200030e+11,1998.0,348.0,"URB SANTA RITA CALLE 9 V. ALTA , VEGA ALTA PR...",1.197719,0.992395
10955,NaN,7.200030e+11,1998.0,199.0,"CARR 679 KM 2 HM 3 SECT FORTUN , VEGA ALTA PR...",0.900000,0.980000
10956,NaN,7.200030e+11,1998.0,835.0,"4 CALLE JULIO OTERO ESQ JOSE A , VEGA BAJA PR...",1.001326,1.000000
10957,NaN,7.200030e+11,1998.0,131.0,"CARR 155 KM 59 HM 9 BO PUGNADO , VEGA BAJA PR...",1.216495,1.000000
10958,NaN,7.200030e+11,1998.0,0.0,NaN,NaN,NaN
10959,NaN,7.200030e+11,1998.0,486.0,"CALLE COMERCIO URB. VERDUN , HORMIGUEROS PR 6...",1.032941,1.000000
10960,NaN,7.200030e+11,1998.0,477.0,"AVE LOS PATRIOTAS , LARES PR 669.0",0.827586,1.000000
10961,NaN,7.200030e+11,1998.0,181.0,"CARR. 111 KM.1.9 BO.HOYAMALA , SAN SEBASTIAN ...",1.131944,1.000000
10962,NaN,7.200030e+11,1998.0,427.0,"CALLE 612 AVE CAMPO RICO FINAL , CAROLINA PR ...",0.939173,1.000000
10963,NaN,7.200030e+11,1998.0,500.0,"CARR 152 CALLE GEORGETTY , NARANJITO PR 719.0",0.926380,1.000000
10964,NaN,7.200030e+11,1998.0,420.0,"CARR 188 KM 7 HM 2 , LOIZA PR 772.0",0.962025,1.000000

In [37]:
pd.options.display.float_format = '{:,.3f}'.format

In [38]:
the_parsed

,SCH_NAME,NCESSCH,YEAR_OPENED,MEMBER,ADDRESS16,PCTFRL,PCTETH
0,NaN,"10,019,702,432.000","2,016.000",0.000,"3100 Cottage Hill Rd , Mobile AL 36606.0",nan,nan
1,NaN,"20,000,100,329.000","1,999.000",177.000,"1010 Fourth Avenue , Bethel AK 99559.0",0.906,0.982
2,NaN,"20,015,000,306.000","1,998.000",163.000,"410 Schoenbar , Ketchikan AK 99901.0",0.395,0.668
3,NaN,"20,015,000,523.000","2,003.000",183.000,"410 Schoenbar Road , Ketchikan AK 99901.0",0.580,0.538
4,NaN,"20,018,000,172.000","1,998.000",379.000,"1705 W 32nd Ave , Anchorage AK 99517.0",0.000,0.263
5,NaN,"20,018,000,178.000","1,998.000",541.000,"401 E Fireweed Lane Suite 100 , Anchorage AK ...",0.000,0.386
6,NaN,"20,018,000,228.000","1,998.000",0.000,NaN,nan,nan
7,NaN,"20,018,000,315.000","1,998.000",0.000,NaN,nan,nan
8,NaN,"20,018,000,459.000","2,005.000",267.000,"4802 Bryn MAWR Court , Anchorage AK 99508.0",0.000,0.253
9,NaN,"20,018,000,460.000","2,005.000",177.000,"10901 Mausel St Suite 101 , Eagle River AK 99...",0.000,0.210
10,NaN,"20,018,000,530.000","2,003.000",267.000,"400 W Northern Lights Blvd #9 , Anchorage AK ...",0.000,0.281
11,NaN,"20,018,000,555.000","2,003.000",193.000,"5530 E Northern Lights Suite 1 , Anchorage AK...",0.000,0.429
12,NaN,"20,018,000,732.000","2,007.000",443.000,"650 W International Airport Rd , Anchorage AK...",0.124,0.197
13,NaN,"20,018,000,736.000","2,008.000",334.000,"550 Bragaw Street , Anchorage AK 99504.0",1.025,0.954
14,NaN,"20,018,000,756.000","2,015.000",0.000,"616 W 10th Ave , Anchorage AK 99501.0",nan,0.386
15,NaN,"20,021,000,268.000","1,998.000",100.000,"430 Fourth Street , Juneau AK 99801.0",0.338,0.473
16,NaN,"20,039,000,274.000","1,998.000",188.000,"705 Frontage Rd Suite A , Kenai AK 99611.0",0.000,0.155
17,NaN,"20,039,000,296.000","1,998.000",103.000,"995 Soundview Ave , Homer AK 99603.0",0.489,0.207
18,NaN,"20,039,000,448.000","2,002.000",155.000,"162 E Park Street , Soldotna AK 99669.0",0.000,0.179
19,NaN,"20,039,000,463.000","2,004.000",253.000,"549 N Forest Dr , Kenai AK 99611.0",0.191,0.309
20,NaN,"20,051,000,311.000","1,998.000",234.000,"801 East Arctic , Palmer AK 99645.0",0.000,0.178
21,NaN,"20,051,000,312.000","1,998.000",192.000,"7362 W Parks #714 , Wasilla AK 99623.0",0.000,0.175
22,NaN,"20,051,000,452.000","2,002.000",185.000,"7362 W Parks Hwy #723 , Wasilla AK 99623.0",0.000,0.247
23,NaN,"20,051,000,469.000","2,005.000",315.000,"141 E Seldon Road Suite C , Wasilla AK 99654.0",0.000,0.161
24,NaN,"20,051,000,524.000","2,003.000",0.000,NaN,nan,nan
25,NaN,"20,051,000,740.000","2,008.000",249.000,"7010 E Bogard Road , Wasilla AK 99654.0",0.000,0.257
26,NaN,"20,051,000,744.000","2,010.000",360.000,"7101 E Palmer Wasilla Highway , Palmer AK 996...",0.000,0.276
27,NaN,"20,052,000,255.000","1,998.000",0.000,NaN,nan,nan
28,NaN,"20,057,000,323.000","1,998.000",60.000,"Mile 3.5 Nome-Teller Highway , Nome AK 99762.0",0.000,0.754
29,NaN,"20,060,000,162.000","1,998.000",150.000,"3002 International Street , Fairbanks AK 9970...",0.000,0.204
...,...,...,...,...,...,...,...
10935,NaN,"720,003,001,462.000","1,998.000",290.000,"URB JARDINES DE COUNTRY CLUB C , CAROLINA PR ...",0.862,1.000
10936,NaN,"720,003,001,472.000","1,998.000",649.000,"CALLE ALMENDRO VALLE ARRIBA HI , CAROLINA PR ...",0.883,1.000
10937,NaN,"720,003,001,499.000","1,998.000",402.000,"CARR 831 URB LOMAS VERDES , BAYAMON PR 956.0",1.206,1.000
10938,NaN,"720,003,001,520.000","1,998.000",310.000,"CALLE 10 URB MAGNOLIA GARDENS , BAYAMON PR 95...",0.979,1.000
10939,NaN,"720,003,001,524.000","1,998.000",179.000,"CALLE 19 URB FLAMBOYAN GARDENS , BAYAMON PR 9...",1.412,1.000
10940,NaN,"720,003,001,533.000","1,998.000",364.000,"CARR 840 KM 1 HM 1 SECTOR LA A , BAYAMON PR 9...",0.570,1.000
10941,NaN,"720,003,001,560.000","1,998.000",228.000,"URB SIERRA BAYAMON CALLE 33 , BAYAMON PR 961.0",1.297,1.000
10942,NaN,"720,003,001,577.000","1,998.000",371.000,"CARR 722 BO RABANAL , AIBONITO PR 705.0",1.113,1.000
10943,NaN,"720,003,001,582.000","1,998.000",603.000,"CARR 14 KM 46 HM 5 BO ASOMANTE , AIBONITO PR ...",0.961,0.998
10944,NaN,"720,003,001,592.000","1,998.000",0.000,NaN,nan,nan
10945,NaN,"720,003,001,609.000","1,998.000",197.000,NaN,nan,nan
10946,NaN,"720,003,001,638.000","1,998.000",175.000,NaN,nan,nan
10947,NaN,"720,003,001,648.000","1,998.000",200.000,"CARR 2 KM 44 HM 4 BO CANTERA , MANATI PR 674.0",0.850,1.000
10948,NaN,"720,003,001,652.000","1,998.000",348.000,"CARR 670 KM 4 HM 9 BO PUEBLITO , MANATI PR 67...",1.003,1.000
10949,NaN,"720,003,001,654.000","1,998.000",214.000,"CARR 2 KM 46 HM 8 BO CAMPO ALE , MANATI PR 67...",1.163,0.988
10950,NaN,"720,003,001,675.000","1,998.000",211.000,"CARR 566 KM 2 HM I BO SALTOS , OROCOVIS PR 72...",1.044,1.000
10951,NaN,"720,003,001,677.000","1,998.000",256.000,"CARR 157 KM 23 BO BARROS , OROCOVIS PR 720.0",0.808,0.997
10952,NaN,"720,003,001,719.000","1,998.000",637.000,"CARR 638 HM 5 BO MIRAFLORES , ARECIBO PR 612.0",0.993,1.000
10953,NaN,"720,003,001,759.000","1,998.000",0.000,NaN,nan,nan
10954,NaN,"720,003,001,784.000","1,998.000",348.000,"URB SANTA RITA CALLE 9 V. ALTA , VEGA ALTA PR...",1.198,0.992
10955,NaN,"720,003,001,790.000","1,998.000",199.000,"CARR 679 KM 2 HM 3 SECT FORTUN , VEGA ALTA PR...",0.900,0.980
10956,NaN,"720,003,001,799.000","1,998.000",835.000,"4 CALLE JULIO OTERO ESQ JOSE A , VEGA BAJA PR...",1.001,1.000
10957,NaN,"720,003,001,809.000","1,998.000",131.000,"CARR 155 KM 59 HM 9 BO PUGNADO , VEGA BAJA PR...",1.216,1.000
10958,NaN,"720,003,001,823.000","1,998.000",0.000,NaN,nan,nan
10959,NaN,"720,003,001,861.000","1,998.000",486.000,"CALLE COMERCIO URB. VERDUN , HORMIGUEROS PR 6...",1.033,1.000
10960,NaN,"720,003,001,895.000","1,998.000",477.000,"AVE LOS PATRIOTAS , LARES PR 669.0",0.828,1.000
10961,NaN,"720,003,001,927.000","1,998.000",181.000,"CARR. 111 KM.1.9 BO.HOYAMALA , SAN SEBASTIAN ...",1.132,1.000
10962,NaN,"720,003,001,992.000","1,998.000",427.000,"CALLE 612 AVE CAMPO RICO FINAL , CAROLINA PR ...",0.939,1.000
10963,NaN,"720,003,001,995.000","1,998.000",500.000,"CARR 152 CALLE GEORGETTY , NARANJITO PR 719.0",0.926,1.000
10964,NaN,"720,003,002,002.000","1,998.000",420.000,"CARR 188 KM 7 HM 2 , LOIZA PR 772.0",0.962,1.000